TICondition.Numeric.EqualTo=等于 {0}
TICondition.Numeric.NotEqualTo=不等于 {0}
TICondition.Numeric.GreaterThan=> {0}
TICondition.Numeric.GreaterThanOrEqualTo=至少为 {0}
TICondition.Numeric.LessThan=< {0}
TICondition.Numeric.LessThanOrEqualTo=不多于 {0}
TINationCondition_Generic= {0} {1}的国家境内														// symbol, numeric comparison
TINationCondition_fMiltech= 军事科技等级为 {0} 的国家境内									// numeric comparison
TINationCondition_iControlPoints= 控制点为 {0} 的国家境内							// numeric comparison
TINationCondition_iArmies= 军队数量为 {0} 的国家境内										// numeric comparison
TINationCondition_efPublicOpinion= 公众支持 {0} {1} 的国家境内
TINationCondition_efPriority= 对 {0} 优先计划的投资点数百分比 {1} 的国家境内	// priority name, numeric pct comparison
TINationCondition_efMonthlyIPsToPriority= 对 {0} 优先计划每个月使用 {1} 投资点数的国家境内
TINationCondition_bFactionControlledTRUE= 受到任意阵营控制的国家境内
TINationCondition_bFactionControlledFALSE= 未受到阵营控制的国家境内
TINationCondition_bIsAlienNationTRUE= 在外星国家境内
TINationCondition_bIsAlienNationFALSE= 人类控制的国家境内
TINationCondition_bAnySpaceAssetsTRUE= 拥有运载力、地面控制中心或空间防御单位的国家境内
TINationCondition_bAnySpaceAssetsFALSE= 没有太空计划的国家境内
TINationCondition_bAggregateNationTRUE= 由较小的真实世界国家组成的聚合国家境内
TINationCondition_bAggregateNationFALSE= 非聚合国家境内
TINationCondition_bFactionHasControlTRUE= 受到 {0} 控制的国家境内
TINationCondition_bFactionHasControlFALSE= 未受到 {0} 控制的国家境内
TINationCondition_iNavies= 海军数量为 {0} 的国家境内
TINationCondition_bHasAntiSpaceDefensesTRUE= 配备有效反太空防御工事的国家境内
TINationCondition_bHasAntiSpaceDefensesFALSE= 未配备有效反太空防御工事的国家境内
TIRegionCondition= {0} {1} 的地区内
TIRegionCondition_bCoastalTRUE= 位于临海地区内
TIRegionCondition_bCoastalFALSE= 位于内陆地区
TIRegionCondition_bOnTheWaterTRUE= 位于目前可以通过海路前往的地区
TIRegionCondition_bOnTheWaterFALSE= 位于目前无法通过海路前往的地区内
TIRegionCondition_eEnvironment= 环境被分类为 {0} 的区域内
TIRegionCondition_eRugged= 地形为 {0} 的区域内
TIRegionCondition_fLatitude= 纬度为 {0} 的区域内
TIRegionCondition_fAbsLatitude= 赤道度为 {0} 的区域内
TIRegionCondition_fLongitude= 在纬度为 {0} 的地区
TIRegionCondition_fMonthlyBoost= 每月 {0}{1} 的区域内
TIRegionCondition_bCapitalTRUE= 国家的首都地区内
TIRegionCondition_bCapitalFALSE= 国家的非首都地区内
TIRegionCondition_bCoreEconomicTRUE= 核心经济区内
TIRegionCondition_bCoreEconomicFALSE= 非核心经济区域内
TIRegionCondition_bCoreResourceTRUE= 资源型地区内
TIRegionCondition_bCoreResourceFALSE= 非资源型地区内
TIRegionCondition_bColonyTRUE= 殖民地地区内
TIRegionCondition_bColonyFALSE= 非殖民地地区内
TIFactionCondition_eIdeologyEqualTo= 若为 {0}
TIFactionCondition_eIdeologyNotEqualTo= 若非 {0}
TIFactionCondition_bAlienProxyTRUE= 用于 {0}
TIFactionCondition_bAlienProxyFALSE= 用于 {0}
TIFactionCondition_bAlienAppeaserTRUE= 用于 {0}
TIFactionCondition_bAlienAppeaserFALSE= 若非 {0}
TIFactionCondition_efResourceValue= 当己方 {0} {1} 时
TIFactionCondition_iAtrocities= 当己方暴行总计 {0} 起时
TIFactionCondition_tbHasEffectTRUE= 当己方具备 {0} 效果时
TIFactionCondition_tbHasEffectFALSE= 当己方不具备 {0} 效果时
TIFactionCondition_bCouncilorHasTraitTRUE= 当理事具备 {0} 特质时
TIFactionCondition_bCouncilorHasTraitOrPredecessorTRUE= 当理事具备 {0} 或 {1} 特质时
TIFactionCondition_iCouncilorStat= 当理事的 {0} 属性 {1} 时
TIFactionCondition_bExtremistTRUE= 若为极端主义阵营
TIFactionCondition_bExtremistFALSE= 若为非极端主义阵营
TIFactionCondition_bProAlienTRUE= 若为支持外星人的阵营
TIFactionCondition_bProAlienFALSE= 若并非支持外星人的阵营
TIFactionCondition_bAntiAlienTRUE= 若为反对外星人的阵营
TIFactionCondition_bAntiAlienFALSE= 若并非反对外星人的阵营
TIFactionCondition_iAlienInvestigations= 当己方目前为止所调查的外星活动 {0} 时
TIFactionCondition_tbCompletedProject= 若为已完成 {0} 项目的阵营
TIFactionCondition_iAggregateStat= 当己方理事的 {0} 属性平均值 {1} 时
TIFactionCondition_iTotalStat= 当己方理事的 {0} 属性总和 {1} 时
TIFactionCondition_iHabs= 当该阵营拥有 {0} 个太空殖民地时
TIFactionCondition_iMines= 当该阵营拥有 {0} 座矿场时
TIFactionCondition_iHabSupportFailureLevel= 当该阵营的太空殖民地支持失败等级 {0} 时
TIFactionCondition_efResourceIncomeDaily= 当己方阵营的每日 {0} 收益 {1} 时
TIFactionCondition_bCynicalTRUE= 若为具有犬儒意识形态的阵营
TIFactionCondition_bBelieversTRUE= 若为具有理想主义意识形态的阵营
TIFactionCondition_fSpaceCombatValueLEO= 当己方阵营的舰队近地轨道总作战力量 {0} 时
TIFactionCondition_iSpaceDefenseFacilities= 当己方阵营控制配备主动太空防御工事的 {0} 区域时
TIFactionCondition_iAssassinatedHumans= 当此阵营所暗杀的人类理事总数{0}
TIFactionCondition_iAssassinatedAliens= 当此阵营所暗杀的外星特工人员总数{0}
TIFactionCondition_iAssassinations= 当此阵营成功实施的暗杀数量{0}
TICouncilorCondition_bInHomeNationTRUE= 当位于母国境内时
TICouncilorCondition_bInHomeNationFALSE= 未位于母国境内时
TICouncilorCondition_tbHasTraitHas= 当此理事具备 {0} 特质时
TICouncilorCondition_tbHasTraitDoesNotHave= 当此理事未具备 {0} 特质时
TICouncilorCondition_tbHasTraitOrPredecessorHas= 当此理事具备 {0} 或 {1} 特质时
TICouncilorCondition_tbHasTraitOrPredecessorDoesNotHave= 当此理事未具备 {0} 或 {1} 特质时
TICouncilorCondition_bHasTraitGroupingTRUE= 当此理事至少具备下列特质之一时：{0}
TICouncilorCondition_bHasTraitGroupingFALSE= 当此理事未具备下列至少一项特质时：{0}
TICouncilorCondition_bHasTraitWithTagTRUE= 当此理事至少具备下列特质之一时：{0}
TICouncilorCondition_bHasTraitWithTagFALSE= 当此理事未具备下列至少一项特质时：{0}
TICouncilorCondition_iStat= 当此理事的 {0} 属性 {1} 时
TICouncilorCondition_iStatWithoutOrgs= 当此理事的 {0} 属性 (没有组织) {1} 时
TICouncilorCondition_iNumLoseableOrgs= 若此理事的非专有组织组合 {0}时
TICouncilorCondition_iAssassinatedHumans= 当此理事所暗杀的人类理事总数{0}时
TICouncilorCondition_iAssassinatedAliens= 当此理事所暗杀的外星特工人员总数{0}时
TICouncilorCondition_iAssassinations= 当此理事成功实施的暗杀数量{0}时
TIHabCondition_tbHasModuleFunctioningTRUE= 若为具备 {0} 舱体的太空殖民地
TIHabCondition_tbHasModuleFunctioningFALSE= 若为未具备 {0} 舱体的太空殖民地
TIHabCondition_tbHasModuleOrUpgradePrereqFunctioningTRUE= 若为具备 {0} 或 {1} 舱体的太空殖民地
TIHabCondition_tbHasModuleOrUpgradePrereqFunctioningFALSE= 若为未具备 {0} 或 {1} 舱体的太空殖民地
TIGlobalCondition_bNuclearWeaponsUsed= 若参战国在此战役中曾使用核武器
TIGlobalCondition_tbCompletedTech= 若已研发 {0} 科技
TIGlobalCondition_fCampaignDuration_years= 若战役为期 {0} 年
TIGlobalCondition_bDummyConditionTRUE= 在任何情况下
TIGlobalCondition_bDummyConditionFALSE= 在任何情况下都不
TIHabCondition_fSpaceCombatValue= 若此太空殖民地的舱体防御分数为 {0}
TIHabCondition_fSpaceCombatValueFromDockedFleets= 若此太空殖民地的停泊飞船防御分数为 {0}
TIHabCondition_fAggregateDefensiveScore= 若此太空殖民地的舱体与停靠飞船防御分数为 {0}
TIHabCondition_bAllowsShipConstruction= 若此太空殖民地具备太空造船厂
TIHabCondition_fAssaultCombatValue= 若此太空殖民地的海军陆战队兵员数 {0}
TIHabCondition_fAssaultCombatValueFromDockedFleets= 若停靠在此太空殖民地的舰队搭载的海军陆战队兵员数 {0}
TIHabCondition_fAssaultCombatValueCombined= 若此太空殖民地或任何停靠的舰队上的海军陆战队兵员数 {0}
TIHabCondition_fMarineCombatValue= 若此太空殖民地的海军陆战队兵员数 {0}
TIHabCondition_fMarineCombatValueCombined= 若此太空殖民地或任何停靠的舰队上的海军陆战队兵员数 {0}
TIHabCondition_fConstructionTimeModifier= 若此太空殖民地的舱体提供的总建造时间修正 {0}
TIHabCondition_bHasConstructionModule= 若此太空殖民地具备建造舱体
TIHabCondition_fTechBonus= 当此太空殖民地的舱体提供的 {0} 研发加成 {1} 时
TIHabCondition_efResourceIncomeAnnual= 当此太空殖民地的年 {0} 收益 {1} 时
TIHabCondition_bHasSpecialRule= 若此太空殖民地的某一舱体具备 {0} 特殊规则
TIHabCondition_fPowerToSectorRatio= 当此太空殖民地的电力与区域比率 {0}
TIArmyCondition_bFactionControlledTRUE= 若为受到任意阵营控制的军队
TIArmyCondition_fNationMiltechDifferential= 当此军队的军事科技与目前区域的军事科技之间的差距 {0} 时
TISpaceShipCondition_bHasSpecialRuleTRUE= 若为具备单个 {0} 设施舱体的飞船
TISpaceShipCondition_iModulesWithSpecialRule= 若为具备 {1} {0} 设施舱体的飞船
TISpaceShipCondition_bLaserBonusPowerTRUE= 若为具备激光引擎设施舱体的飞船
TISpaceShipCondition_tbHasUtilityModuleTypeTRUE= 若为具备 {0} 设施舱体的飞船
TISpaceShipCondition_tiNumberOfUtilityModulesType= 若为 {0} 设施舱体数量 {1} 的飞船
TISpaceShipCondition_fAssaultCombatValue= 若此舰船的海军陆战队兵员数 {0}