Context.displayName.CanContactAliens=外星人联络
Context.displayName.AlienRelationsEstablished=外星人关系
Context.displayName.CanTransferTerritoryToAliens=外星管理调动
Context.displayName.DetectAliensOnEarth=外星人侦测
Context.displayName.DetectAlienActivity=外星人活动侦测
Context.displayName.CanCaptureHydra=外星人俘虏
Context.displayName.DetectAlienSpaceAssetsRange=外星人太空资产侦测范围
Context.displayName.PherocyteResistance=费洛细胞抗性
Context.displayName.ManyAliensOnEarth=外星人在地球上存在的迹象
Context.displayName.CouncilSize=阵营理事会规模
Context.displayName.NewCouncilorRecruitXP=通过招募获得的理事经验值加成
Context.displayName.MaxAvailableOrgs=最大组织卖场规模
Context.displayName.HumanLifespan=人类寿命
Context.displayName.AdvancedAircraft=进阶飞船
Context.displayName.ControlPointMaintenance=控制点上限
Context.displayName.ConsolidatePowerDurationMultiplier=巩固行政权力持续时间
Context.displayName.BilateralRelationsCooldownMultiplier=双边关系冷却时间
Context.displayName.ProjectUnlockChance=计划解锁几率
Context.displayName.MonthlyProjectTriggerChance=月度计划触发几率
Context.displayName.EconomyPriority=经济优先计划投资
Context.displayName.Economy_BasePCGDPIncrease=经济优先计划<color=#FFFFFFFF><sprite name="per_capita_GDP"></color>变动
Context.displayName.Economy_CoreEcoPCGDPMultiplier=核心经济区加成
Context.displayName.Economy_ResourcePCGDPMultiplier=石油产区/矿区加成
Context.displayName.Economy_InequalityMultiplier=经济优先计划<color=#FFFFFFFF><sprite name="inequality"></color>变动
Context.displayName.WelfarePriority=福利优先计划投资
Context.displayName.WelfareInequalityReductionBonus=福利优先计划<color=#FFFFFFFF><sprite name="inequality"></color>变动
Context.displayName.EnvironmentPriority=环境优先计划投资
Context.displayName.Environment_SustainabilityChange=环境可持续性变动
Context.displayName.Environment_BestSustainabilityValue=最大国家可持续性价值
Context.displayName.Welfare_CO2_ppm=环境优先计划二氧化碳减排
Context.displayName.Welfare_CH4_ppm=环境优先计划甲烷减排
Context.displayName.Welfare_N2O_ppm=环境优先计划一氧化二氮减排
Context.displayName.KnowledgePriority=知识优先计划投资
Context.displayName.GovernmentPriority=政府优先计划投资
Context.displayName.UnityPriority=团结优先计划投资
Context.displayName.OppressionPriority=镇压优先计划投资
Context.displayName.SpoilsPriority=牟利优先计划投资
Context.displayName.SpoilsOutput=牟利<color=#FFFFFFFF><sprite name="currency"></color>收益
Context.displayName.SpaceDevPriority=资金优先计划投资
Context.displayName.SpaceflightPriority=启动民用太空飞行计划投资
Context.displayName.LaunchFacilitiesPriority=运载力优先计划投资
Context.displayName.MissionControlPriority=任务管控力优先计划投资
Context.displayName.MilitaryPriority=军事优先计划投资
Context.displayName.BuildArmyPriority=建立军队优先计划投资
Context.displayName.UpgradeArmyPriority=建立海军优先计划投资
Context.displayName.BuildNuclearWeaponsPriority=建造核武器优先计划投资
Context.displayName.BuildSpaceDefensesPriority=建造太空防御设施优先计划投资
Context.displayName.BuildSTOSquadronPriority=建造轨道站战斗机优先计划投资
Context.displayName.DirectInvestGlobalDiscount_Money_PCT=直接投资<color=#FFFFFFFF><sprite name="currency"></color>折扣
Context.displayName.DirectInvestGlobalDiscount_Influence_PCT=直接投资<color=#FFFFFFFF><sprite name="influence"></color>折扣
Context.displayName.DirectInvestGlobalDiscount_Ops_PCT=直接投资<color=#FFFFFFFF><sprite name="ops"></color>折扣
Context.displayName.DetectHumanCouncilorsOnEarth=地球上的敌方人类理事侦测
Context.displayName.MaxMissionSliderSteps=最大任务加成成本
Context.displayName.Mission_Terrorize_Def=恐吓任务防御
Context.displayName.Mission_Abductions_Att=绑架任务
Context.displayName.Mission_Abductions_Def=绑架任务防御施
Context.displayName.Mission_EnthrallElites_Def=操纵精英任务防御
Context.displayName.Mission_EnthrallPublic_Def=操纵公众任务防御
Context.displayName.Mission_GainControlPoint=所有获得控制点任务
Context.displayName.Mission_Propaganda_Att=宣传任务
Context.displayName.Mission_HostileTakeover_Att=恶意收购任务
Context.displayName.Mission_HostileTakeover_Def=恶意收购任务防御
Context.displayName.Mission_SabotageProject_Att=破坏计划任务
Context.displayName.Mission_SabotageProject_Def=破坏计划任务防御
Context.displayName.Mission_StealProject_Att=窃取计划任务
Context.displayName.Mission_StealProject_Def=窃取计划任务防御
Context.displayName.Mission_Assassination_Att=暗杀任务
Context.displayName.Mission_Assassinate_Def=暗杀任务防御
Context.displayName.Mission_ControlAsset_Def=控制太空资产任务防御
Context.displayName.Mission_Unrest_Att=增加动乱任务
Context.displayName.Mission_Stabilize_Att=稳定任务
Context.displayName.Mission_Turn_Att=启动理事任务
Context.displayName.Mission_Inspire_Att=激励任务
Context.displayName.Mission_Crackdown_Att=镇压任务
Context.displayName.Mission_Crackdown_Def=镇压任务防御
Context.displayName.Mission_Purge_Att=肃清任务
Context.displayName.Mission_Purge_Def=肃清任务防御
Context.displayName.Mission_SabotageFacilities_Att=破坏设施任务
Context.displayName.Mission_SabotageFacilities_Def=破坏设施任务防御
Context.displayName.Mission_SabotageHabModule_Att=破坏太空殖民地舱体任务
Context.displayName.Mission_SabotageHabModule_Def=破坏太空殖民地舱体任务防御
Context.displayName.Mission_SeizeSpaceAsset_Att=夺取太空资产任务
Context.displayName.Mission_SeizeSpaceAsset_Def=夺取太空资产任务防御
Context.displayName.Mission_Detain_Att=拘留任务
Context.displayName.Mission_Detain_Def=拘留任务防御
Context.displayName.Mission_Xenoform_Def=异变任务防御
Context.displayName.Mission_AssaultAlienAsset_Att=外星资产攻击任务
Context.displayName.Mission_Coup_Att=政变任务
Context.displayName.Mission_InvestigateCouncilor_Att=调查理事任务
Context.displayName.PublicCampaignStrength=宣传任务影响
Context.displayName.DefendInterestEarthDuration=捍卫利益任务持续时间
Context.displayName.InterrogationBonus=拘留获得的情报加成
Context.displayName.Corruption=国家腐败
Context.displayName.BreakawayChance=国家分裂
Context.displayName.AtrocityMitigation=减缓暴行影响
Context.displayName.PostRegimeChangeUnrestReduction=友方政权更迭动乱
Context.displayName.PostRegimeLossUnrestIncrease=敌方政权更迭动乱
Context.displayName.ArmyUnrestReductionImpact=减少军队动乱
Context.displayName.ArmyHealRate=军队维修率
Context.displayName.ArmyUrbanWarfare=军队城市战斗
Context.displayName.ArmyRuggedWarfare=军队崎岖地形战斗
Context.displayName.XenoformingDestructionStrength=对异变的伤害
Context.displayName.ArmyDamageBonustoMegafauna=军队对外星巨兽的伤害加成
Context.displayName.ArmyDamageBonustoInvaderArmy=军队对外星军队的伤害加成
Context.displayName.ArmyDamageBonustoHumanArmy=军队对常规军队的伤害加成
Context.displayName.ArmyDamageBonustoAllArmies=军队在所有战斗中的伤害加成
Context.displayName.MegafaunaDamageMitigation=缓解外星巨兽伤害
Context.displayName.MegafaunaRepellent=巨兽驱避
Context.displayName.MegafaunaMastery=驾驭巨兽
Context.displayName.ArmyNuclearHardening=军队核战争抗性
Context.displayName.NuclearStrikeDamageReduction=区域核战争抗性
Context.displayName.BombardmentArmyDefenseBonus=军队轰炸抗性
Context.displayName.LaserDefenseType=区域激光防御武器类别
Context.displayName.LaserDefenseFreq=区域激光防御武器频率
Context.displayName.MCFreeSpaceMineNetwork=太空地雷网络任务管控力成本
Context.displayName.HabMissionControlReduction=太空殖民地任务管控力
Context.displayName.ShipMissionControlReduction=舰船任务管控力
Context.displayName.AlienHateFromMCUsage=向外星人隐藏任务管控力的使用
Context.displayName.MissionControlDisruption_PCT=任务管控力干扰
Context.displayName.CanFoundTier1Station=建造空间平台
Context.displayName.CanFoundTier2Station=建造轨道站
Context.displayName.CanFoundTier3Station=建造环状空间站
Context.displayName.CanFoundTier1Base=建造前哨站
Context.displayName.CanFoundTier2Base=建造大型殖民地
Context.displayName.CanFoundTier3Base=建造超大殖民地
Context.displayName.CanFoundAutomatedT1Station=建造自动化空间平台
Context.displayName.CanFoundAutomatedT1Base=建造自动化前哨站
Context.displayName.GenericModuleTransferTime=地球至舰船和太空殖民地舱体的转移时间 
Context.displayName.GenericTransferEV_kps=舰船和太空殖民地舱体的运载力成本
Context.displayName.GenericTransfer_OffDate_PCT=地球至舰船和太空殖民地舱体的霍曼转移时间
Context.displayName.ProbeTransferTime=探测器速度
Context.displayName.InnerExplorationRange_AU=内太阳系探索
Context.displayName.ExploreLuna=月球探索
Context.displayName.ExploreEarthLagrangePoints=日地拉格朗日点探索
Context.displayName.OuterExplorationRange_AU=外太阳系探索
Context.displayName.SpaceCameraResolution=太空成像分辨率
Context.displayName.HabResearchProduction=太空殖民地研究力生产
Context.displayName.BombardmentHabDefenseBonus=基地轰炸抗性
Context.displayName.CanAmassAntimatter=储备反物质
Context.displayName.CanAmassExotics=储备异星物质
Context.displayName.SpaceMiningBonus=太空采矿与精炼
Context.displayName.MiningWaterBonus=水冰开采与精炼
Context.displayName.MiningVolatilesBonus=挥发物开采与精炼
Context.displayName.MiningMetalsBonus=金属开采与精炼
Context.displayName.MiningNoblesBonus=贵金属开采与精炼
Context.displayName.MiningFissilesBonus=裂变物质开采与精炼
Context.displayName.ResourceMarketSales=太空资源市场销售
Context.displayName.ShipConstructionTime=舰船建造时间
Context.displayName.ShipOfficerPromotion=舰船军官晋升
Context.displayName.Ship_MaxSurvivableCombatAcceleration_Bonus=可承受的最大舰船战斗加速度
Context.displayName.Ship_MaxSurvivableCruiseAcceleration_Bonus=可承受的最大舰船巡航加速度
Context.displayName.DockyardRepairSpeed=太空殖民地舰船修复速度
Context.displayName.ShipLaserDamage=舰船激光伤害
Context.displayName.ParticleLaserDamage=舰船粒子武器伤害
Context.displayName.ShipMagDamage=舰船磁力武器伤害
Context.displayName.ShipConvMissileDamage=舰船常规导弹伤害
Context.displayName.BonusDamagetoAlienShips=对外星舰船的伤害            					// not coded
Context.displayName.GlobalECMBonus=电子反制措施强度
Context.displayName.STOFighterECM=<skip/>
Context.displayName.HumanECMAgainstAliens=电子反制措施能力
Context.displayName.TargetingComputerBonus=瞄准用计算机能力
Context.displayName.GlobalTargetingBonus=战斗瞄准
Context.displayName.MissileECM=导弹电子反制措施
Context.displayName.DamageReductionAgainstAllShips=舰船伤害减免
Context.displayName.DamageReductionAgainstAlienShips=舰船对外星人的伤害减免
Context.displayName.ShipLaserCooldownTime=舰船激光冷却时间              						// not coded
Context.displayName.ShipLaserEfficiencyBonus=舰船激光效率           					// not coded
Context.displayName.ShipMagWeaponEfficiencyBonus=舰船磁力武器能效       			// not coded
Context.displayName.ShipMagRechargeTime=舰船磁力武器冷却时间                			// not coded
Context.displayName.ShipWeaponTargetingRange=舰船目标射程           					// not coded
Context.displayName.Combat_ShipRepairSpeed=战斗中舰船修复速度
Context.displayName.SpaceAssaultBonus=太空突袭
Context.displayName.BombardmentDamageBonus=轰炸伤害
Context.displayName.MiningOutputPerformanceRecord=<skip/>
Context.displayName.BuddyMovie=<skip/>
Context.displayName.FakedDeath=<skip/>
Context.displayName.MarkedChain=<skip/>
Context.displayName.MarkedCombatChain=<skip/>
Context.displayName.InfiltratedCombatChain=<skip/>
Context.displayName.InfiltratedMoneyChain=<skip/>
Context.displayName.InfiltratedInfluenceChain=<skip/>
Context.displayName.InfiltratedChain=<skip/>
Context.displayName.InfiltratedCount=<skip/>
Context.displayName.VaccineChips=疫苗晶片
Context.displayName.InfluenceLies=<skip/>

TIEffectTemplate.displayName.Effect_DetectAbductions=侦测绑架							// ALL NUMBERED TAGS IN THIS FILE DO THE SAME THING IF THEY HAVE THE SAME NUMBER. You can use any tag between {0} and {13} when localizing in this file; all are checked for all strings
TIEffectTemplate.description.Effect_DetectAbductions=- 允许阵营侦测地球上的外星人绑架事件
TIEffectTemplate.displayName.Effect_DetectEnthralls=侦测操纵行动
TIEffectTemplate.description.Effect_DetectEnthralls=- 允许阵营侦测外星人与人类的接触
TIEffectTemplate.description.Effect_DetectAllOperations=- 允许侦测所有的外星人行动
TIEffectTemplate.description.Effect_DetectAlienMovements=- 允许直接侦测所有外星特工
TIEffectTemplate.description.Effect_Skywatch=- 允许所有阵营追踪土星轨道内的外星舰船及建筑
TIEffectTemplate.description.Effect_DeepSkywatch=- 允许阵营追踪太阳系内任何地方的外星舰船及建筑
TIEffectTemplate.description.Effect_ExploreVenus=- 允许在金星之上建造空间站
TIEffectTemplate.description.Effect_ExploreInnerPlanets=- 允许发射探测器到水星，并在水星上建造太空殖民地
TIEffectTemplate.description.Effect_ExploreLuna=- 允许发射探测器到月球，并在月球表面建造太空殖民地
TIEffectTemplate.description.Effect_ExploreMars=- 允许发射探测器到火星和内太阳系小行星，并在这些地点建造太空殖民地
TIEffectTemplate.description.Effect_ExploreEarthLagrangePoints=- 允许对地球轨道地区范围内的日地拉格朗日点和小行星进行勘探和建设
TIEffectTemplate.description.Effect_ExploreAsteroids=- 允许发射探测器到小行星带并建造太空殖民地
TIEffectTemplate.description.Effect_ExploreJupiter=- 允许发射探测器到木星，并在木星卫星上及其周围建造太空殖民地
TIEffectTemplate.description.Effect_ExploreSaturn=- 允许发射探测器到土星，并在土星卫星上及其周围建造太空殖民地
TIEffectTemplate.description.Effect_ExploreOuterPlanets=- 允许发射探测器到天王星和海王星，并在外太阳系建造太空殖民地
TIEffectTemplate.description.Effect_ExploreKuiperBelt=- 允许发射探测器到古柏带，并在古柏带建造太空殖民地
TIEffectTemplate.description.Effect_TechProbeSpeed=- 对于这项科技做出更多贡献的阵营，能够更快地扫描天体
TIEffectTemplate.description.Effect_CanFoundTier1Station=- 允许阵营建造空间平台
TIEffectTemplate.description.Effect_CanFoundTier2Station=- 允许阵营建造轨道站
TIEffectTemplate.description.Effect_CanFoundTier3Station=- 允许阵营建造环状空间站
TIEffectTemplate.description.Effect_CanFoundTier1Base=- 允许阵营建造前哨站
TIEffectTemplate.description.Effect_CanFoundTier2Base=- 允许阵营建造大型殖民地
TIEffectTemplate.description.Effect_CanFoundTier3Base=- 允许阵营建造超大殖民地
TIEffectTemplate.description.Effect_CanFoundAutomatedT1Station=- 允许阵营建造自动化空间平台
TIEffectTemplate.description.Effect_CanFoundAutomatedT1Base=- 使阵营能建造自动化前哨站
TIEffectTemplate.description.Effect_CanAmassAntimatter=- 允许阵营储备大量反物质
TIEffectTemplate.description.Effect_CanAmassExotics=- 允许阵营储备大量外来物
TIEffectTemplate.description.Effect_CanCaptureHydra=- 使阵营能捕捉和关押外星人活体
TIEffectTemplate.description.Effect_CanContactAliens=- 允许阵营派遣理事执行与外星人的接触任务
TIEffectTemplate.description.Effect_AlienRelationsEstablished=- 建立和外星人之间的通讯频道
TIEffectTemplate.description.Effect_CooperateTransferTerritorytoAliens=- 允许我方将领土转让给外星国家
TIEffectTemplate.description.Effect_AppeaseTransferTerritoryToAliens=- 允许我方将领土转让给外星国家
TIEffectTemplate.description.Effect_SubmitTransferTerritoryToAliens=- 允许我方将领土转让给外星国家
TIEffectTemplate.description.Effect_GlobalListeningNetwork=- 我方理事在侦测外星人时获得 +1 调查
TIEffectTemplate.description.Effect_SpaceTugs=- 火箭动力拖船运送太空殖民地舱体的速度加快 {18}																					// 18: value as percentage increase
TIEffectTemplate.description.Effect_SolarSteamers=- 长途货物运输使用持续的推力，将发射时间窗口外发射的太空殖民地舱体的运送时间缩短 {4}		//  4: value as percentage decrease
TIEffectTemplate.description.Effect_NuclearFreighters=- 核动力货运船运送太空殖民地舱体的速度加快 {18}
TIEffectTemplate.description.Effect_FusionFreighters=- 廉价聚变驱动器使我方运送太空殖民地舱体的速度加快 {18}
TIEffectTemplate.description.Effect_FastProbes=- 探测器抵达目的地的速度加快 {18}																	
TIEffectTemplate.description.Effect_IncreaseCouncilSize=- 允许我方招募一名额外的理事
TIEffectTemplate.description.Effect_SpaceMarketEfficiency1=- 我方在地球市场贩卖太空资源时，获得的收入增加 {3}									// 3: value to %
TIEffectTemplate.description.Effect_SpaceMarketEfficiency2=- 我方在地球市场贩卖太空资源时，获得的收入增加 {3}
TIEffectTemplate.description.Effect_AdvancedAircraft=<skip/>
TIEffectTemplate.description.Effect_IncreaseMaxAvailableOrgs5=- 每个月可额外取得 {0} 个组织										// 0: value
TIEffectTemplate.description.Effect_IncreaseMaxArmyTechLevel=- 所有人类国家的最大军事科技等级提高 {0} 级
TIEffectTemplate.description.Effect_AllowSpaceDefensesConstruction=- 解锁一项优先计划，使国家能在所属地区建造地表对轨道防御设施
TIEffectTemplate.description.Effect_AllowBuildSTOFighters=- 解锁一项优先计划，使国家能建造地对轨道战斗机，可以利用助推器发射，攻击近地轨道上的目标
TIEffectTemplate.description.Effect_AllowDecontaminateRegion=- 环境优先计划允许各国对遭受核攻击的地区进行净化
TIEffectTemplate.description.Effect_SpaceScan=- 立刻揭露我方侦测范围内的所有外星舰船和太空殖民地
TIEffectTemplate.description.Effect_MajorGlobalPropaganda=- 使{14}在全世界的民意显著改善											// 14: 1st faction displayName (colored)
TIEffectTemplate.description.Effect_GlobalPropagandaForSecondary10=- 使{2}在全世界的民意显著改善									// 2: 2nd target displayName (so could be nation, faction, or something else depending on context)
TIEffectTemplate.description.Effect_NegativeGlobalPropaganda10=- {21}在全世界的民意恶化													// 21: 1st faction displayName (capitalized & colored)
TIEffectTemplate.description.Effect_NegativeGlobalPropaganda25=- {21}在全世界的民意大幅恶化
TIEffectTemplate.description.Effect_NegativeGlobalPropaganda_Secondary50=- {22}在全世界的民意大幅恶化                         		// 22: 2nd faction displayName (capitalized+colored)
TIEffectTemplate.description.Effect_NegativeGlobalPropaganda_Secondary75=- {22}在全世界的民意大幅恶化                          		
TIEffectTemplate.description.Effect_GlobalPropaganda=- 使{14}在全世界的民意有所改善
TIEffectTemplate.description.Effect_MinorGlobalPropaganda=- 使{14}在全世界的民意稍微改善
TIEffectTemplate.description.Effect_NationPropaganda=- 使{14}在{5}的民意显著改善															// 5: nation displayName with location preposition - "in France"
TIEffectTemplate.description.Effect_MajorNationPropaganda=- 使{14}在{5}的民意大幅度改善
TIEffectTemplate.description.Effect_NegativeNationPropaganda=- 使{5}的部分民意背离{14}
TIEffectTemplate.description.Effect_NegativeNationPropaganda25=- {14}在{5}的民意显著恶化
TIEffectTemplate.description.Effect_NegativeNationPropaganda5_PerCP=- 我方每拥有一个控制点，{5}就会有一小部分民意背离{14}
TIEffectTemplate.description.Effect_NegativeNationPropaganda10_PerCP=- 我方每拥有一个控制点，{5}就会有部分民意背离{14}
TIEffectTemplate.description.Effect_MinusculeSingleRegionDamage=- 对{10}的经济和人口造成轻微损害									// 10: region displayName
TIEffectTemplate.description.Effect_MinorSingleRegionDamage=- 对{10}的经济和人口造成有限损害
TIEffectTemplate.description.Effect_MajorSingleRegionDamage=- 对{10}的经济和人口造成严重损害
TIEffectTemplate.description.Effect_MassiveSingleRegionDamage=- 对{10}的经济和人口造成极大损害
TIEffectTemplate.description.Effect_TotalSingleRegionDamage=- 对{10}的经济和人口造成毁灭性破坏
TIEffectTemplate.description.Effect_NuclearDetonation025=- 一枚核弹头于{10}爆炸，对其经济和人口造成重大损害
TIEffectTemplate.description.Effect_NuclearDetonation05=- 一枚核弹头于{10}爆炸，对其经济和人口造成极大损害
TIEffectTemplate.description.Effect_SecondaryMinusculeSingleRegionDamage=- 对{12}的经济和人口造成轻微损害							// 12: region display name -- a city. Can also say "in the region of {12}" if necessary			
TIEffectTemplate.description.Effect_SecondaryMinorSingleRegionDamage=- 对{12}的经济和人口造成有限损害
TIEffectTemplate.description.Effect_SecondaryMajorSingleRegionDamage=- 对{12}的经济和人口造成严重损害
TIEffectTemplate.description.Effect_SecondaryMassiveSingleRegionDamage=- 对{12}的经济和人口造成极大损害
TIEffectTemplate.description.Effect_SecondaryNuclearDetonation025=- 一枚核弹头于{12}爆炸，对其经济和人口造成极大损害			
TIEffectTemplate.description.Effect_SecondaryNuclearDetonation05=- 一枚核弹头于{12}爆炸，对其经济和人口造成极大损害
TIEffectTemplate.description.Effect_MajorRegionBoostDamage=- {10}失去其大部分的运载力
TIEffectTemplate.description.Effect_MinorRegionBoostDamage=- {10}失去其少量的运载力
TIEffectTemplate.displayName.Effect_LocalProsperity=经济繁荣
TIEffectTemplate.description.Effect_LocalProsperity=- {9}的 GDP 实现增长，不平等与环境破坏也随之轻微加剧						// 9: nation displayName
TIEffectTemplate.displayName.Effect_MajorLocalProsperity=经济腾飞
TIEffectTemplate.description.Effect_MajorLocalProsperity=- {9}的 GDP 实现显著增长，不平等与环境破坏也随之加剧
TIEffectTemplate.displayName.Effect_LocalProsperity50=经济繁荣
TIEffectTemplate.description.Effect_LocalProsperity50=- {9}的 GDP 实现增长，不平等与环境破坏也随之轻微加剧
TIEffectTemplate.displayName.Effect_LocalProsperity200=经济繁荣
TIEffectTemplate.description.Effect_LocalProsperity200=- {9}的 GDP 实现增长，不平等与环境破坏也随之轻微加剧
TIEffectTemplate.displayName.Effect_SecondaryProsperity1=经济繁荣
TIEffectTemplate.description.Effect_SecondaryProsperity1=- {11}的 GDP 实现增长，不平等与环境破坏也随之轻微加剧				// 11: 2nd nation displayName
TIEffectTemplate.displayName.Effect_SecondaryProsperity2=经济繁荣
TIEffectTemplate.description.Effect_SecondaryProsperity2=- {11}的 GDP 实现增长，不平等与环境破坏也随之轻微加剧
TIEffectTemplate.displayName.Effect_SecondaryProsperity3=经济繁荣
TIEffectTemplate.description.Effect_SecondaryProsperity3=- {11}的 GDP 实现增长，不平等与环境破坏也随之轻微加剧
TIEffectTemplate.displayName.Effect_LocalRecession=经济衰退
TIEffectTemplate.description.Effect_LocalRecession=- {9}的 GDP 出现下滑，不平等加剧
TIEffectTemplate.displayName.Effect_MajorLocalRecession=经济大萧条
TIEffectTemplate.description.Effect_MajorLocalRecession=- {9}的 GDP 出现大幅下滑，不平等加剧
TIEffectTemplate.displayName.Effect_LocalRecession50=经济衰退
TIEffectTemplate.description.Effect_LocalRecession50=- {9}的 GDP 出现大幅下滑，不平等加剧
TIEffectTemplate.displayName.Effect_FreePriorityWelfare10=福利投资
TIEffectTemplate.description.Effect_FreePriorityWelfare10=- {9}将会稍微增加对社会福利及环保计划的投资
TIEffectTemplate.displayName.Effect_FreePriorityWelfare50=福利投资
TIEffectTemplate.description.Effect_FreePriorityWelfare50=- {9}将会大幅增加对社会福利及环保计划的投资
TIEffectTemplate.displayName.Effect_FreePriorityWelfare200=福利投资
TIEffectTemplate.description.Effect_FreePriorityWelfare200=- {9}将会极大增加对社会福利及环保计划的投资
TIEffectTemplate.displayName.Effect_FreePriorityKnowledge10=知识投资
TIEffectTemplate.description.Effect_FreePriorityKnowledge10=- {9}将会稍微增加对职业培训和教育计划上的投资
TIEffectTemplate.displayName.Effect_FreePriorityKnowledge20=知识投资
TIEffectTemplate.description.Effect_FreePriorityKnowledge20=- {9}将会显著增加对职业培训和教育计划上的投资
TIEffectTemplate.displayName.Effect_FreePriorityMilitary10=军事投资
TIEffectTemplate.description.Effect_FreePriorityMilitary10=- {9}将会稍微增加对军事训练及采购的投资
TIEffectTemplate.displayName.Effect_FreePriorityMilitary20=军事投资
TIEffectTemplate.description.Effect_FreePriorityMilitary20=- {9}将会显著增加对军事训练及采购的投资
TIEffectTemplate.displayName.Effect_SecondaryFreePriorityMilitary20=军事投资
TIEffectTemplate.description.Effect_SecondaryFreePriorityMilitary20=- {11}将会显著增加对军事训练及采购的投资								
TIEffectTemplate.displayName.Effect_FreePriorityMilitary200=军事投资
TIEffectTemplate.description.Effect_FreePriorityMilitary200=- {9}将会极大增加对军事训练及采购的投资
TIEffectTemplate.displayName.Effect_FreePriorityBoost1=运载力投资
TIEffectTemplate.description.Effect_FreePriorityBoost1=- {9}将会增加对太空发射及太空飞行上的投资
TIEffectTemplate.displayName.Effect_FreePriorityBoost2=运载力投资
TIEffectTemplate.description.Effect_FreePriorityBoost2=- {9}将会显著增加对太空发射及太空飞行上的投资
TIEffectTemplate.displayName.Effect_FreePriorityFunding1=基金投资
TIEffectTemplate.description.Effect_FreePriorityFunding1=- {9}将会拨出一部分预算作为自由分配基金
TIEffectTemplate.displayName.Effect_XenoformingReduction=异种消亡
TIEffectTemplate.description.Effect_XenoformingReduction=- {10}地区的异变传播缩小															// 10: region displayName
TIEffectTemplate.displayName.Effect_XenoformingReduction100=异种消亡
TIEffectTemplate.description.Effect_XenoformingReduction100=- {10}地区的所有异种会被彻底根除
TIEffectTemplate.displayName.Effect_XenoformingIncrease25=异种增长
TIEffectTemplate.description.Effect_XenoformingIncrease25=- {10}地区的异变传播会小幅扩大
TIEffectTemplate.displayName.Effect_XenoformingIncrease50=异种增长
TIEffectTemplate.description.Effect_XenoformingIncrease50=- {10}地区的异变传播会中幅扩大
TIEffectTemplate.displayName.Effect_XenoformingIncrease75=异种增长
TIEffectTemplate.description.Effect_XenoformingIncrease75=- {10}地区的异变传播会大幅扩大
TIEffectTemplate.displayName.Effect_XenoformingIncrease100=异种增长
TIEffectTemplate.description.Effect_XenoformingIncrease100=- {10}地区的异变传播会极大幅扩大
TIEffectTemplate.displayName.Effect_MinorExposure=轻微暴露
TIEffectTemplate.description.Effect_MinorExposure=- 关于{14}的信息会被暴露给我方的敌人									
TIEffectTemplate.displayName.Effect_MajorExposure=重大暴露
TIEffectTemplate.description.Effect_MajorExposure=- 关于{14}的大量信息会被暴露给我方的敌人
TIEffectTemplate.displayName.Effect_CouncilorExposure=理事暴露
TIEffectTemplate.description.Effect_CouncilorExposure=- 关于{1}的大量信息会被暴露给我方的敌人
TIEffectTemplate.description.Effect_SmallDemocracyGain=- {9}的民主值变动 {0}																				// 9: 1st nation displayName, 0: value
TIEffectTemplate.displayName.Effect_SmallDemocracyLoss=轻微民主损失
TIEffectTemplate.description.Effect_SmallDemocracyLoss=- {9}的民主值变动 {0}																				
TIEffectTemplate.displayName.Effect_DemocracyLoss02=民主损失
TIEffectTemplate.description.Effect_DemocracyLoss02=- {9}的民主值变动 {0}
TIEffectTemplate.displayName.Effect_DemocracyLoss05=民主损失
TIEffectTemplate.description.Effect_DemocracyLoss05=- {9}的民主值变动 {0}
TIEffectTemplate.displayName.Effect_DemocracyLoss1=民主损失
TIEffectTemplate.description.Effect_DemocracyLoss1=- {9}的民主值变动 {0}
TIEffectTemplate.displayName.Effect_DemocracyLoss5=重大民主损失
TIEffectTemplate.description.Effect_DemocracyLoss5=- {9}的民主值变动 {0}
TIEffectTemplate.displayName.Effect_DemocracyLoss7=重大民主损失
TIEffectTemplate.description.Effect_DemocracyLoss7=- {9}的民主值变动 {0}
TIEffectTemplate.description.Effect_DemocracyLossSecondary1=- {11}的民主值变动 {0}
TIEffectTemplate.displayName.Effect_SecondaryTargetPropaganda=宣传
TIEffectTemplate.description.Effect_SecondaryTargetPropaganda=- {15}在{5}的民意改善																		// 15: 2nd faction displayName (colored), 5: 1st nation displayName with location preposition - "in France"
TIEffectTemplate.displayName.Effect_SecondaryTargetNegativePropaganda10=宣传
TIEffectTemplate.description.Effect_SecondaryTargetNegativePropaganda10=- {15}在{5}的民意恶化																
TIEffectTemplate.description.Effect_SecondaryTargetPropagandaGlobal10=- 全世界对{15}的民意改善													
TIEffectTemplate.description.Effect_SecondaryTargetPropaganda_Faction10=- {21}在{5}的民意改善																// 21: 1st faction displayName (capitalized & colored),
TIEffectTemplate.description.Effect_SecondaryTargetPropaganda_Faction25=- {21}在{5}的民意改善																
TIEffectTemplate.description.Effect_SecondaryTargetRegionPropaganda15=- {1}地区对{15}的民意改善													// 21: 1st faction displayName (capitalized & colored), region displayName
TIEffectTemplate.description.Effect_SecondaryTargetNegativePropaganda_Faction10=- {21}在{6}的民意恶化															//  6: 2nd nation displayName with preposition
TIEffectTemplate.description.Effect_SecondaryTargetNegativePropaganda_Faction25=- {21}在{6}的民意恶化														
TIEffectTemplate.displayName.Effect_SecondaryMiltechLoss=国家军事科技等级降低
TIEffectTemplate.description.Effect_SecondaryMiltechLoss=- {11}的军事科技等级降低 {0}																		// 11: 2nd nation displayName, 0: value
TIEffectTemplate.displayName.Effect_SecondaryMiltechLoss02=国家军事科技等级降低
TIEffectTemplate.description.Effect_SecondaryMiltechLoss02=- {11}的军事科技等级降低 {0}
TIEffectTemplate.displayName.Effect_MiltechLoss005=国家军事科技等级降低
TIEffectTemplate.description.Effect_MiltechLoss005=- {9}的军事科技等级降低 {0}																				// 9: 1st nation displayName
TIEffectTemplate.displayName.Effect_MiltechLoss01=国家军事科技等级降低
TIEffectTemplate.description.Effect_MiltechLoss01=- {9}的军事科技等级降低 {0}
TIEffectTemplate.displayName.Effect_MiltechLoss02=国家军事科技等级降低
TIEffectTemplate.description.Effect_MiltechLoss02=- {9}的军事科技等级降低 {0}
TIEffectTemplate.displayName.Effect_MiltechGain005=国家军事科技等级提高
TIEffectTemplate.description.Effect_MiltechGain005=- {9}的军事科技等级提高 {0}
TIEffectTemplate.displayName.Effect_MiltechGain01=国家军事科技等级提升
TIEffectTemplate.description.Effect_MiltechGain01=- {9}的军事科技等级提高 {0}
TIEffectTemplate.displayName.Effect_MiltechGain02=国家军事科技等级提升
TIEffectTemplate.description.Effect_MiltechGain02=- {9}的军事科技等级提高 {0}
TIEffectTemplate.displayName.Effect_MiltechGain03=国家军事科技等级提升
TIEffectTemplate.description.Effect_MiltechGain03=- {9}的军事科技等级提升 {0}
TIEffectTemplate.displayName.Effect_MassiveCohesionLoss=凝聚力重大损失
TIEffectTemplate.description.Effect_MassiveCohesionLoss=- {5}的凝聚力变动 {0}																						// 5: 1st nation displayName with location preposition - "in France"
TIEffectTemplate.displayName.Effect_MajorCohesionGain=凝聚力大幅提升
TIEffectTemplate.description.Effect_MajorCohesionGain=- {5}的凝聚力会增加 {23}
TIEffectTemplate.displayName.Effect_MajorCohesionLoss=凝聚力大幅降低
TIEffectTemplate.description.Effect_MajorCohesionLoss=- {5}的凝聚力变动 {23}
TIEffectTemplate.displayName.Effect_MinorCohesionLoss=凝聚力降低
TIEffectTemplate.description.Effect_MinorCohesionLoss=- {5}的凝聚力变动 {23}
TIEffectTemplate.displayName.Effect_MinorCohesionGain=国家获得凝聚力
TIEffectTemplate.description.Effect_MinorCohesionGain=- {9}获得 {23} 凝聚力
TIEffectTemplate.displayName.Effect_SecondaryCohesionGain=国家获得凝聚力
TIEffectTemplate.description.Effect_SecondaryCohesionGain=- {11}获得 {24} 凝聚力
TIEffectTemplate.displayName.Effect_SecondaryCohesionLoss=凝聚力降低
TIEffectTemplate.description.Effect_SecondaryCohesionLoss=- {6}的凝聚力变动 {24}
TIEffectTemplate.description.Effect_MajorCohesionOutward=- {5}的凝聚力变动 {23} 并趋向极端数值
TIEffectTemplate.description.Effect_MinorCohesionOutward=- {5}的凝聚力变动 {23} 并趋向极端数值
TIEffectTemplate.description.Effect_MajorGlobalCohesionOutward=- 所有国家的凝聚力改变 {0} 并趋向极端数值
TIEffectTemplate.description.Effect_MinorGlobalCohesionOutward=- 所有国家的凝聚力改变 {0} 并趋向极端数值
TIEffectTemplate.displayName.Effect_GlobalCohesionGain=所有国家获得凝聚力
TIEffectTemplate.description.Effect_GlobalCohesionGain=- 所有国家获得 {0} 凝聚力
TIEffectTemplate.displayName.Effect_MinorGlobalCohesionGain=所有国家获得凝聚力
TIEffectTemplate.description.Effect_MinorGlobalCohesionGain=- 所有国家获得 {0} 凝聚力
TIEffectTemplate.displayName.Effect_GlobalCohesionLoss=所有国家损失凝聚力
TIEffectTemplate.description.Effect_GlobalCohesionLoss=- 所有国家获得 {0} 凝聚力
TIEffectTemplate.displayName.Effect_MajorGlobalCohesionLoss=所有国家损失凝聚力
TIEffectTemplate.description.Effect_MajorGlobalCohesionLoss=- 所有国家获得 {0} 凝聚力
TIEffectTemplate.displayName.Effect_TotalGlobalCohesionLoss=所有国家损失凝聚力
TIEffectTemplate.description.Effect_TotalGlobalCohesionLoss=- 所有国家获得 {0} 凝聚力
TIEffectTemplate.displayName.Effect_MaximumUnrestGain=动乱飙升
TIEffectTemplate.description.Effect_MaximumUnrestGain=- {5}的动乱增加 {0}																					// 5: 1st nation name with preposition ("in France"), 0: value
TIEffectTemplate.displayName.Effect_MassiveUnrestGain=动乱飙升
TIEffectTemplate.description.Effect_MassiveUnrestGain=- {5}的动乱增加 {0}																				
TIEffectTemplate.displayName.Effect_MajorUnrestGain=动乱飙升
TIEffectTemplate.description.Effect_MajorUnrestGain=- {5}的动乱增加 {0}																					
TIEffectTemplate.displayName.Effect_MajorUnrestLoss=动乱平息
TIEffectTemplate.description.Effect_MajorUnrestLoss=- {5}的动乱变动 {0}
TIEffectTemplate.displayName.Effect_MinorUnrestGain=动乱增加
TIEffectTemplate.description.Effect_MinorUnrestGain=- {5}的动乱增加 {0}
TIEffectTemplate.displayName.Effect_MinorUnrestLoss=动乱减少
TIEffectTemplate.description.Effect_MinorUnrestLoss=- {5}的动乱变动 {0}
TIEffectTemplate.displayName.Effect_MajorUnrestGain_ByFaction=动乱飙升
TIEffectTemplate.description.Effect_MajorUnrestGain_ByFaction=- {5}的动乱增加 {0}																			
TIEffectTemplate.displayName.Effect_MajorUnrestLoss_ByFaction=动乱平息
TIEffectTemplate.description.Effect_MajorUnrestLoss_ByFaction=- {5}的动乱变动 {0}
TIEffectTemplate.displayName.Effect_MinorUnrestGain_ByFaction=动乱增加
TIEffectTemplate.description.Effect_MinorUnrestGain_ByFaction=- {5}的动乱增加 {0}
TIEffectTemplate.displayName.Effect_MinorUnrestLoss_ByFaction=动乱减少
TIEffectTemplate.description.Effect_MinorUnrestLoss_ByFaction=- {5}的动乱变动 {0}
TIEffectTemplate.displayName.Effect_SecondaryMassiveUnrestGain_ByFaction=动乱飙升
TIEffectTemplate.description.Effect_SecondaryMassiveUnrestGain_ByFaction=- {6}的动乱增加 {0}																// 6: 2nd nation name with preposition ("in France")
TIEffectTemplate.displayName.Effect_SecondaryMajorUnrestGain_ByFaction=动乱飙升
TIEffectTemplate.description.Effect_SecondaryMajorUnrestGain_ByFaction=- {6}的动乱增加 {0}																
TIEffectTemplate.displayName.Effect_SecondaryMajorUnrestLoss_ByFaction=动乱平息
TIEffectTemplate.description.Effect_SecondaryMajorUnrestLoss_ByFaction=- {6}的动乱变动 {0}
TIEffectTemplate.displayName.Effect_SecondaryMinorUnrestGain_ByFaction=动乱增加
TIEffectTemplate.description.Effect_SecondaryMinorUnrestGain_ByFaction=- {6}的动乱增加 {0}
TIEffectTemplate.displayName.Effect_SecondaryMinorUnrestLoss_ByFaction=动乱减少
TIEffectTemplate.description.Effect_SecondaryMinorUnrestLoss_ByFaction=- {6}的动乱变动 {0}
TIEffectTemplate.displayName.Effect_MajorInequalityGain=不平等飙升
TIEffectTemplate.description.Effect_MajorInequalityGain=- {5}的不平等增加 {23}
TIEffectTemplate.displayName.Effect_ModerateInequalityGain=不平等加剧
TIEffectTemplate.description.Effect_ModerateInequalityGain=- {5}的不平等增加 {23}
TIEffectTemplate.displayName.Effect_MinorInequalityGain=- 不平等逐渐加剧
TIEffectTemplate.description.Effect_MinorInequalityGain=- {5}的不平等增加 {23}
TIEffectTemplate.displayName.Effect_MinorInequalityLoss=- 不平等逐渐缓和
TIEffectTemplate.description.Effect_MinorInequalityLoss=- {5}的不平等降低 {23}
TIEffectTemplate.displayName.Effect_EducationLoss=人才流失
TIEffectTemplate.description.Effect_EducationLoss=- {5}的教育变动 {23}
TIEffectTemplate.displayName.Effect_EducationGain01=人才流入
TIEffectTemplate.description.Effect_EducationGain01=- {5}的教育变动 {0}
TIEffectTemplate.displayName.Effect_GDPGain01=国家 GDP 增长
TIEffectTemplate.description.Effect_GDPGain01=- {5}的 GDP 变动 {3}																								// 3: value to %
TIEffectTemplate.displayName.Effect_GDPGain02=国家 GDP 增长
TIEffectTemplate.description.Effect_GDPGain02=- {5}的 GDP 变动 {3}
TIEffectTemplate.displayName.Effect_GDPLoss02=国家 GDP 下滑
TIEffectTemplate.description.Effect_GDPLoss02=- {5}的 GDP 变动 {3}
TIEffectTemplate.displayName.Effect_GDPLoss04=国家 GDP 下滑
TIEffectTemplate.description.Effect_GDPLoss04=- {5}的 GDP 变动 {3}
TIEffectTemplate.displayName.Effect_GDPLoss20=国家 GDP 暴跌
TIEffectTemplate.description.Effect_GDPLoss20=- {5}的 GDP 变动 {3}
TIEffectTemplate.displayName.Effect_GDPLoss50=国家 GDP 崩溃
TIEffectTemplate.description.Effect_GDPLoss50=- {5}的 GDP 变动 {3}
TIEffectTemplate.description.Effect_GlobalGDPLoss1=- 所有国家的 GDP 变动 {3}
TIEffectTemplate.description.Effect_GlobalGDPLoss2=- 所有国家的 GDP 变动 {3}
TIEffectTemplate.description.Effect_GlobalGDPLoss3=- 所有国家的 GDP 变动 {3}
TIEffectTemplate.description.Effect_GlobalGDPLoss10=- 所有国家的 GDP 变动 {3}
TIEffectTemplate.displayName.Effect_GlobalGDPLoss50=全球经济崩溃
TIEffectTemplate.description.Effect_GlobalGDPLoss50=- 所有国家的 GDP 变动 {3}
TIEffectTemplate.displayName.Effect_GlobalGDPLossByCPTrigger=全球经济受影响
TIEffectTemplate.description.Effect_GlobalGDPLossByCPTrigger=- 所有国家的 GDP 下滑，程度取决于触发国家规模
TIEffectTemplate.displayName.Effect_SecondaryGDPLoss=国家 GDP 下滑
TIEffectTemplate.description.Effect_SecondaryGDPLoss=- {6}的 GDP 变动 {3}
TIEffectTemplate.displayName.Effect_SecondaryGDPLoss02=国家 GDP 下滑
TIEffectTemplate.description.Effect_SecondaryGDPLoss02=- {6}的 GDP 变动 {3}
TIEffectTemplate.displayName.Effect_SecondaryGDPLoss04=国家 GDP 下滑
TIEffectTemplate.description.Effect_SecondaryGDPLoss04=- {6}的 GDP 变动 {3}
TIEffectTemplate.displayName.Effect_SecondaryInequalityIncrease=国家不平等加剧
TIEffectTemplate.description.Effect_SecondaryInequalityIncrease=- {11}获得 {0} 不平等
TIEffectTemplate.displayName.Effect_SecondaryGDPGain=国家 GDP 增长
TIEffectTemplate.description.Effect_SecondaryGDPGain=- {6}的 GDP 增长 {3}
TIEffectTemplate.displayName.Effect_SecondaryMiltechGain=国家军事科技等级提高
TIEffectTemplate.description.Effect_SecondaryMiltechGain=- {11}的军事科技等级提高 {0}																		// 11: 1st region displayName
TIEffectTemplate.description.Effect_NukeAdd1=- {9}的军火库将增加 {0} 次核轰炸																		//  0: value, 9: 1st nation displayName
TIEffectTemplate.description.Effect_NukeRemove1=- {9}的军火库将移除 {19} 次核轰炸																// 19: Multiple the input value by -1 to output a normal value
TIEffectTemplate.description.Effect_NukeRemoveSecondary1=- {11}的军火库将移除 {19} 次核轰炸
TIEffectTemplate.description.Effect_LooseNukeAdd1=- 世界上的未严控核弹数量改变 {0}
TIEffectTemplate.description.Effect_LooseNukeAdd3=- 世界上的未严控核弹数量改变 {0}
TIEffectTemplate.description.Effect_LooseNukeRemove1=- 世界上的未严控核弹数量改变 {0}
TIEffectTemplate.description.Effect_ShipNukeAdd1=- {1}上的一个核鱼雷发射管将增加 {0} 枚弹头													// 1: 1st target displayName
TIEffectTemplate.description.Effect_ShipNukeRemove1=- {1}上核鱼雷的数量变动 {0}
TIEffectTemplate.displayName.Effect_UpgradeRelations=关系改善
TIEffectTemplate.description.Effect_UpgradeRelations=- {9}和{11}之间的关系改善
TIEffectTemplate.displayName.Effect_DowngradeRelations=关系恶化
TIEffectTemplate.description.Effect_DowngradeRelations=- {9}和{11}之间的关系恶化
TIEffectTemplate.displayName.Effect_DeclareLimitedWar=战争爆发
TIEffectTemplate.description.Effect_DeclareLimitedWar=- 仅限于{9}和{11}之间的战争爆发了
TIEffectTemplate.displayName.Effect_DeclareFullWar=战争爆发
TIEffectTemplate.description.Effect_DeclareFullWar=- {9}和{11}之间的战争爆发，且{11}所有的盟友都加入了
TIEffectTemplate.displayName.Effect_RevealRegionAlienActivities=此地区近期的外星人活动被揭露了
TIEffectTemplate.description.Effect_RevealRegionAlienActivities=- 此地区近期的外星人活动被揭露了
TIEffectTemplate.displayName.Effect_Atrocity=暴行
TIEffectTemplate.description.Effect_Atrocity=- {21}犯下暴行																									// 21: 1st faction displayName (Capitalized & Colored)
TIEffectTemplate.description.Effect_EconomyPriorityBonus02=- 我方投入于经济优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_EconomyPriorityBonus05=- 我方投入于经济优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_EconomyPriorityBonus1=- 我方投入于经济优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_WelfarePriorityBonus05=- 我方投入于福利优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_KnowledgePriorityBonus02=- 我方投入于知识优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_KnowledgePriorityBonus05=- 我方投入于知识优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_KnowledgePriorityBonus1=- 我方投入于知识优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_MilitaryPriorityBonus02=- 我方投入于军事优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_MilitaryPriorityBonus05=- 我方投入于军事优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_BuildArmyPriorityBonus05=- 我方投入于建立军队优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_UpgradeArmyPriorityBonus05=- 我方投入于建立海军优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_LaunchFacilitiesPriorityBonus05=- 我方投入于运载力优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_LaunchFacilitiesPriorityBonus1=- 我方投入于运载力优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_LaunchFacilitiesPriorityBonus15=- 我方投入于运载力优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_LaunchFacilitiesPriorityBonus2=- 我方投入于运载力优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_LaunchFacilitiesPriorityBonus25=- 我方投入于运载力优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_SpaceflightProgramPriorityBonus05=- 我方投入于太空飞行优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_SpaceflightProgramPriorityBonus50=- 我方投入于太空飞行优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_MissionControlPriorityBonus05=- 我方投入于任务管控力优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_MissionControlPriorityBonus25=- 我方投入于任务管控力优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_UnityPriorityBonus05=- 我方投入于团结优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_BuildSpaceDefensesPriority05=- 我方投入于建立太空防御设施优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_BuildSpaceDefensesPriority10=- 我方投入于建立太空防御设施优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_BuildSpaceDefensesPriority95=- 我方投入于建立太空防御设施优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_OppressionPriority05=- 我方投入于镇压优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_OppressionPriority10=- 我方投入于压制优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_GovernmentPriority05=- 我方投入于政府优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_GovernmentPriority10=- 我方投入于政府优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_EnvironmentPriority05=- 我方投入于环境优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_EnvironmentPriority10=- 我方投入于环境优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_BuildSTOSquadronPriority05=- 我方投入于建立轨道站战斗机优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_BuildSTOSquadronPriority10=- 我方投入于建立轨道站战斗机优先计划的国家投资点增加 {3}
TIEffectTemplate.description.Effect_DirectInvestMoneyReduction15=- 直接投资花费的金钱减少 {3}
TIEffectTemplate.description.Effect_DirectInvestInfluenceReduction25=- 直接投资花费的影响力减少 {3}
TIEffectTemplate.displayName.Effect_ArcticMethaneRelease=北极甲烷释放
TIEffectTemplate.description.Effect_ArcticMethaneRelease=- 地球大气中的甲烷增加 {0} ppm
TIEffectTemplate.displayName.Effect_CO2Fires=大气二氧化碳增加
TIEffectTemplate.description.Effect_CO2Fires=- 地球大气中的二氧化碳增加 {0} ppm
TIEffectTemplate.displayName.Effect_AerosolsFires=高空烟雾
TIEffectTemplate.description.Effect_AerosolsFires=- 平流层气溶胶增加 {0} ppm
TIEffectTemplate.displayName.Effect_AerosolsVolcano=火山灰及浓烟释放至平流层
TIEffectTemplate.description.Effect_AerosolsVolcano=- 平流层气溶胶增加 {0} ppm
TIEffectTemplate.displayName.Effect_AerosolsMajorVolcano=大量火山灰及浓烟释放至平流层
TIEffectTemplate.description.Effect_AerosolsMajorVolcano=- 平流层气溶胶增加 {0} ppm
TIEffectTemplate.displayName.Effect_AerosolsColossalVolcano=极大量的火山灰及浓烟释放至平流层
TIEffectTemplate.description.Effect_AerosolsColossalVolcano=- 平流层气溶胶增加 {0} ppm
TIEffectTemplate.description.Effect_SpaceMiningBonus5=- 地球外采矿产出增加 {3}
TIEffectTemplate.description.Effect_SpaceMiningBonus10=- 地球外采矿产出增加 {3}
TIEffectTemplate.description.Effect_SolidFuelRockets=- 减少从地球运送材料至近地轨道外时的运载力消耗。使用运载力传输时将使用 {0} kps 排气速度来计算成本。
TIEffectTemplate.description.Effect_LiquidFuelRockets=- 减少从地球运送材料至近地轨道外时的运载力消耗。使用运载力传输时将使用 {0} kps 排气速度来计算成本。
TIEffectTemplate.description.Effect_NuclearRockets=- 减少从地球运送材料至近地轨道外时的运载力消耗。使用运载力传输时将使用 {0} kps 排气速度来计算成本。
TIEffectTemplate.description.Effect_CryogenicFuelRockets=- 减少从地球运送材料至近地轨道外时的运载力消耗。使用运载力传输时将使用 {0} kps 排气速度来计算成本。
TIEffectTemplate.description.Effect_ImprovedRockets=- 减少从地球运送材料至近地轨道外时的运载力消耗。使用运载力传输时将使用 {0} kps 排气速度来计算成本。
TIEffectTemplate.description.Effect_AdvancedRockets=- 减少从地球运送材料至近地轨道外时的运载力消耗。使用运载力传输时将使用 {0} kps 排气速度来计算成本。
TIEffectTemplate.description.Effect_ManyAliensOnEarth=- 地球上现在有大量外星人口
TIEffectTemplate.description.Effect_PherocyteResistance=- 增强我方抵抗外星人费洛细胞影响的能力
TIEffectTemplate.description.Effect_MinorFloodingRiskIncrease=- 严重水灾的发生频率增加，导致全球 GDP 下滑
TIEffectTemplate.description.Effect_ModerateFloodingRiskIncrease=- 严重水灾的发生频率显著增加，导致全球 GDP 下滑
TIEffectTemplate.description.Effect_MajorFloodingRiskIncrease=- 严重水灾带来持续威胁，许多区域完全被水淹没，导致全球 GDP 下滑
TIEffectTemplate.description.Effect_ArcticOceanBlue=- {1}地区的海岸现已可全年通达
TIEffectTemplate.description.Effect_GainOpenControlPoint=- 获得一个开放控制点
TIEffectTemplate.description.Effect_GainAnyControlPoint=- 获得这个国家内的一个随机控制点
TIEffectTemplate.description.Effect_GainAnyControlPoint_Plus=- 获得这个国家内的一个随机控制点，且该控制点会处于看守状态 {0} 个月
TIEffectTemplate.description.Effect_LoseUndefendedControlPoint=- 一个未设防的控制点被另一个阵营夺走
TIEffectTemplate.description.Effect_LoseUndefendedControlPoint_Plus=- 一个未设防的控制点被另一个阵营夺走，且该控制点会处于看守状态 {0} 个月
TIEffectTemplate.description.Effect_CrackdownArmyControlPoint=- 这支军队管辖的控制点会遭受镇压，持续 {0} 个月
TIEffectTemplate.description.Effect_IncreaseMaxMissionSliderSteps=- 提升可用来增加任务成功率的资源数量上限
TIEffectTemplate.description.Effect_ShipConstructionTimeReduction5=- 舰船建造速度加快 {18}																					//18: value to percentage increase
TIEffectTemplate.description.Effect_ShipConstructionTimeReduction10=- 舰船建造速度加快 {18}
TIEffectTemplate.description.Effect_ShipConstructionTimeReduction=- 舰船建造速度加快 {18}
TIEffectTemplate.displayName.Effect_FactionSoftPower=阵营软实力
TIEffectTemplate.description.Effect_FactionSoftPower=- 获取控制点或太空殖民地控制权的任务获得 +{0}
TIEffectTemplate.description.Effect_IncreaseMonthlyMoneyIncome2=- {21}每月的金钱收入增加 {0}																	// 21: 1st faction displayName (Capitalized & Colored)
TIEffectTemplate.description.Effect_IncreaseMonthlyMoneyIncome10=- {21}每月的金钱收入增加 {0}
TIEffectTemplate.description.Effect_IncreaseMonthlyMoneyIncome200=- {21}每月的金钱收入增加 {0}
TIEffectTemplate.description.Effect_DecreaseMonthlyMoneyIncome5=- {21}每月的金钱收入减少 {0}
TIEffectTemplate.description.Effect_DecreaseMonthlyMoneyIncome10=- {21}每月的金钱收入减少 {0}
TIEffectTemplate.description.Effect_DecreaseMonthlyMoneyIncome25=- {21}每月的金钱收入减少 {0}
TIEffectTemplate.description.Effect_DecreaseMonthlyMoneyIncome50=- {21}每月的金钱收入减少 {0}
TIEffectTemplate.description.Effect_DecreaseMonthlyMoneyIncome100=- {21}每月的金钱收入减少 {0}
TIEffectTemplate.description.Effect_DecreaseMonthlyMoneyIncome200=- {21}每月的金钱收入减少 {0}
TIEffectTemplate.description.Effect_IncreaseMonthlyInfluenceIncome1=- {21}每月的影响力收益增加 {0}
TIEffectTemplate.description.Effect_IncreaseMonthlyInfluenceIncome3=- {21}每月的影响力收益增加 {0}
TIEffectTemplate.description.Effect_IncreaseMonthlyBoostIncome025=- {21}每月的运载力收益增加 {0}
TIEffectTemplate.description.Effect_IncreaseMonthlyOpsIncome5=- {21}每月的行动力收益增加 {0}
TIEffectTemplate.description.Effect_IncreaseMonthlyOpsIncome3=- {21}每月的行动力收益增加 {0}
TIEffectTemplate.description.Effect_IncreaseMonthlyOpsIncome05=- {21}每月的行动力收益增加 {0}
TIEffectTemplate.description.Effect_IncreaseMonthlyResearchIncome15=- {21}每月的研究力收益增加 {0}
TIEffectTemplate.description.Effect_IncreaseMonthlyNoblesIncome10=- {21}每月的贵金属收益增加 {0}
TIEffectTemplate.description.Effect_DecreaseMonthlyNoblesIncome10=- {21}每月的贵金属收益减少 {0}
TIEffectTemplate.displayName.Effect_RapidResponseTeams=快速反应小组
TIEffectTemplate.description.Effect_RapidResponseTeams=- 外星人在对我方控制点进行的恐吓任务中遭受 -{0}
TIEffectTemplate.displayName.Effect_RapidDiplomacy=进步的国际外交
TIEffectTemplate.description.Effect_RapidDiplomacy=- 在我方发起外交事件后，国家间改善关系的冷却时间降低 {4}					// 4:value to percentage decrease
TIEffectTemplate.displayName.Effect_EnthrallElitesDefense=行政保护
TIEffectTemplate.description.Effect_EnthrallElitesDefense=- 外星人在对我方控制点进行的操纵任务中遭受 -{0}
TIEffectTemplate.description.Effect_DestroyNationalSpaceAssets=- {9}失去所有运载力、任务管控力和所有太空防御设施														// 9: 1st nation displayName, 3: value to percentage
TIEffectTemplate.description.Effect_DamageNationalSpaceAssets=- {9}失去 {3} 运载力、任务管控力和太空防御设施
TIEffectTemplate.description.Effect_DamageNationalSpaceAssetsSecondary025=- {11}失去 {3} 运载力、任务管控力和太空防御设施										// 11: 2nd nation displayName
TIEffectTemplate.description.Effect_GlobalFamine=- 地球国家遭受巨大的人口损失，情况依财富状况稍有减缓
TIEffectTemplate.description.Effect_WetBulb=- {1}地区遭受显著的人口损失，情况依财富状况稍微减缓													//  1: 1st target displayName
TIEffectTemplate.description.Effect_MitigatedWetBulb=- {1}地区遭受些许人口损失，情况依财富状况稍微减缓
TIEffectTemplate.displayName.Effect_Apparatchiks=党政官僚
TIEffectTemplate.description.Effect_Apparatchiks=- 肃清任务获得 +{0}
TIEffectTemplate.displayName.Effect_IncreasePurgeAttack_10=主仆互换
TIEffectTemplate.description.Effect_IncreasePurgeAttack_10=- 肃清任务获得 +{0}
TIEffectTemplate.description.Effect_GainFactionSpaceOrg=- 获得一个提升运载力和任务管控力收益的特殊组织
TIEffectTemplate.description.Effect_FreeAbductions1=- 外星人在{5}进行 {0} 起绑架事件																					// 5: nation name with preposition ("in France")
TIEffectTemplate.description.Effect_FreeAbductions2=- 外星人在{5}进行 {0} 起绑架事件																					
TIEffectTemplate.description.Effect_FreeAbductions4=- 外星人在{5}进行 {0} 起绑架事件																					
TIEffectTemplate.description.Effect_FreeAbductions6=- 外星人在{5}进行 {0} 起绑架事件																					
TIEffectTemplate.description.Effect_AtrocityMitigation50=- 减少实施暴行时产生的负面宣传影响
TIEffectTemplate.displayName.Effect_HostileTakeoverDefense=机构防御
TIEffectTemplate.description.Effect_HostileTakeoverDefense=- 敌方在对我方进行的恶意收购任务中遭受 -{0}
TIEffectTemplate.displayName.Effect_HostileTakeoverAttack=恶意收购计划
TIEffectTemplate.description.Effect_HostileTakeoverAttack=- 恶意收购任务获得 +{0}
TIEffectTemplate.displayName.Effect_FactionResearchEncryption=研究加密
TIEffectTemplate.description.Effect_FactionResearchEncryption=- 敌人在偷窃与破坏计划任务中遭受 -{0}
TIEffectTemplate.displayName.Effect_AssassinationAttack=暗杀科技
TIEffectTemplate.description.Effect_AssassinationAttack=- 暗杀任务获得 +{0}
TIEffectTemplate.displayName.Effect_ControlAssetDefense=乘员忠诚
TIEffectTemplate.description.Effect_ControlAssetDefense=- 敌人在控制太空资产任务中遭受 -{0}
TIEffectTemplate.displayName.Effect_GainControlPoint_Debuff4_12=外星间谍软件
TIEffectTemplate.description.Effect_GainControlPoint_Debuff4_12=- 获取控制点或太空殖民地控制权的任务遭受 {0}，持续 {7} 个月						// 7: duration in months
TIEffectTemplate.displayName.Effect_ControlAssetDefense_Debuff6_12=外星间谍软件
TIEffectTemplate.description.Effect_ControlAssetDefense_Debuff6_12=- 在对我方进行的控制太空资产任务中遭受 {0}，持续 {7} 个月
TIEffectTemplate.displayName.Effect_AssassinationAttack_Debuff6_12=外星间谍软件
TIEffectTemplate.description.Effect_AssassinationAttack_Debuff6_12=- 暗杀任务遭受 {0}，持续 {7} 个月
TIEffectTemplate.displayName.Effect_TerrorizeDefense_Debuff6_12=外星间谍软件
TIEffectTemplate.description.Effect_TerrorizeDefense_Debuff6_12=- 在对我方控制点进行的恐吓任务中遭受 {0}，持续 {7} 个月
TIEffectTemplate.displayName.Effect_EnthrallElitesDefense_Debuff4_12=外星间谍软件
TIEffectTemplate.description.Effect_EnthrallElitesDefense_Debuff4_12=- 在对我方控制点进行执行的操纵任务中遭受 {0}，持续 {7} 个月
TIEffectTemplate.displayName.Effect_StealSabotageProjectDefense_Debuff6_12=外星间谍软件
TIEffectTemplate.description.Effect_StealSabotageProjectDefense_Debuff6_12=- 在对我方进行的偷窃与破坏计划任务中遭受 {0}，持续 {7} 个月
TIEffectTemplate.displayName.Effect_PublicCampaign_Debuff6_12=过街老鼠
TIEffectTemplate.description.Effect_PublicCampaign_Debuff6_12=- {1}将在公众宣传任务中永久性遭受 {0}
TIEffectTemplate.description.Effect_PrimaryOccupiesSecondary15=- {5}：对{6}地区的占领增加 {3}														// 6: 2nd nation displayName with preposition
TIEffectTemplate.description.Effect_PrimaryOccupiesSecondary25=- {5}：对{6}地区的占领增加 {3}
TIEffectTemplate.description.Effect_SecondaryOccupiesPrimary15=- {6}：对{6}地区的占领增加 {3}
TIEffectTemplate.description.Effect_SecondaryRegimeChangesPrimary=- {2}在{5}进行政权更迭																		// 2: 2nd target displayName
TIEffectTemplate.description.Effect_SecondaryAnnexesPrimary=- {2}吞并{1}
TIEffectTemplate.description.Effect_SnapElection0=- {5}的控制点会根据阵营支持率重新分配
TIEffectTemplate.description.Effect_SnapElection15=- {5}的控制点会根据阵营支持率重新分配，对{14}的加权为 {3}
TIEffectTemplate.description.Effect_PopularityContestLegislature0=- {5}的{13}控制点会根据阵营支持率随机重新分配									// 13: a displayName for a data template
TIEffectTemplate.description.Effect_PopularityContestLegislature25=- {5}的{13}控制点将会根据阵营支持率随机重新分配，对{14}的加权为 {3}	// 14: 1st nation displayName (colored)
TIEffectTemplate.description.Effect_CoupNullFaction=- {5}会发生一场政变
TIEffectTemplate.description.Effect_IncreaseProjectUnlockChance=- 我方解锁任何研究计划的几率提高 {0}%
TIEffectTemplate.displayName.Effect_IncreaseUnrestAttack=动乱计划
TIEffectTemplate.description.Effect_IncreaseUnrestAttack=- 动乱任务获得 +{0}
TIEffectTemplate.displayName.Effect_StabilizeAttack=稳定计划
TIEffectTemplate.description.Effect_StabilizeAttack=- 稳定任务获得 +{0}
TIEffectTemplate.description.Effect_PostRegimeChangeUnrestControl=- 在被我方军队征服的国家中，动乱减少 {0}
TIEffectTemplate.description.Effect_PostRegimeLossUnrestIncrease=- 我方国家被征服时，其动乱增加 {0}
TIEffectTemplate.description.Effect_BreakawayChance=- 在我方于拥有独立运动的地区执行动乱任务后，该地区脱离的几率上升 {8}						// 8: a percentage (value - 1 to %)
TIEffectTemplate.displayName.Effect_IncreaseInspireAttack=激励计划
TIEffectTemplate.description.Effect_IncreaseInspireAttack=- 获得激励任务 +{0}
TIEffectTemplate.description.Effect_GlobalFissionTechIncrease=<skip/> 																														// TRANSLATORS: RETAIN TRANSLATION IN COMMENTS IN CASE CASE WE RESTORE IT -Increases the global nuclear fission tech level by {0}, buffering the world against energy crises
TIEffectTemplate.description.Effect_GlobalFusionTechIncrease=<skip/>																														// TRANSLATORS: RETAIN TRANSLATION IN COMMENTS IN CASE WE RESTORE IT -Increases the global nuclear fusion tech level by {0}, buffering the world against energy crises
TIEffectTemplate.description.Effect_DestroyRandomModules1=- {1}的一个随机舱体将被摧毁																					// 1st target displayName
TIEffectTemplate.description.Effect_DestroyRandomModules_Marines1=- {1}的一个容纳海军陆战队的随机舱体将被摧毁
TIEffectTemplate.description.Effect_DestroyRandomModules_Marines2=- {1}的 {0} 个容纳海军陆战队的舱体将被摧毁
TIEffectTemplate.description.Effect_DestroyRandomModules_Power2=- {1}的 {0} 个发电舱体将被摧毁
TIEffectTemplate.description.Effect_DestroyRandomModules_Power3=- {1}的 {0} 个发电舱体将被摧毁
TIEffectTemplate.description.Effect_DestroyRandomNumberOfModules1=- {1}的最多 {0} 个舱体将被摧毁
TIEffectTemplate.description.Effect_DestroyRandomNumberOfModules2=- {1}的最多 {0} 个舱体将被摧毁
TIEffectTemplate.description.Effect_DestroyRandomNumberOfModules3=- {1}的最多 {0} 个舱体将被摧毁
TIEffectTemplate.description.Effect_DestroyRandomNumberOfModules4=- {1}的最多 {0} 个舱体将被摧毁
TIEffectTemplate.description.Effect_DestroyHabSector=- {1}的一个随机区域将被摧毁
TIEffectTemplate.description.Effect_DestroyHab=- {1} 将被彻底摧毁
TIEffectTemplate.description.Effect_HabDefectsToSecondary=- {1}叛变至{2}
TIEffectTemplate.description.Effect_FreeDailySpaceResources1=- 免费获得一天份的所有基础太空资源收益
TIEffectTemplate.description.Effect_LoseDailySpaceResources1=- 失去一天份的所有基础太空资源收益
TIEffectTemplate.description.Effect_IncreaseMineProduction25=- {1}所有现有的基础太空资源的开采量会增加 {3}												// 3: value to %
TIEffectTemplate.description.Effect_IncreaseMineProduction50=- {1}所有现有的基础太空资源的开采量会增加 {3}
TIEffectTemplate.description.Effect_DecreaseMineProduction25=- {1}的所有基础太空资源开采量会减少 {3}
TIEffectTemplate.description.Effect_DecreaseMineProduction50=- {1}的所有基础太空资源开采量会减少 {3}
TIEffectTemplate.description.Effect_DecreaseMineProduction75=- {1}的所有基础太空资源开采量会减少 {3}
TIEffectTemplate.displayName.Effect_MiningPerformance_LuckyStrike=- 采矿产出纪录
TIEffectTemplate.description.Effect_MiningPerformance_LuckyStrike=- 我方会在自身阵营的采矿产出纪录中记录这个事件
TIEffectTemplate.displayName.Effect_MiningPerformance_DryHole=- 采矿产出纪录
TIEffectTemplate.description.Effect_MiningPerformance_DryHole=- 我们会在我们阵营的采矿产出纪录中记录这个事件
TIEffectTemplate.description.Effect_IncreaseDebrisInOrbit1=- {1}轨道上的太空垃圾增加 {0}
TIEffectTemplate.description.Effect_IncreaseDebrisInOrbit3=- {1}轨道上的太空垃圾增加 {0}
TIEffectTemplate.description.Effect_IncreaseDebrisInOrbit5=- {1}轨道上的太空垃圾增加 {0}
TIEffectTemplate.description.Effect_DecreaseDebrisInOrbit1=- {1}轨道上的太空垃圾减少 {0}
TIEffectTemplate.description.Effect_KesslerSyndrome2=- 所有近地轨道上的太空垃圾将增加 {0}
TIEffectTemplate.description.Effect_KesslerSyndrome5=- 所有近地轨道上的太空垃圾将增加 {0}
TIEffectTemplate.description.Effect_KesslerSyndrome10=- 所有近地轨道上的太空垃圾将增加 {0}
TIEffectTemplate.description.Effect_LEOCleanup1=- 所有近地轨道上的太空垃圾将减少 {0}
TIEffectTemplate.description.Effect_LEOCleanup3=- 所有近地轨道上的太空垃圾将减少 {0}
TIEffectTemplate.description.Effect_LEOCleanup6=- 所有近地轨道上的太空垃圾将减少 {0}
TIEffectTemplate.description.Effect_GlobalSeaLevelRise_5cm=- 全球海平面上升 5 厘米
TIEffectTemplate.description.Effect_GlobalSeaLevelRise_10cm=- 全球海平面上升 10 厘米
TIEffectTemplate.description.Effect_GlobalSeaLevelRise_20cm=- 全球海平面上升 20 厘米
TIEffectTemplate.description.Effect_GlobalSeaLevelRise_50cm=- 全球海平面上升 50 厘米
TIEffectTemplate.description.Effect_GlobalSeaLevelRise_120cm=- 全球海平面上升 120 厘米
TIEffectTemplate.description.Effect_ArmyNuclearHardening25=- 我方军队受到的核武器伤害降低 {4}
TIEffectTemplate.description.Effect_ArmyNuclearHardening50=- 我方军队受到的核武器伤害降低 {4}
TIEffectTemplate.description.Effect_LifeExtension05=- 我方理事的平均寿命延长 6 个月
TIEffectTemplate.description.Effect_LifeExtension10=- 我方理事的平均寿命延长 10 年
TIEffectTemplate.description.Effect_SpawnMegafaunaArmy=- 一只外星巨兽将会在 {10} 产卵																								// 10: 1st region displayName
TIEffectTemplate.description.Effect_SpawnMegafaunaArmyDamaged25=- 一只受伤的外星巨兽将会在 {10} 产卵
TIEffectTemplate.displayName.Effect_MissionControlDisruption10_Global=- 全球任务管控力干扰
TIEffectTemplate.description.Effect_MissionControlDisruption10_Global=- 所有人类阵营的任务管控力收益会减少 {4}，持续 {7} 个月								//  4: value to percentage (decrease), 7: duration in months
TIEffectTemplate.displayName.Effect_MissionControlDisruption25=- 任务管控力干扰
TIEffectTemplate.description.Effect_MissionControlDisruption25=- 我方的任务管控力收益将会减少 {4}，持续 {7} 个月
TIEffectTemplate.displayName.Effect_MissionControlDisruption50=- 任务管控力干扰
TIEffectTemplate.description.Effect_MissionControlDisruption50=- 我方的任务管控力收益将会减少 {4}，持续 {7} 个月
TIEffectTemplate.displayName.Effect_MissionControlDisruption75=- 任务管控力干扰
TIEffectTemplate.description.Effect_MissionControlDisruption75=- 我方的任务管控力收益将会减少 {4}，持续 {7} 个月
TIEffectTemplate.displayName.Effect_LaunchFacilitiesPriorityDisruption25_6=- 运载力优先计划干扰
TIEffectTemplate.description.Effect_LaunchFacilitiesPriorityDisruption25_6=- 我方投入到运载力优先计划的国家投资点将会减少 {4}，持续 {7} 个月
TIEffectTemplate.displayName.Effect_LaunchFacilitiesPriorityDisruption25_12=- 运载力优先计划干扰
TIEffectTemplate.description.Effect_LaunchFacilitiesPriorityDisruption25_12=- 我方投入到运载力优先计划的国家投资点将会减少 {4}，持续 {7} 个月
TIEffectTemplate.description.Effect_PropagandaStrengthMultiplier25=- 我方的公众宣传任务对全国民意的影响增大 {8}
TIEffectTemplate.description.Effect_PropagandaStrengthMultiplier15=- 我方的公众宣传任务对全国民意的影响增大 {8}
TIEffectTemplate.description.Effect_AlienSpaceResourceShareMajor=- 外星人每天会转移大量的太空资源到我方的储备中
TIEffectTemplate.description.Effect_AlienSpaceResourceShareMinor=- 外星人每天会转移太空资源到我方的储备中
TIEffectTemplate.description.Effect_ControlPointMaintenanceBonus160=- 我方的控制点管理能力增加 {19}																// 19: negative value
TIEffectTemplate.description.Effect_ControlPointMaintenanceBonus40=- 我方的控制点管理能力增加 {19}
TIEffectTemplate.description.Effect_ControlPointMaintenanceBonus20=- 我方的控制点管理能力增加 {19}
TIEffectTemplate.description.Effect_ControlPointMaintenanceBonus10=- 我方的控制点管理能力增加 {19}
TIEffectTemplate.description.Effect_ControlPointMaintenanceBonus3=- 我方的控制点管理能力增加 {19}
TIEffectTemplate.description.Effect_StandardLaserDefenses=- 地表防御工事建造完成后将会装备基础激光武器
TIEffectTemplate.description.Effect_ArcLaserDefenses=- 地表防御工事将会装备电弧激光武器
TIEffectTemplate.description.Effect_PhaserDefenses=- 地表防御工事将会装备相位激光炮
TIEffectTemplate.description.Effect_IRLaserDefenses=- 地表防御工事建造完成后，将会装备红外激光
TIEffectTemplate.description.Effect_GreenLaserDefenses=- 地表防御工事会装备可见光激光
TIEffectTemplate.description.Effect_UVLaserDefenses=- 基地防御舱体将会装备紫外线激光
TIEffectTemplate.description.Effect_GainXP4=- {1}获得 {0} 经验值
TIEffectTemplate.description.Effect_GainXP10=- {1}获得 {0} 经验值
TIEffectTemplate.description.Effect_GainXP20=- {1}获得 {0} 经验值
TIEffectTemplate.description.Effect_GainXP60=- {1}获得 {0} 经验值
TIEffectTemplate.description.Effect_GainXPSecondary20=- {2}获得 {0} 经验值
TIEffectTemplate.description.Effect_GainXPSecondary60=- {2}获得 {0} 经验值
TIEffectTemplate.description.Effect_GainTraitIndebted=- {1}获得{13}特质
TIEffectTemplate.description.Effect_GainTraitDelinquent=- {1}获得{13}特质
TIEffectTemplate.description.Effect_GainTraitInflexible=- {1}获得{13}特质
TIEffectTemplate.description.Effect_GainTraitAddict=- {1}获得{13}特质
TIEffectTemplate.description.Effect_GainTraitIndulgent=- {1}获得{13}特质
TIEffectTemplate.description.Effect_CouncilorDetained6=- {1}将会被拘留在当前地点，持续 {0} 个任务阶段
TIEffectTemplate.displayName.Effect_SabotageFacilitiesDefense2=太空港安全
TIEffectTemplate.description.Effect_SabotageFacilitiesDefense2=- 在我方控制的国家中，敌人的破坏设施任务会遭受 -{0}
TIEffectTemplate.displayName.Effect_SabotageFacilitiesOrHabModulesDefense1=违禁品扫描仪
TIEffectTemplate.description.Effect_SabotageFacilitiesOrHabModulesDefense1=- 敌方在对我方资产进行的破坏设施及破坏太空殖民地舱体任务中遭受 -{0}
TIEffectTemplate.description.Effect_ArmyHealingRate005=- 我方军队的维修率每天增加 {3}
TIEffectTemplate.description.Effect_ArmyUrbanWarfare125=- 在核心经济区内作战时，我方军队的战力值提高
TIEffectTemplate.description.Effect_ArmyRuggedWarfare125=- 在崎岖地区作战时，我方军队的战力值提高
TIEffectTemplate.description.Effect_BonusDamageToXenoforming=- 我方理事和军队对异种生物造成 {8} 额外伤害
TIEffectTemplate.description.Effect_ArmyDamageBonustoMegafauna=- 我方军队对巨兽造成 {8} 额外伤害
TIEffectTemplate.description.Effect_ArmyDamageBonustoInvaderArmy=- 我方军队对外星人军队造成 {8} 额外伤害
TIEffectTemplate.description.Effect_ArmyDamageBonustoHumanArmy=- 我方军队对人类军队造成 {8} 额外伤害
TIEffectTemplate.description.Effect_ArmyDamageBonustoAllArmies=- 我方军队造成 {8} 额外伤害
TIEffectTemplate.description.Effect_MegafaunaDamageMitigation=- 巨兽对我方地区造成的伤害减少 {3}
TIEffectTemplate.description.Effect_MegafaunaDamageElimination=- 巨兽不会再对我方地区造成伤害
TIEffectTemplate.description.Effect_MegafaunaRepellent=- 巨兽会尽可能避开我方国家辖区
TIEffectTemplate.displayName.Effect_CrackdownBonus3=镇压计划
TIEffectTemplate.description.Effect_CrackdownBonus3=- 镇压任务获得 +{0}
TIEffectTemplate.displayName.Effect_CoupBonus3=政变计划
TIEffectTemplate.description.Effect_CoupBonus3=- 政变任务获得 +{0}
TIEffectTemplate.displayName.Effect_CrackdownDefense3=反镇压计划
TIEffectTemplate.description.Effect_CrackdownDefense3=- 敌方在对我方控制点进行的镇压任务中遭受 -{0}
TIEffectTemplate.description.Effect_TotalHabMissionControlCost=- 我方太空殖民地的总<color=#FFFFFFFF><sprite name="mission_control"></color>花费减少 {4}
TIEffectTemplate.description.Effect_TotalShipMissionControlCost=- 我方舰船的总<color=#FFFFFFFF><sprite name="mission_control"></color>花费减少 {4}
TIEffectTemplate.description.Effect_ImprovedSpaceCombatDamageControl5=- 我方损伤控制小组的维修速度加快 {8}
TIEffectTemplate.description.Effect_ImprovedSpaceCombatDamageControl25=- 我方损伤控制小组的维修速度加快 {8}
TIEffectTemplate.description.Effect_ImprovedSpaceCombatDamageControl=- 我方损伤控制小组的维修速度加快 {8}
TIEffectTemplate.description.Effect_ShipLaserDamage=- 我方舰载激光武器造成 {8} 额外伤害
TIEffectTemplate.description.Effect_ShipMagDamage=- 我方舰载磁能武器造成 {8} 额外伤害
TIEffectTemplate.description.Effect_ShipConvMissileDamage=- 我方舰载导弹造成 {8} 额外伤害
TIEffectTemplate.description.Effect_MiningWaterBonus=- 我方矿场产出的<color=#FFFFFFFF><sprite name="water"></color>增加 {8}
TIEffectTemplate.description.Effect_MiningVolatilesBonus=- 我方矿场产出的<color=#FFFFFFFF><sprite name="volatiles"></color>增加 {8}
TIEffectTemplate.description.Effect_MiningMetalsBonus=- 我方矿场产出的<color=#FFFFFFFF><sprite name="metal"></color>增加 {8}
TIEffectTemplate.description.Effect_MiningNoblesBonus=- 我方矿场产出的<color=#FFFFFFFF><sprite name="metal_noble"></color>增加 {8}
TIEffectTemplate.description.Effect_MiningFissilesBonus=- 我方矿场产出的<color=#FFFFFFFF><sprite name="radioactive"></color>增加 {8}
TIEffectTemplate.description.Effect_EconomyInequalityReduction=- 经济优先计划产生的不平等降低 {4}
TIEffectTemplate.description.Effect_WelfareInequalityReductionEffectiveness=- 福利优先计划降低的不平等提高 {8}
TIEffectTemplate.description.Effect_Economy_CO2_ppm90=- 经济优先计划在全球范围产生的二氧化碳减少 {4}
TIEffectTemplate.description.Effect_Economy_CO2_ppm50=- 经济优先计划在全球范围产生的二氧化碳减少 {4}
TIEffectTemplate.description.Effect_WelfareReduction_CO2_ppm=- 福利优先计划从大气层移除的二氧化碳增加 {8}
TIEffectTemplate.description.Effect_Economy_CH4_ppm=- 经济优先计划在全球范围内产生的甲烷减少 {4}
TIEffectTemplate.description.Effect_WelfareReduction_CH4_ppm=- 福利优先计划从大气层移除的甲烷增加 {8}
TIEffectTemplate.description.Effect_Economy_N2O_ppm=- 经济优先计划在全球范围内产生的一氧化二氮减少 {4}
TIEffectTemplate.description.Effect_WelfareReduction_N2O_ppm=- 福利优先计划移除的一氧化二氮增加 {8}
TIEffectTemplate.description.Effect_NuclearStrikeDamageReduction80=- 核打击造成的人口损失和 GDP 损失减少 {4}
TIEffectTemplate.description.Effect_RecruitStartingXP=- 新招募的理事自带 +{0} 经验值
TIEffectTemplate.description.Effect_Economy_BasePCGDPIncrease02=- 经济优先计划使国家人均 GDP 额外增长 {8}
TIEffectTemplate.description.Effect_Economy_BasePCGDPIncreasePenalty02=- 经济优先计划对国家人均 GDP 的效果降低 {4}
TIEffectTemplate.description.Effect_Economy_BasePCGDPIncreaseDisruption08_12=- 经济优先计划对国家人均 GDP 的效果降低 {4}，持续 {7} 个月
TIEffectTemplate.description.Effect_NuclearWeaponsProgramPenalty50=- 所有国家对核武器的投资点变动了 {3}
TIEffectTemplate.description.Effect_MilitaryPriorityPenalty10=- 所有国家对军事优先计划的投资点变动了 {3}
TIEffectTemplate.description.Effect_BuildArmyPriorityPenalty10=- 所有国家对建立军队优先计划的投资点变动了 {3}
TIEffectTemplate.description.Effect_UpgradeArmyPriorityPenalty10=- 所有国家对建立海军优先计划的投资点变动了 {3}
TIEffectTemplate.description.Effect_ArmyBombardmentDefenses=- 军队在轨道轰炸中受到的伤害减少 {4}
TIEffectTemplate.description.Effect_HabBombardmentDefenses=- 太空殖民地在轨道轰炸中受到的伤害减少 {4}
TIEffectTemplate.description.Effect_TerrorKnowledge=- 敌方在对我方控制点进行的恐吓任务中受到 -{0} 惩罚
TIEffectTemplate.displayName.Effect_AssaultAlienAssetKnowledge=外星人审讯
TIEffectTemplate.description.Effect_AssaultAlienAssetKnowledge=- 我方的突袭外星资产任务获得 +{0} 的加成
TIEffectTemplate.displayName.Effect_CounterXenoforming=反异变计划
TIEffectTemplate.description.Effect_CounterXenoforming=- 外星人试图在我方地区安插异种时，会受到 -{0}惩罚。
TIEffectTemplate.description.Effect_FocusedDefenses=- 我方舰船受到的外星武器伤害减少 {4}
TIEffectTemplate.description.Effect_SurvivabilityUpgrades=- 我方舰船在战斗中受到的敌人武器伤害减少 {4}
TIEffectTemplate.displayName.Effect_SeizeSpaceAssetAttack_Griffin=狮鹫研究
TIEffectTemplate.description.Effect_SeizeSpaceAssetAttack_Griffin=- 突袭敌方太空资产任务获得 +{0}
TIEffectTemplate.displayName.Effect_SeizeSpaceAssetDefense_Griffin=狮鹫研究
TIEffectTemplate.description.Effect_SeizeSpaceAssetDefense_Griffin=- 敌方在对我方进行的突袭敌方太空资产任务中受到 -{0}
TIEffectTemplate.description.Effect_DamageArmy10=- {1}的当前强度受到 {3} 伤害
TIEffectTemplate.description.Effect_DamageArmy15=- {1}的当前强度受到 {3} 伤害
TIEffectTemplate.description.Effect_DamageArmy20=- {1}的当前强度受到 {3} 伤害
TIEffectTemplate.description.Effect_DamageArmy30=- {1}的当前强度受到 {3} 伤害
TIEffectTemplate.description.Effect_DamageArmy40=- {1}的当前强度受到 {3} 伤害
TIEffectTemplate.description.Effect_RepairArmy20=- {1}的当前强度修复 {25} 伤害								// 25- Make value absolute and change to percentage
TIEffectTemplate.description.Effect_RepairArmy40=- {1}的当前强度修复 {25} 伤害
TIEffectTemplate.description.Effect_DamageAllRegionArmies10=- 受影响地区内的所有军队遭受轻微伤害
TIEffectTemplate.description.Effect_DummyTooltipImprovedMaintenanceProcedures1=- 太空殖民地意外事件影响我方的几率降低
TIEffectTemplate.description.Effect_DummyTooltipImprovedMaintenanceProcedures2=- 连锁故障在事件中出现的几率降低
TIEffectTemplate.description.Effect_DummyTooltipDevolvedSpaceCommand1=- 太空殖民地叛变事件影响我方的几率降低
TIEffectTemplate.description.Effect_DummyTooltipDevolvedSpaceCommand2=- 我方能更好地抵抗任务管控力受到的干扰
TIEffectTemplate.description.Effect_DummyTooltipInSituResourceUtilization1=- 矿井枯竭事件在我方的矿场的出现几率降低
TIEffectTemplate.description.Effect_DummyTooltipInSituResourceUtilization2=- 幸运来敲门事件在我方的矿场的出现几率升高
TIEffectTemplate.description.Effect_MegafaunaMastery=- 我方军队在战斗中遇上外星巨兽时，我方有概率取得对其的控制
TIEffectTemplate.description.Effect_SpoilsBonus20=- 我方在牟利优先计划中获得的金钱增加 {8}
TIEffectTemplate.description.Effect_CorruptionReduction20=- 精英在我方控制的国家中对牟利优先计划的投资需求降低，进而降低政变几率
TIEffectTemplate.description.Effect_EndofOil=- 消除所有核心石油资源区
TIEffectTemplate.description.Effect_ShipDefectsToSecondary=- {1}叛变至{2}
TIEffectTemplate.description.Effect_DestroyShip=- {1}将被彻底摧毁
TIEffectTemplate.description.Effect_CouncilorGoesToGround=- 其他阵营将会丢失{1}的动向
TIEffectTemplate.description.Effect_LoyaltyGain1=- {1}的{20}属性值将变动 {0}
TIEffectTemplate.description.Effect_LoyaltyGainSecondary1=- {2}的{20}属性值将变动 {0}
TIEffectTemplate.description.Effect_LoyaltyGain3=- {1}的{20}属性值将变动 {0}
TIEffectTemplate.description.Effect_LoyaltyGainSecondary3=- {2}的{20}属性值将变动 {0}
TIEffectTemplate.description.Effect_LoyaltyLoss3=- {1}的{20}属性值将变动 {0}
TIEffectTemplate.description.Effect_LoyaltyLossSecondary3=- {2}的{20}属性值将变动 {0}
TIEffectTemplate.description.Effect_LoyaltyLoss4=- {1}的{20}属性值将变动 {0}
TIEffectTemplate.description.Effect_LoyaltyLossSecondary4=- {2}的{20}属性值将变动 {0}
TIEffectTemplate.description.Effect_LoyaltyLoss6=- {1}的{20}属性值将变动 {0}
TIEffectTemplate.description.Effect_LoyaltyLossSecondary6=- {2}的{20}属性值将变动 {0}
TIEffectTemplate.description.Effect_ApparentLoyaltyGain1=- {1}的{20}属性值将变动 {0}
TIEffectTemplate.description.Effect_ApparentLoyaltyGainSecondary1=- {2}的{20}属性值将变动 {0}
TIEffectTemplate.description.Effect_ApparentLoyaltyGain3=- {1}的{20}属性值将变动 {0}
TIEffectTemplate.description.Effect_ApparentLoyaltyGainSecondary3=- {2}的{20}属性值将变动 {0}
TIEffectTemplate.description.Effect_ApparentLoyaltyLoss3=- {1}的{20}属性值将变动 {0}
TIEffectTemplate.description.Effect_ApparentLoyaltyLossSecondary3=- {2}的{20}属性值将变动 {0}
TIEffectTemplate.description.Effect_ApparentLoyaltyLoss4=- {1}的{20}属性值将变动 {0}
TIEffectTemplate.description.Effect_ApparentLoyaltyLossSecondary4=- {2}的{20}属性值将变动 {0}
TIEffectTemplate.description.Effect_ApparentLoyaltyLoss6=- {1}的{20}属性值将变动 {0}
TIEffectTemplate.description.Effect_ApparentLoyaltyLossSecondary6=- {2}的{20}属性值将变动 {0}
TIEffectTemplate.description.Effect_CouncilorSelfDetained4=- {1}将会被拘留在当前地点，持续 {0} 个任务阶段
TIEffectTemplate.description.Effect_CouncilorSelfDetainedSecondary6=- {2}将会被拘留在当前地点，持续 {0} 个任务阶段
TIEffectTemplate.description.Effect_DamageShipParts_Marines05=- {1}上由海军陆战队驻扎的设施舱体会受到 {3} 伤害
TIEffectTemplate.description.Effect_AlienECM=- 我方舰船的电子反制措施舱体将能有效抵抗外星武器
TIEffectTemplate.description.Effect_GlobalEnergyCrisis1=- 我方控制的所有国家都将遭受 {3} 的GDP 下滑和不平等加剧，受该国石油资源区和全球核裂变及核聚变科技等级影响。
TIEffectTemplate.description.Effect_GlobalEnergyCrisis075=- 我方控制的所有国家都将遭受 {3} 的GDP 下滑和不平等加剧，受该国石油资源区和全球核裂变及核聚变科技等级影响。
TIEffectTemplate.description.Effect_GlobalEnergyCrisis066=- 我方控制的所有国家都将遭受 {3} 的GDP 下滑和不平等加剧，受该国石油资源区和全球核裂变及核聚变科技等级影响。
TIEffectTemplate.description.Effect_GlobalEnergyCrisis05=- 我方控制的所有国家都将遭受 {3} 的GDP 下滑和不平等加剧，受该国石油资源区和全球核裂变及核聚变科技等级影响。
TIEffectTemplate.description.Effect_GlobalEnergyCrisis025=- 我方控制的所有国家都将遭受 {3} 的GDP 下滑和不平等加剧，受该国石油资源区和全球核裂变及核聚变科技等级影响。
TIEffectTemplate.description.Effect_InterrogationTechniques25=- 我方通过审问其他阵营被拘留的囚犯能获得 {8} 的额外情报
TIEffectTemplate.description.Effect_InterrogationTechniques100=- 我方通过审问其他阵营被拘留的囚犯能获得 {8} 的额外情报
TIEffectTemplate.description.Effect_AddTraitGroup5=- {1}将获得以下性格特质之一：{16}
TIEffectTemplate.description.Effect_RemoveTraitGroup5=- {1}将失去他们的{17}特质
TIEffectTemplate.description.Effect_AddTraitGroup9=- {1}将获得以下安全特质之一：{16} 
TIEffectTemplate.displayName.Effect_BuddyMovieFlag=系列电影
TIEffectTemplate.description.Effect_BuddyMovieFlag=- {1}和{2}合作抓捕一个臭名昭著的黑帮头目
TIEffectTemplate.description.Effect_PropagandaCouncilorHome25=- 我方在{1}祖国的民意将会大幅改善
TIEffectTemplate.description.Effect_NegativePropagandaCouncilorHome10=- 我方在{1}祖国的民意将会显著恶化
TIEffectTemplate.description.Effect_NegativePropagandaCouncilorHome25=- 我方在{1}祖国的民意将会大幅恶化
TIEffectTemplate.description.Effect_PropagandaCouncilorHomeSecondary25=- 我方在{2}祖国的民意将会大幅改善
TIEffectTemplate.description.Effect_NegativePropagandaCouncilorHomeSecondary10=- 我方在{2}祖国的民意将会显著恶化
TIEffectTemplate.description.Effect_NegativePropagandaCouncilorHomeSecondary25=- 我方在{2}祖国的民意将会大幅恶化
TIEffectTemplate.description.Effect_GlobalCrackdown50_Secondary=- 约半数属于{2}的控制点将遭受镇压，持续 12 个月
TIEffectTemplate.description.Effect_CouncilorHomeNationsImproveRelations=- {1}和{2}的祖国的关系将会改善
TIEffectTemplate.description.Effect_KillCouncilor=- {1}将会死亡，除非受到另一名理事的保护
TIEffectTemplate.description.Effect_KillCouncilorSecondary=- {2}将会死亡，除非受到另一名理事的保护
TIEffectTemplate.description.Effect_LoseRandomNumberOfOrgs3=- {1}将会失去最多 {0} 个非专属组织
TIEffectTemplate.description.Effect_LoseTraitGovernment=- {1}会失去{13}特质
TIEffectTemplate.description.Effect_GainTraitEnemyOfTheState=- {1}获得{13}特质
TIEffectTemplate.description.Effect_GainTraitExtorted=- {1}获得{13}特质
TIEffectTemplate.description.Effect_RegionGDPGainSpain=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_RegionGDPGainRabat=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_RegionGDPGainAden=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_RegionGDPGainDjibouti=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_RegionGDPGainJava=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_RegionGDPGainSumatra=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_RegionGDPGainHijaz=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_RegionGDPGainCairo=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_RegionGDPGainEgypt=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_RegionGDPGainAfghanistan=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_RegionGDPGainXinjiang=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_RegionGDPGainPanama=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_RegionGDPGainColombia=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_RegionGDPGainTibet=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_RegionGDPGainUpperMyanmar=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_RegionGDPGainAlaska=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_RegionGDPGainKamchatka=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_RegionGDPGainMalayPeninsula=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_RegionGDPGainSriLanka=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_RegionGDPGainChennai=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_RegionGDPGainScotland=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_RegionGDPGainNorthernIreland=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_RegionGDPGainRussianFarEast=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_RegionGDPGainSakhalinKurils=- {13}的 GDP 获得 {3} 的一次性增长
TIEffectTemplate.description.Effect_MCUsageMasking=- 我方预计可以在不招致外星人报复的情况下，将我方舰队和太空殖民地规模扩大 {18}（根据我方的任务管控力使用量计算得出）
TIEffectTemplate.description.Effect_FreeXenoInvestigations10=- 我方将获得相当于 {0} 次外星人调查的结果
TIEffectTemplate.description.Effect_TriggerEventHabRevolt=- 为{15}触发{13}事件
TIEffectTemplate.displayName.Effect_EnthrallPublicDefense=操纵公众防御
TIEffectTemplate.description.Effect_EnthrallPublicDefense=- 外星人在我方有行政控制的国家进行的操纵公众任务中遭受 -{0}
TIEffectTemplate.displayName.Effect_AbductionsDefense=绑架防御
TIEffectTemplate.description.Effect_AbductionsDefense=- 在我方有行政控制的国家，外星人的绑架任务遭受 -{0}
TIEffectTemplate.description.Effect_UpdateAlienThreatMeter=- 我方更新外星人对我方阵营看法的情报评估
TIEffectTemplate.description.Effect_FixAlienThreatMeter=- 我方利用准确信息更新外星人对我方阵营看法的情报评估
TIEffectTemplate.displayName.Effect_HackProject_Steal=骇客计划
TIEffectTemplate.description.Effect_HackProject_Steal=- 在偷窃计划任务中获得 {0}
TIEffectTemplate.displayName.Effect_HackProject_Sabotage=骇客计划
TIEffectTemplate.description.Effect_HackProject_Sabotage=- 在破坏计划任务中获得 {0}
TIEffectTemplate.displayName.Effect_InspireBonus=激励计划
TIEffectTemplate.description.Effect_InspireBonus=- 在激励任务中获得 {0}
TIEffectTemplate.description.Effect_TurnBonus=- 在拉拢理事任务中获得 {0}
TIEffectTemplate.description.Effect_LoseTraitDeclining=- {1}会失去{13}特质
TIEffectTemplate.displayName.Effect_EaseAbductions=绑架定位晶片
TIEffectTemplate.description.Effect_EaseAbductions=- 全球范围的绑架任务 +{0} 成功率
TIEffectTemplate.description.Effect_SpaceResearchBoost05=所有太空殖民地生产 +{8} 研究力产出
TIEffectTemplate.description.Effect_SpaceResearchBoost1=- 所有太空殖民地生产 +{8} 研究力产出
TIEffectTemplate.description.Effect_SetAlienHate0=- 外星人对我方的态度已设为容忍
TIEffectTemplate.description.Effect_BlockAlienContact=- 阻止联系外星人理事
TIEffectTemplate.description.Effect_GainTraitLoyaltyMonitor=- {1}获得{13}特质
TIEffectTemplate.description.Effect_HabNuclearFreighters=<skip/>
TIEffectTemplate.displayName.Effect_VaccineTrackers=疫苗定位晶片
TIEffectTemplate.description.Effect_VaccineTrackers=- 疫苗定位晶片运行中
TIEffectTemplate.description.Effect_LoseTraitBillionaire=- {1}会失去{13}特质
TIEffectTemplate.description.Effect_GainTraitBeloved=- {1}获得{13}特质
TIEffectTemplate.description.Effect_GainTraitProsperous=- {1}获得{13}特质
TIEffectTemplate.displayName.Effect_SecondaryTargetFreePriorityWelfare200=福利投资
TIEffectTemplate.description.Effect_SecondaryTargetFreePriorityWelfare200=- {11}将会极大增加对社会福利及环保计划的投资
TIEffectTemplate.displayName.Effect_FakedDeath=假死
TIEffectTemplate.description.Effect_FakedDeath={1}近期试图伪造自己的死亡
TIEffectTemplate.displayName.Effect_LiedAboutInfluence=在影响力的事情上说谎
TIEffectTemplate.description.Effect_LiedAboutInfluence=- {21}就其的影响力对大众进行了误导
TIEffectTemplate.description.Effect_NegativeGlobalPropaganda5=- {21}在全世界的民意小幅恶化
TIEffectTemplate.description.Effect_RegionMinorGDPGain=- {1}地区的经济极小幅上涨
TIEffectTemplate.description.Effect_RegionGDPGain=- {1}地区的经济小幅上涨
TIEffectTemplate.description.Effect_MarkedChain=- “众矢之的”事件链开始了
TIEffectTemplate.description.Effect_MarkedCombatChain=- “众矢之的：战斗”事件链开始了
TIEffectTemplate.description.Effect_InfiltratedChain=- “遭到渗透”事件链开始了
TIEffectTemplate.description.Effect_LoseTraitMarked=- {1}会失去{13}特质
TIEffectTemplate.description.Effect_KillCouncilorNoSave=- {1}死亡
TIEffectTemplate.description.Effect_RetireCouncilor=- {1}退休，即刻生效 
TIEffectTemplate.description.Effect_InfiltratedCombatChain=- “遭到渗透：行动”事件链开始了
TIEffectTemplate.description.Effect_InfiltratedMoneyChain=- “遭到渗透：金钱”事件链开始了
TIEffectTemplate.description.Effect_InfiltratedInfluenceChain=- “遭到渗透：影响力”事件链开始了
TIEffectTemplate.description.Effect_IncreaseInfiltratedCount=- 信息泄露再次阻碍了我方的行动
TIEffectTemplate.description.Effect_EndInfiltratedChain=- 信息泄露似乎已得到补救
TIEffectTemplate.description.Effect_GainTraitMarked=- {1}获得{13}特质
TIEffectTemplate.description.Effect_GainTraitAce=- {1}获得{13}特质
TIEffectTemplate.description.Effect_RemoveLiedAboutInfluence=- 我方不再被自己的谎言所困扰
TIEffectTemplate.description.Effect_IncreaseMonthlyProjectTriggerChance01=- 所有已解锁计划转化为可研究状态的几率每月 +{3}
TIEffectTemplate.description.Effect_TargetingComputer1=- 我方太空殖民地舱体和地表防御工事在克服舰船电子反制措施方面获得 {3} 加成
TIEffectTemplate.description.Effect_TargetingComputer2=- 我方太空殖民地舱体和地表防御工事在克服舰船电子反制措施方面获得 {3} 加成
TIEffectTemplate.description.Effect_TargetingComputer3=- 我方太空殖民地舱体和地表防御工事在克服舰船电子反制措施方面获得 {3} 加成
TIEffectTemplate.description.Effect_FighterECM1=<skip/>
TIEffectTemplate.description.Effect_FighterECM2=<skip/>
TIEffectTemplate.description.Effect_FighterECM3=<skip/>
TIEffectTemplate.description.Effect_EnvironmentBestSustainabilityValue05=各国可实现的最佳可持续性价值已提升。
TIEffectTemplate.description.Effect_EnvironmentBestSustainabilityValue10=各国可实现的最佳可持续性价值已显著提升。
TIEffectTemplate.description.Effect_SpaceMineFreebies1=- 我方可无需支付任务管控力成本支持的太空殖民地采矿舱体数量增加 {0}。
TIEffectTemplate.description.Effect_SpaceMineFreebies3=- 我方可无需支付任务管控力成本支持的太空殖民地采矿舱体数量增加 {0}。
TIEffectTemplate.description.Effect_SpaceMineFreebies4=- 我方可无需支付任务管控力成本支持的太空殖民地采矿舱体数量增加 {0}。
TIEffectTemplate.description.Effect_SpaceMineFreebies6=- 我方可无需支付任务管控力成本支持的太空殖民地采矿舱体数量增加 {0}。
TIEffectTemplate.description.Effect_OfficerSpawnChance02=- 军官从触发事件中重生或晋升的几率增加 {3}
TIEffectTemplate.description.Effect_OfficerSpawnChance03=- 军官从触发事件中重生或晋升的几率增加 {3}
TIEffectTemplate.description.Effect_OfficerSpawnChance05=- 军官从触发事件中重生或晋升的几率增加 {3}