TIMissileTemplate.displayName.KraitMissileBay=环蛇导弹舱
TIMissileTemplate.description.KraitMissileBay=海军固体燃料反舰巡航导弹的太空用改型。
TIMissileTemplate.displayName.AnacondaMissileBay=森蚺导弹舱
TIMissileTemplate.description.AnacondaMissileBay=采用自燃火箭燃料的小型反舰导弹，搭载爆炸弹头。
TIMissileTemplate.displayName.CobraMissileBay=眼镜蛇导弹舱
TIMissileTemplate.description.CobraMissileBay=大型反舰导弹，使用自发点火式火箭燃料推进爆炸弹头。
TIMissileTemplate.displayName.CopperheadMissileBay=铜头蝮导弹舱
TIMissileTemplate.description.CopperheadMissileBay=增程巡弋导弹，搭载使用液氢液氧燃料的爆炸弹头。
TIMissileTemplate.displayName.HarlequinMissileBay=花斑眼镜蛇导弹舱
TIMissileTemplate.description.HarlequinMissileBay=采用自燃燃料的导弹，搭载穿甲弹头。
TIMissileTemplate.displayName.KeelbackMissileBay=棱背蛇导弹舱
TIMissileTemplate.description.KeelbackMissileBay=搭载大型弹头的贯穿导弹。
TIMissileTemplate.displayName.LanceheadMissileBay=锐蝮蛇导弹舱
TIMissileTemplate.description.LanceheadMissileBay=使用液氢液氧燃料的远距离穿甲导弹。
TIMissileTemplate.displayName.RacerMissileBay=游蛇飞弹舱
TIMissileTemplate.description.RacerMissileBay=短程速射制导火箭系统。可用于防御反击。
TIMissileTemplate.displayName.RattlerMissileBay=响尾蛇导弹舱
TIMissileTemplate.description.RattlerMissileBay=搭载破片弹头的小型导弹。可用于防御反击。
TIMissileTemplate.displayName.RiverjackMissileBay=犀咝蝰导弹舱
TIMissileTemplate.description.RiverjackMissileBay=搭载破片弹头的大型导弹。可用于防御反击。
TIMissileTemplate.displayName.ViperMissileBay=蝰蛇导弹舱
TIMissileTemplate.description.ViperMissileBay=搭载破片弹头的远距离导弹，使用液氢液氧燃料。可用于防御反击。
TIMissileTemplate.displayName.PythonNuclearMissileBay=蟒蛇核导弹舱
TIMissileTemplate.description.PythonNuclearMissileBay=搭载五万吨当量战术核弹头的敏捷导弹，使用液氢液氧燃料。可用于防御反击。
TIMissileTemplate.displayName.SidewinderNuclearMissileBay=响尾蛇聚能核导弹舱
TIMissileTemplate.description.SidewinderNuclearMissileBay=这种敏捷导弹搭载一颗十万吨当量的聚能装药核弹头，可将爆炸能量集中在一个狭窄的锥形区中。可用于对来袭的导弹进行防御反击。
TIMissileTemplate.displayName.HeraTorpedoBay=赫拉鱼雷舱
TIMissileTemplate.description.HeraTorpedoBay=采用自燃燃料的鱼雷，搭载爆炸弹头。
TIMissileTemplate.displayName.ArtemisTorpedoBay=阿提米丝鱼雷舱
TIMissileTemplate.description.ArtemisTorpedoBay=搭载爆炸弹头的改良鱼雷。
TIMissileTemplate.displayName.AthenaTorpedoBay=雅典娜鱼雷舱
TIMissileTemplate.description.AthenaTorpedoBay=搭载爆炸弹头的核鱼雷。
TIMissileTemplate.displayName.HermesTorpedoBay=荷米斯鱼雷舱
TIMissileTemplate.description.HermesTorpedoBay=搭载贯穿弹头的鱼雷。
TIMissileTemplate.displayName.VulcanTorpedoBay=兀儿肯鱼雷舱
TIMissileTemplate.description.VulcanTorpedoBay=改良射程并搭载贯穿弹头的液氢液氧鱼雷。
TIMissileTemplate.displayName.AresTorpedoBay=阿瑞斯鱼雷舱
TIMissileTemplate.description.AresTorpedoBay=核热火箭动力鱼雷，搭载穿甲弹头。
TIMissileTemplate.displayName.PoseidonTorpedoBay=波塞冬鱼雷舱
TIMissileTemplate.description.PoseidonTorpedoBay=穿甲鱼雷，在较小型的弹头中装入了尽可能多的 Delta-v。
TIMissileTemplate.displayName.CerebrusNuclearTorpedoBay=地狱三头犬核鱼雷舱
TIMissileTemplate.description.CerebrusNuclearTorpedoBay=采用自燃燃料的鱼雷，搭载 30 万吨热核弹头。
TIMissileTemplate.displayName.HadesNuclearTorpedoBay=黑帝斯核鱼雷舱
TIMissileTemplate.description.HadesNuclearTorpedoBay=采用液氢液氧燃料的鱼雷，搭载 65 万吨热核弹头 。
TIMissileTemplate.displayName.NemesisNuclearTorpedoBay=涅墨西斯核鱼雷舱
TIMissileTemplate.description.NemesisNuclearTorpedoBay=搭载 120 万吨弹头的核热核鱼雷。
TIMissileTemplate.displayName.OlympusNuclearTorpedoBay=奥林匹斯聚能核鱼雷舱
TIMissileTemplate.description.OlympusNuclearTorpedoBay=核动力鱼雷，配备有一百万吨当量的聚能核武器，可将爆炸能量集中在一个狭窄的锥形区中。
TIMissileTemplate.displayName.AcheronNuclearTorpedoBay=阿刻戎聚能核鱼雷舱
TIMissileTemplate.description.AcheronNuclearTorpedoBay=核动力鱼雷，配备有一百万吨当量的聚能核武器，可将爆炸能量集中在一个非常狭窄的锥形区中。
TIMissileTemplate.displayName.TartarusNuclearTorpedoBay=塔耳塔洛斯聚能核鱼雷舱
TIMissileTemplate.description.TartarusNuclearTorpedoBay=核动力鱼雷，配备有一百万吨当量的聚能核武器，可将爆炸能量集中在一个极其狭窄的锥形区中。
TIMissileTemplate.displayName.StyxNuclearTorpedoBay=斯堤克斯聚能核鱼雷舱
TIMissileTemplate.description.StyxNuclearTorpedoBay=核动力鱼雷，配备有一百万吨当量的聚能核武器，可将爆炸能量集中在一个狭窄的圆锥形区域中。
TIMissileTemplate.displayName.AntimatterTorpedoLauncher=反物质鱼雷发射器
TIMissileTemplate.description.AntimatterTorpedoLauncher=搭载装有微量反物质弹头的核热火箭。

TIMissileTemplate.displayName.KraitMissilePod=环蛇导弹发射架
TIMissileTemplate.description.KraitMissilePod=海军固体燃料反舰巡航导弹的太空用改型。
TIMissileTemplate.displayName.AnacondaMissilePod=森蚺导弹发射架
TIMissileTemplate.description.AnacondaMissilePod=采用自燃火箭燃料的小型反舰导弹，搭载爆炸弹头。
TIMissileTemplate.displayName.CobraMissilePod=眼镜蛇导弹发射架
TIMissileTemplate.description.CobraMissilePod=大型反舰导弹，使用自发点火式火箭燃料推进爆炸弹头。
TIMissileTemplate.displayName.CopperheadMissilePod=铜头蝮导弹发射架
TIMissileTemplate.description.CopperheadMissilePod=增程巡弋导弹，搭载使用液氢液氧燃料的爆炸弹头。
TIMissileTemplate.displayName.HarlequinMissilePod=小丑导弹发射架
TIMissileTemplate.description.HarlequinMissilePod=采用自燃燃料的导弹，搭载穿甲弹头。
TIMissileTemplate.displayName.KeelbackMissilePod=游蛇导弹发射架
TIMissileTemplate.description.KeelbackMissilePod=搭载大型弹头的贯穿导弹。
TIMissileTemplate.displayName.LanceheadMissilePod=锐蝮蛇导弹发射架
TIMissileTemplate.description.LanceheadMissilePod=使用液氢液氧燃料的远距离穿甲导弹。
TIMissileTemplate.displayName.RacerMissilePod=游侠导弹发射架
TIMissileTemplate.description.RacerMissilePod=短程速射制导火箭系统。可用于防御反击。
TIMissileTemplate.displayName.RattlerMissilePod=响尾蛇导弹发射架
TIMissileTemplate.description.RattlerMissilePod=搭载破片弹头的小型导弹。可用于防御反击。
TIMissileTemplate.displayName.RiverjackMissilePod=河岸蝰蛇导弹发射架
TIMissileTemplate.description.RiverjackMissilePod=搭载破片弹头的大型导弹。可用于防御反击。
TIMissileTemplate.displayName.ViperMissilePod=蝰蛇导弹发射架
TIMissileTemplate.description.ViperMissilePod=搭载破片弹头的远距离导弹，使用液氢液氧燃料。可用于防御反击。
TIMissileTemplate.displayName.PythonNuclearMissilePod=蟒蛇导弹发射架
TIMissileTemplate.description.PythonNuclearMissilePod=搭载五万吨当量战术核弹头的敏捷导弹，使用液氢液氧燃料。可用于防御反击。
TIMissileTemplate.displayName.HeraTorpedoPod=赫拉鱼雷发射架
TIMissileTemplate.description.HeraTorpedoPod=采用自燃燃料的鱼雷，搭载爆炸弹头。
TIMissileTemplate.displayName.ArtemisTorpedoPod=阿提米丝鱼雷发射架
TIMissileTemplate.description.ArtemisTorpedoPod=搭载爆炸弹头的改良鱼雷。
TIMissileTemplate.displayName.HermesTorpedoPod=荷米斯鱼雷发射架
TIMissileTemplate.description.HermesTorpedoPod=搭载贯穿弹头的鱼雷。
TIMissileTemplate.displayName.VulcanTorpedoPod=兀儿肯鱼雷发射架
TIMissileTemplate.description.VulcanTorpedoPod=改良射程并搭载贯穿弹头的液氢液氧鱼雷。
TIMissileTemplate.displayName.CerebrusNuclearTorpedoPod=地狱三头犬核鱼雷发射架
TIMissileTemplate.description.CerebrusNuclearTorpedoPod=采用自燃燃料的鱼雷，搭载 30 万吨热核弹头。
TIMissileTemplate.displayName.HadesNuclearTorpedoPod=黑帝斯核鱼雷发射架
TIMissileTemplate.description.HadesNuclearTorpedoPod=采用液氢液氧燃料的鱼雷，搭载 65 万吨热核弹头 。

TIMissileTemplate.displayName.GlitteringJewelMissileBay=闪耀宝石导弹舱
TIMissileTemplate.description.GlitteringJewelMissileBay=外星导弹系统。
TIMissileTemplate.displayName.GlitteringJewelMissilePod=闪耀宝石导弹发射架
TIMissileTemplate.description.GlitteringJewelMissilePod=外星导弹系统。
TIMissileTemplate.displayName.IridescentStarTorpedoBay=霓虹星星鱼雷舱
TIMissileTemplate.description.IridescentStarTorpedoBay=外星重型鱼雷系统。
TIMissileTemplate.displayName.LuminousSwarmMissileBay=荧光虫群导弹舱
TIMissileTemplate.description.LuminousSwarmMissileBay=速射外星导弹系统。
TIMissileTemplate.displayName.BrilliantSkyMissileBay=晴空导弹发射舱
TIMissileTemplate.description.BrilliantSkyMissileBay=先进的外星导弹系统。
TIMissileTemplate.displayName.PredatoryStarTorpedoBay=掠食之星鱼雷舱
TIMissileTemplate.description.PredatoryStarTorpedoBay=先进的外星重型鱼雷系统。

TIMissileTemplate.Warhead=弹头类型：<rcol>{0}</rcol>
TIMissileTemplate.Warhead.Explosive=爆炸 (对装甲造成 {0} 伤害)
TIMissileTemplate.Warhead.Penetrator=贯穿 (对装甲造成 {0} 伤害)
TIMissileTemplate.Warhead.Fragmentation=破片 (对装甲造成 {0} 伤害)
TIMissileTemplate.Warhead.Nuclear=核 (对装甲造成所有伤害)
TIMissileTemplate.Warhead.ShapedNuclear=聚能核（对装甲造成全额伤害）
TIMissileTemplate.Warhead.Antimatter=反物质（对装甲造成 {0} 伤害）
TIMissileTemplate.WarheadType.Explosive=高爆
TIMissileTemplate.WarheadType.Penetrator=贯穿
TIMissileTemplate.WarheadType.Fragmentation=破片
TIMissileTemplate.WarheadType.Nuclear=核
TIMissileTemplate.WarheadType.ShapedNuclear=聚能核
TIMissileTemplate.WarheadType.Antimatter=反物质
TIMissileTemplate.Acc=加速度：<rcol>{0} G</rcol>
TIMissileTemplate.DV=Delta-v：<rcol>{0} kps</rcol>
TIMissileTemplate.ShapedNuclearAngle=杀伤锥形区：<rcol>{0} 度</rcol>
TIMissileTemplate.EffectiveAOERange_Sphere=爆炸伤害衰减半径：<rcol>{0} km</rcol>
TIMissileTemplate.EffectiveAOERange_Cone=爆炸锥形范围伤害衰减距离：<rcol>{0} km</rcol>