UI.Codex.Title=游戏法则
UI.Codex.ListContainerHeader=法则条目
UI.Codex.DetailContainerHeader=法则详细信息
UI.Codex.codex_welcome.Title=简介 
UI.Codex.codex_welcome0=此法则呈现了有关《地球不屈》玩法的信息。选择左侧的主题，即可深入了解游戏机制。<br/><br/>若科技解锁了新机制，可能会偶尔出现新主题<br/><br/>若要了解如何操作游戏界面，请启用教学，然后以“抵抗派”的身份开始战役。
UI.Codex.codex_factions.Title=阵营
UI.Codex.codex_factions0=对于如何处理即将登陆地球的外星人，各国无法达成共识。于是，志同道合的人们暗中组成跨国阵营，主导世界的事务。每个阵营对于在地球上处理外星活动有各自的意识形态。为了达成目标，这些阵营会投资与控制地球的政府，而你正是其中某个阵营的领袖。
UI.Codex.codex_factions1=各个阵营内部的领导层称为<h>理事会</h>，理事会成员会执行任务，协助你获得控制地球各国的权力，并找出外星人在地球的目的。阵营也可控制<h>军队</h>，随着故事发展，阵营可在太空建造<h>太空殖民地</h>和<h>舰队</h>。
UI.Codex.codex_factions2=你无法在《地球不屈》完全消灭阵营，因为阵营起源自地球人的理念，你可以影响人们及消除组织架构，但无法根除想法。重要的是，支持那些意识形态的人们拥有多少权力。
UI.Codex.codex_objectives.Title=目标
UI.Codex.codex_objectives0=在战役期间，每个阵营随时会有一个或多个必须完成的目标，完成目标后，即会获得有关外星人的资讯，以及他们在太阳系的真正目的。此外，目标还可让阵营解锁特殊研究计划和组织。
UI.Codex.codex_resources.Title=资源
UI.Codex.codex_resources0=阵营必须在地球上管理多种重要资源，而随着战役的发展，将会换成在太空管理。
UI.Codex.codex_resources1=地球资源可通过各种来源产生，但空间资源（水、挥发物、金属、贵金属和裂变物）只能通过发展科技来开采地球以外的天体，以及向目标区域发射电磁弹射器来取得。
UI.Codex.codex_resources2=为方便阅读，《地球不屈》会不时针对极大或极小的数字，在数字后方以字母替换表示，例如“10K”。大写字母用于大于 1,000 的数字：
UI.Codex.codex_resources3=K：千 (1,000)
UI.Codex.codex_resources4=M：百万（1,000,000）
UI.Codex.codex_resources5=B：十亿（1,000,000,000）
UI.Codex.codex_resources6=T：兆（1,000,000,000,000）
UI.Codex.codex_resources7=Q：千兆（1,000,000,000,000,000）
UI.Codex.codex_resources8=小写字母用于小于 1 的小数：
UI.Codex.codex_resources9=m：毫（.001）
UI.Codex.codex_resources10=u：微（.000 001）
UI.Codex.codex_resources11=n：奈（.000 000 001）
UI.Codex.codex_resources12=p：皮（.000 000 000 001）									// 1e-12
UI.Codex.codex_resources13=f：飞（.000 000 000 000 001）
UI.Codex.codex_resources14=a：阿（.000 000 000 000 000 001）
UI.Codex.codex_resources15=z：介（.000 000 000 000 000 000 001）
UI.Codex.codex_resources16=y：攸（.000 000 000 000 000 000 000 001）
UI.Codex.codex_money.Title=金钱
UI.Codex.codex_money0=<LOC,UI.GeneralControls.MoneyDetail>
UI.Codex.codex_money1=<LOC,UI.GeneralControls.MoneySource>
UI.Codex.codex_influence.Title=影响力
UI.Codex.codex_influence0=<LOC,UI.GeneralControls.InfluenceDetail>
UI.Codex.codex_influence1=<LOC,UI.GeneralControls.InfluenceSource>
UI.Codex.codex_ops.Title=行动力
UI.Codex.codex_ops0=<LOC,UI.GeneralControls.OpsDetail>
UI.Codex.codex_ops1=<LOC,UI.GeneralControls.OpsSource>
UI.Codex.codex_boost.Title=运载力
UI.Codex.codex_boost0=<LOC,UI.GeneralControls.BoostDetail>
UI.Codex.codex_boost1=<LOC,UI.GeneralControls.BoostSource>
UI.Codex.codex_missionControl.Title=任务管控力
UI.Codex.codex_missionControl0=<LOC,UI.GeneralControls.MissionControlDetail>
UI.Codex.codex_missionControl1=任务管控力主要设立于地球陆地上的设施，但部分组织和太空殖民地舱体也可以提供此资源。
UI.Codex.codex_researchIncome.Title=研究
UI.Codex.codex_researchIncome0=<LOC,UI.GeneralControls.ResearchDetail>
UI.Codex.codex_researchIncome1=国家、理事会、组织和太空殖民地舱体可生成研究力，许多理事、组织和太空殖民地舱体会给特定研究<h>类别</h>提供加成。
UI.Codex.codex_researchIncome2=研究收益也会因你的阵营参与的调查数量而获得奖励，因此一心多用可能很有用。但是，如果你在多个项目中同时使用它们，个别类别的收益会有所减少。
UI.Codex.codex_projectsIncome.Title=计划
UI.Codex.codex_projectsIncome0=计划力资源代表阵营建造特定物体或成果的能力。
UI.Codex.codex_projectsIncome1=阵营拥有的数量会决定阵营可同时开发的计划数量及完成速度。阵营可免费获得一个计划栏位，若理事拥有具备计划收益价值的组织，便会获得第二个计划栏位（即可同时开发两个计划）。阵营若建造具备计划收益价值的太空殖民地舱体，可以获得第三个计划栏位。若拥有理事特质、多个具备计划收益价值的组织或太空殖民地舱体，阵营可为所有开发的计划提供加成。
UI.Codex.codex_water.Title=水
UI.Codex.codex_water0=<LOC,UI.GeneralControls.WaterDetail>
UI.Codex.codex_volatiles.Title=挥发性物质
UI.Codex.codex_volatiles0=<LOC,UI.GeneralControls.VolatilesDetail>
UI.Codex.codex_metals.Title=金属
UI.Codex.codex_metals0=<LOC,UI.GeneralControls.BaseMetalsDetail>
UI.Codex.codex_nobleMetals.Title=贵金属
UI.Codex.codex_nobleMetals0=<LOC,UI.GeneralControls.NobleMetalsDetail>
UI.Codex.codex_fissiles.Title=裂变物
UI.Codex.codex_fissiles0=<LOC,UI.GeneralControls.FissilesDetail>
UI.Codex.codex_antimatter.Title=反物质
UI.Codex.codex_antimatter0=<LOC,UI.GeneralControls.AntimatterDetail>
UI.Codex.codex_exotics.Title=异星物质
UI.Codex.codex_exotics0=<LOC,UI.GeneralControls.ExoticsDetail>
UI.Codex.codex_diplomacy.Title=阵营外交
UI.Codex.codex_diplomacy0=若对其他阵营的理事使用<h>联络</h>任务，理事可以与该阵营的领袖展开贸易讨论。贸易成功有助于减少双方阵营间的敌对。
UI.Codex.codex_diplomacy1=然而，所有人类阵营都有着互不相容的意识形态和对立的目标，他们会把所有友好关系视为“充其量只是暂时联手而已”。
UI.Codex.codex_councilors.Title=理事
UI.Codex.codex_councilors0=理事是阵营处理地球事务的主要代理人，但也可能为了发展阵营的太空利益而前往太空。阵营一开始会有四位理事，但通过开发某些计划，可让阵营理事增加至六位。理事的主要职责是为阵营执行<h>任务</h>。
UI.Codex.codex_professions.Title=职业
UI.Codex.codex_professions0=理事的职业会决定其初始属性、可执行的任务及潜在特质等类别。 
UI.Codex.codex_recruiting.Title=招募
UI.Codex.codex_recruiting0=你可通过花费影响力招募理事。为理事会招募不同职业的理事，可让你拥有所有可执行的任务类型。
UI.Codex.codex_recruiting1=由于一些理事候选人会离开，你可招募的理事名单会于每月一号更新。
UI.Codex.codex_attributes.Title=属性
UI.Codex.codex_attributes0=理事具有八种属性，这些属性会决定任务或提供收益加成的成功率。
UI.Codex.codex_attributes1=<color=#FFFFFFFF><sprite name="attribute_persuasion"></color>说服<br/><LOC,UI.Councilor.PersuasionTip>
UI.Codex.codex_attributes2=<color=#FFFFFFFF><sprite name="attribute_investigation"></color>调查<br/><LOC,UI.Councilor.InvestigationTip>
UI.Codex.codex_attributes3=<color=#FFFFFFFF><sprite name="attribute_espionage"></color>间谍<br/><LOC,UI.Councilor.EspionageTip>
UI.Codex.codex_attributes4=<color=#FFFFFFFF><sprite name="attribute_command"></color>指挥<br/><LOC,UI.Councilor.CommandTip>
UI.Codex.codex_attributes5=<color=#FFFFFFFF><sprite name="attribute_administration"></color>行政<br/><LOC,UI.Councilor.AdministrationTip>
UI.Codex.codex_attributes6=<color=#FFFFFFFF><sprite name="attribute_science"></color>科学<br/><LOC,UI.Councilor.ScienceTip>
UI.Codex.codex_attributes7=<color=#FFFFFFFF><sprite name="attribute_security"></color>安全<br/><LOC,UI.Councilor.SecurityTip>
UI.Codex.codex_attributes8=<color=#FFFFFFFF><sprite name="attribute_loyalty"></color>忠诚<br/><LOC,UI.Councilor.LoyaltyTip>
UI.Codex.codex_traits.Title=特质
UI.Codex.codex_traits0=特质是理事与生俱来的特性，可提供固定或条件的属性值加成或回扣、收入，或建立特定组织的权力。你可以花费经验值来消除或升级部分特质。
UI.Codex.codex_augmentations.Title=增强
UI.Codex.codex_augmentations0=增强代表你可以为理事增加控制性植入物，其作用大致与特质类似。
UI.Codex.codex_XP.Title=经验值
UI.Codex.codex_XP0=<LOC,UI.Councilor.XPTooltip>
UI.Codex.codex_orgs.Title=组织
UI.Codex.codex_orgs0=组织即可以由理事控制的政府机关、私营企业和犯罪集团。组织可为阵营的国家投资优先计划提供收益、属性加成、新任务与加成。组织分为 1 到 3 层级（以组织图示附带的星星数表示），理事在“管理”属性的每个点可管理一个组织等级。
UI.Codex.codex_orgs1=阵营的专属市集会提供大部分的组织，但组织会轮流于一段时间后供其他阵营使用。你可以花费金钱、影响力，或在少数情况下以行动力或运载力购买组织，亦可通过敌方接管任务或与其他阵营交易获得组织。完成目标或进行事件时，阵营也可能获得特殊组织。 
UI.Codex.codex_orgs2=阵营可将具有货币价值的组织价值卖回市场，并拥有许多未分配的组织，可用于在理事之间转移。
UI.Codex.codex_orgs3=阵营名单上的组织不会为阵营带来任何好处，但造成负收益的组织会持续花费资源来维持。阵营只能在自己的名单保留 10 个非阵营特定的组织，其余必须卖出或转移给理事直接管理。
UI.Codex.codex_orgs4=为理事新获得的组织在下一个任务阶段之前不会提供收益，为了计算理事的组织能力而进行的管理除外。如果一名理事遭到拘留，所有组织都将处于非活动状态。
UI.Codex.codex_missions.Title=任务
UI.Codex.codex_missions0=游戏将定期进入任务阶段，在此期间，所有派别都将秘密地将他们的理事分配给任务。这些任务将在未来几天或几周内按顺序解决。虽然有些任务是自动成功的，但大多数任务是对抗性任务且有成功概率，需要进行任务判定。任务通常针对国家、地区、控制点、空间设施和其他理事。
UI.Codex.codex_missions1=在任务阶段之间，任务按预先确定的部分顺序进行，由任务描述中可见的小时钟符号的数量表示。非对抗性和防御性的任务比对抗性任务更早触发。当两名理事试图执行同一任务时，在计算任务成功几率时，会优先计算主属性较高的那名理事的成功率。
UI.Codex.codex_missions2=争夺任务的成功率，会通过加总特定任务的所有相关加成与回扣来决定，而执行任务的阵营可能须花费资源来提升成功率。若加成与回扣加总为零，那么成功率便为 50%；若加总不为零，各方向的每个点对成果的影响会越来越小。变更地球条件可调整任务指派阶段与任务完成之间的成功率。
UI.Codex.codex_missions3=完成争夺的任务后，会产生 0 到 100 之间的随机数字；若数字低于或等于成功率，那么任务成功，反之则任务即失败。若最终数字低于成功率的 10%，则代表重大成功，比起一般成功，重大成功通常会带来加成；若最终数字落在可能失败率范围的前 10%，则表示重大失败，会带来更为严重的后果。
UI.Codex.codex_missionList.Title=任务列表
UI.Codex.codex_missionList0=这些是《地球不屈》中人类理事可以执行的任务。 
UI.Codex.codex_missionList_alien.Title=外星人任务列表
UI.Codex.codex_missionList_alien0=在战役期间，阵营会解锁外星人在地球上活动的相关知识，随着有关外星人及外星相关任务的资讯逐渐揭露，这份清单会越来越长。
UI.Codex.codex_detection.Title=监控
UI.Codex.codex_detection0=执行任务可能会暴露身份，暴露几率取决于任务及其结果。具有高间谍属性的理事或者理事在阵营拥有控制点的国家执行任务将更难被发现，而理事调查分数高的阵营更有可能看到理事。执行“监视位置”任务使您更有可能发现特定地区或太空殖民地中的其他阵营理事。
UI.Codex.codex_detection1=有些理事虽然会被发现，但你不一定知道他们的确切身份。若要进一步了解理事，你可以针对他们执行<h>调查理事</h>任务。
UI.Codex.codex_detection2=若你认为自己的理事被发现，执行<h>回到地面</h>任务可让他们较不易被追踪。
UI.Codex.codex_nations.Title=国家
UI.Codex.codex_nations0=地球上的国家处在抗击外星侵略的前线，是政治和军事冲突的场所。人类阵营利用理事和军队，争相控制这些国家，以利用后者的资源来实现它们的目标。 
UI.Codex.codex_nations1=《地球不屈》 (Terra Invicta) 中的大多数国家对应于一个现实世界的地球国家，不过在某些情况下，为了提升与游戏规模的相关程度，相邻的小国家群体会合并成一个国家，而这些国家之间的国际问题通常会小于模拟规模。阵营就像国家的秘密投资者一样，只要投入足够的心思，他们就可以控制国家的经济和外交政策。
UI.Codex.codex_regions.Title=地区
UI.Codex.codex_regions0=国家是由一个或多个地区组成。地区会以该地的主要城市命名，主要在地理而非政治上发挥影响力；地区的存在是为了标记重要资产和军队的地点。若有新的国家形成或现有国家改变，这类国家便由其他国家的地区组成。 
UI.Codex.codex_regions1=地区是航天设施的所在地：提供运载力的发射设施、任务管控力设施，以及游戏后期的地对轨道防御设施。
UI.Codex.codex_regions2=战争期间，军队会在地区作战并占领地区。
UI.Codex.codex_regions3=理事在地球上移动时，他们会处在某个地区中，且可以在这里被侦测到，但是理事的大部分工作是在国家层面进行的。
UI.Codex.codex_regions4=地区可能会<h>崎岖难行</h>，也就是军队通过地区的时间更长，而防守方在对战时拥有极大的优势。沿海地区是海军升级军队的出发和抵达点。地球赤道上或附近的地区会为特定投资量带来更多运载力，因为这里的地球旋转速度较高，有利于发射火箭。
UI.Codex.codex_claims.Title=权利主张
UI.Codex.codex_claims0=有些国家在不属于他们的地区上拥有权利主张，这些多为他们通过战争或分裂运动获得的地区。
UI.Codex.codex_claims1=有些社会科学计划可以在战役期间解锁新的权利主张。
UI.Codex.codex_controlPoints.Title=控制点
UI.Codex.codex_controlPoints0=<LOC,UI.Nation.ControlPointDescription>
UI.Codex.codex_controlPoints1=控制点包含多种类型，其类型视国家政府和其他条件而定，并可为控制的阵营提供相关加成。其中，最重要的是可让拥有者控制国家外交政策的<h>行政</h>控制点，
UI.Codex.codex_controlPoints2=某些有力的政策，比如加入和离开联盟、以及国家合并，需要以<h>巩固</h>控制行政权力为前提，这意味着掌权阵营要么通过战争或革命获得国家的控制权，要么必须在一定时间内连续控制行政控制点。
UI.Codex.codex_controlPoints3=<LOC,UI.Nation.ControlPointCost>
UI.Codex.codex_incomes.Title=收益
UI.Codex.codex_incomes0=国家会依照比例向拥有控制点的阵营提供金钱、研究、运载力和任务管控力。投资多种<h>优先计划</h>可增加所有阵营获得的这些资源。
UI.Codex.codex_nationStats.Title=国家属性值
UI.Codex.codex_nationStats0=由于外星人到来，在地球上许多早已脆弱不堪的国家区域，其繁荣和稳定受到质疑。玩家可以追踪及查看这些情况，同时可以采取各种行动来缓和情形。以下为重要的国家价值和角色：
UI.Codex.codex_nationStats1=<color=#FFFFFFFF><sprite name="gov_type"></color>政府<br/><LOC,UI.Nation.DemocracyHelp1>
UI.Codex.codex_nationStats2=<color=#FFFFFFFF><sprite name="nation_unrest"></color>动乱<br/><LOC,UI.Nation.UnrestHelp1>
UI.Codex.codex_nationStats3=<color=#FFFFFFFF><sprite name="per_capita_GDP"></color>国内生产总值和人均国内生产总值<br/><LOC,UI.Nation.GDPHelp1>
UI.Codex.codex_nationStats4=<LOC,UI.Nation.PerCapitaGDPHelp1>
UI.Codex.codex_nationStats5=<color=#FFFFFFFF><sprite name="army_level"></color>军事科技<br/><LOC,UI.Nation.MiltechHelp1>
UI.Codex.codex_nationStats6=<color=#FFFFFFFF><sprite name="education"></color>教育<br/><LOC,UI.Nation.EducationHelp1>
UI.Codex.codex_nationStats7=<color=#FFFFFFFF><sprite name="culture"></color>凝聚力<br/><LOC,UI.Nation.CohesionHelp1>
UI.Codex.codex_nationStats8=<color=#FFFFFFFF><sprite name="inequality"></color>不平等值<br/><LOC,UI.Nation.InequalityHelp1>
UI.Codex.codes_nationStats9=<color=#FFFFFFFF><sprite name="greeneconomy_orange"></color>经济可持续性<br/><LOC,UI.Nation.SustainabilityHelp1>
UI.Codex.codex_publicOpinion.Title=民意
UI.Codex.codex_publicOpinion0=所有地球人对外星人的到来都有特定看法，但人的想法是可塑的，而事件和宣传可以让他们转向不同的观点。
UI.Codex.codex_publicOpinion1=这些观点与各阵营的意识形态一致，不过其中会有人的观点是“未定”。意识形态有相对于彼此的位置，若事件可能改变某人的意见，他们通常会转换成类似的想法，例如抵抗派支持者的观点若变得更为激进，可能会接近人类至上派的想法，或者单纯软化成未定。
UI.Codex.codex_publicOpinion2=你阵营的大众观点是主要的影响力资源来源，在大众大部分的观点偏袒你的国家时，你也会收到任务加成。
UI.Codex.codes_publicOpinion3=阵营可通过犯下暴行来推动民意。暴行是会造成死亡或痛苦的行动，因此须负责的阵营会面临支持者减少。暴行会累积，当阵营犯下越多暴行，民意的惩罚会急遽增加。
UI.Codex.codex_priorities.Title=国家优先计划
UI.Codex.codex_priorities0=投资点代表一个国家创造的剩余经济资本。每个国家都会根据其经济规模产生一定数量的投资点，并因动乱度和军队数量相应减少。一个国家的<h>优先计划</h>控制这些投资点的分配。每个控制点的拥有者可以将一定份额的投资点投入到任何数量的优先计划中。
UI.Codex.codex_priorities1=设定各优先计划的重要值（0、1、2 或 3）即可分配投资，而投入特定优先计划的投资金额会根据特定控制点设定的总重要值而定。
UI.Codex.codex_priorities2=投资点数会逐渐投入各优先计划的投资额度，达到最高额度后，国家便会受该优先计划影响，而在多数情况下，投资可能会再次达到优先计划的最高额度。
UI.Codex.codex_priorities3=你也可以研发并保存“设计优先计划范本”，这是预先设定好的投资点细分规划。这些范本可以快速套用至所有由你掌握控制点的国家。你可以将任意范本指定为默认范本，夺取新控制点之后就可以很方便地套用范本。
UI.Codex.codex_priorities4=阵营也可在所选的优先计划上花费金钱、影响力和行动，就能直接投资国家。这么做可让军队、发射设施和其他资产迅速完成。然而，国家一年只能获得一定数量的直接投资。
UI.Codex.codex_priority_economy.Title=经济
UI.Codex.codex_priority_economy0=<LOC,UI.Nation.EconomyPriorityGeneric>
UI.Codex.codex_priority_welfare.Title=福利
UI.Codex.codex_priority_welfare0=<LOC,UI.Nation.WelfarePriorityGeneric>
UI.Codex.codex_priority_environment.Title=环境
UI.Codex.codex_priority_environment0=<LOC,UI.Nation.EnvironmentPriorityGeneric>
UI.Codex.codex_priority_knowledge.Title=知识
UI.Codex.codex_priority_knowledge0=<LOC,UI.Nation.KnowledgePriorityGeneric>
UI.Codex.codex_priority_government.Title=政府
UI.Codex.codex_priority_government0=<LOC,UI.Nation.GovernmentPriorityGeneric>
UI.Codex.codex_priority_unity.Title=团结
UI.Codex.codex_priority_unity0=<LOC,UI.Nation.UnityPriorityGeneric>
UI.Codex.codex_priority_foundMilitary.Title=建立军队
UI.Codex.codex_priority_foundMilitary0=<LOC,UI.Nation.Military_FoundMilitaryPriorityGeneric>
UI.Codex.codex_priority_military.Title=军事
UI.Codex.codex_priority_military0=<LOC,UI.Nation.MilitaryPriorityGeneric>
UI.Codex.codex_priority_oppression.Title=镇压
UI.Codex.codex_priority_oppression0=<LOC,UI.Nation.OppressionPriorityGeneric>
UI.Codex.codex_priority_spoils.Title=牟利
UI.Codex.codex_priority_spoils0=<LOC,UI.Nation.SpoilsPriorityGeneric>
UI.Codex.codex_priority_funding.Title=资金
UI.Codex.codex_priority_funding0=<LOC,UI.Nation.FundingPriorityGeneric>
UI.Codex.codex_priority_spaceflight.Title=太空飞行计划
UI.Codex.codex_priority_spaceflight0=<LOC,UI.Nation.Civilian_InitiateSpaceflightProgramPriorityGeneric>
UI.Codex.codex_priority_launchFacilities.Title=运载力
UI.Codex.codex_priority_launchFacilities0=<LOC,UI.Nation.LaunchFacilitiesPriorityGeneric>
UI.Codex.codex_priority_missionControl.Title=任务管控力
UI.Codex.codex_priority_missionControl0=<LOC,UI.Nation.MissionControlPriorityGeneric>
UI.Codex.codex_priority_buildArmy.Title=建立军队
UI.Codex.codex_priority_buildArmy0=<LOC,UI.Nation.Military_BuildArmyPriorityGeneric>
UI.Codex.codex_priority_sealift.Title=建立海军
UI.Codex.codex_priority_sealift0=<LOC,UI.Nation.Military_SealiftPriorityGeneric>
UI.Codex.codex_priority_initiateNuclearProgram.Title=开发核武器
UI.Codex.codex_priority_initiateNuclearProgram0=<LOC,UI.Nation.Military_InitiateNuclearProgramPriorityGeneric>
UI.Codex.codex_priority_nuclearWeapons.Title=建造核武器
UI.Codex.codex_priority_nuclearWeapons0=<LOC,UI.Nation.Military_BuildNuclearWeaponsPriorityGeneric>
UI.Codex.codex_priority_spaceDefenses.Title=太空防御设施
UI.Codex.codex_priority_spaceDefenses0=<LOC,UI.Nation.Military_BuildSpaceDefensesPriorityGeneric>
UI.Codex.codex_priority_buildSTOSquadron.Title=建造轨道站战斗机
UI.Codex.codex_priority_buildSTOSquadron0=<LOC,UI.Nation.Military_BuildSTOSquadronPriorityGeneric>
UI.Codex.codex_priority_coreEcoUpgrade.Title=<color=#FFFFFFFF><sprite name=build_core_economic_region></color>新的核心经济地区
UI.Codex.codex_priority_coreEcoUpgrade0=<LOC,UI.Nation.Civilian_CoreEcoUpgradePriorityGeneric>
UI.Codex.codex_priority_coreMineralUpgrade.Title=<color=#FFFFFFFF><sprite name=build_core_mining_region></color>新的采矿地区
UI.Codex.codex_priority_coreMineralUpgrade0=<LOC,UI.Nation.Civilian_CoreMineralUpgradePriorityGeneric>
UI.Codex.codex_priority_coreOilUpgrade.Title=<color=#FFFFFFFF><sprite name=build_core_oil_region></color>新的石油地区
UI.Codex.codex_priority_coreOilUpgrade0=<LOC,UI.Nation.Civilian_CoreOilUpgradePriorityGeneric>
UI.Codex.codex_priority_decolonizeRegion.Title=<color=#FFFFFFFF><sprite name=decolonize_region></color>去殖民化地区
UI.Codex.codex_priority_decolonizeRegion0=<LOC,UI.Nation.Civilian_DecolonizeRegionPriorityGeneric>
UI.Codex.codex_priority_decontaminateRegion.Title=<color=#FFFFFFFF><sprite name=decontaminate></color>无害化地区
UI.Codex.codex_priority_decontaminateRegion0=<LOC,UI.Nation.Civilian_DecontaminateRegionPriorityGeneric>
UI.Codex.codex_relations.Title=国际关系
UI.Codex.codex_relations0=没有交战的国家彼此之间可以处于三种状态之一：它们可能是盟友，也可能是对手，或者关系正常。
UI.Codex.codex_relations1=具备战争能力的盟军即是拥有军队或核武的国家，他们会在遭受攻击时参战以防卫彼此。盟军也可能会在战争或和平期间派送军队到对方的地区。在战争开始后，交战双方的任何盟国也可能会加入战争，只要其不与另一方的任何成员的联盟相冲突。
UI.Codex.codex_relations2=竞争者是可能会通过”制定政策“理事任务与对方开战的国家。如果人类国家对一个新对手宣战，通常会遭受凝聚力损失。
UI.Codex.codex_relations3=在阵营拥有行政控制权的国家，各阵营可能会花费影响力<color=#FFFFFFFF><sprite name="influence"></color>来改变他们与其他国家的双边关系。任何改善关系的行动：从对手到正常外交关系，或从正常外交关系到盟友的行动都需要对方的同意。改善关系的行动也会改变国家之间实施政策的冷却时间。
UI.Codex.codex_relations4=成为盟军与竞争者包含一些限制；各自只拥有一或两个控制点的不相邻国家无法成为盟军或竞争者，除非其中一方拥有海军。与分离国结盟的国家无法与该分离国的母国成为盟军；分离国母国的盟军无法与该分离国结盟。
UI.Codex.codex_relations5=国家若有一个控制点至少比本国少一点的”对等“或实力更强的敌国，也可以获得凝聚力。政府分数大于等于 6 的民主国家只能从与其旗鼓相当的非民主国家手中获得这种奖励。
UI.Codex.codex_federations.Title=联邦
UI.Codex.codex_federations0=<LOC,UI.Nation.FederationTooltipDetail>
UI.Codex.codex_policies.Title=政策
UI.Codex.codex_policies0=政策是国家行政阵营可以用来改变国家方向的行动，理事可以使用<h>制定政策</h>任务来实施政策。可实施的政策包括：
UI.Codex.codex_terrestrialWarfare.Title=陆地战争
UI.Codex.codex_terrestrialWarfare0=在两个竞争国之间，若有一方的行政阵营选择向对方实施”战争“政策，则战争开始。在（拥有军队或核武）的防守竞争国这一方，所有具备战争能力的盟军会参战；而在发动攻击的这一方，所有具备战争能力的盟军可以选择是否要加入攻击国的行列。
UI.Codex.codex_terrestrialWarfare1=军队必须要占领敌国的首都地区，才能赢得战争。达成此条件后，战争就会结束，触发政权更迭事件。该地区的统治权将转移至占领者及其盟友手中。如果任何被入侵的国家仍然存在，胜利者将拥有该国家的控制点。在新的政权出现时，某些国家的属性会改变，具体如何改变有时是无法预测的，但新的统治阵营将能够直接投资该国，一年内无需负担影响力成本。未被占领的地区和剩余的军队将会在政权更迭后造成更大的动乱。
UI.Codex.codex_terrestrialWarfare2=在战时，如果其本国对某个地区提出主张，军队也可以吞并敌对地区，但是地区内的任何战斗都会中断和取消这一企图。战争也可能以简单的和平方式结束，双方回到战前的现状。
UI.Codex.codex_armies.Title=军队
UI.Codex.codex_armies0=军队由多个能在其他国家获得并控制领土的现代部门组成。理事拥有国家至少一部分的控制权后，便可以控管军队。大部分国家在战役初期不会有军队，但人口充足的国家可以通过足够的投资来打造新的军队。虽然军队拥有强大力量，但会减缓国家的经济发展，且仍会受该国的国际关系影响，不过，这个问题也可通过充分控制国家来管理。
UI.Codex.codex_armies1=军队在自己的国家拥有总部地区，若将军队放在该处，国家经济发展所花费的成本会比较低。
UI.Codex.codex_armies2=军队仰赖两项关键值：母国的军事科技水准与实力，实力值会显示军队受到的损伤。 
UI.Codex.codex_armies3=受损的军队会在未发生战斗的所有友好地区进行恢复。军队在本国境内的恢复速度更快，在家乡地区的恢复速度为最快。如果一个国家正在同时恢复多支军队，则恢复速度会减慢。
UI.Codex.codex_armies4=有些军队拥有<h>海军</h>升级，因此可以横渡海洋。在战争期间，只有在国家相对于敌国拥有海军优势时，该国海军才能越过水域。只有较大或较富有的国家有能力建造海军和施展海军战力。
UI.Codex.codex_armies5=摧毁一个军队将在其本国的“建立军队”优先计划中获得投资点，代表使用先前单位的幸存者来重建军队。摧毁一个同时具有海军的军队还将在其本国的“建立海军”优先计划中获得投资点。
UI.Codex.codex_armyOperations.Title=军事行动
UI.Codex.codex_armyOperations0=控制军队的阵营可展开以下军事行动：
UI.Codex.codex_armyBattles.Title=军事战役
UI.Codex.codex_armyBattles0=若至少两个敌对的军队在同一地区，他们就会开战。就机制而言，每个军队一天有一次攻击机会。成功伤害敌军的机率取决于军事科技水准、实力、是否有任何理事通过”顾问“任务将指挥属性借给军队所属国家，以及是否处于防御状态且该地区有”崎岖的“的旗帜。
UI.Codex.codex_armyBattles1=若军队位于敌军地区，但该地区没有任何敌军，军队会开始占领该地、与当地（使用该国科技等级的）国防军作战并受到该国防军的伤害。若军队受到严重损伤，你不需采取任何动作，他们就会试图逃到安全的地点，但如果军队的实力降到零，他们也可能全军覆没。
UI.Codex.codex_armyBattles2=若地区遭到全面占领便随即停战，不过除非战争结束，否则地区的控制权不会转移。尽管损伤率会随着军事科技提升（即拥有更精准的武器）而下降，但地区经济和太空设施仍可能在战争期间受到严重损伤。造成一定程度的损伤后，管辖军队的阵营会被视为犯下暴行。
UI.Codex.codex_navalSuperiority.Title=海军优势
UI.Codex.codex_navalSuperiority0=<LOC,UI.Nation.NavalDetail>
UI.Codex.codex_navalSuperiority1=请注意，新出现的海军封锁不会阻碍已经位于海上的军队到达目的地。
UI.Codex.codex_navalSuperiority2=即使拥有海上自由航运权或海军优势，但与身处这些地区的国家处于战争状态且这些地区没有被占领，则海上运输军队可能无法通过巴拿马和苏伊士运河。由于舰队只能走其他航线，因此任何海上旅行都将花费更长的时间。
UI.Codex.codex_nuclearWarfare.Title=核战
UI.Codex.codex_nuclearWarfare0=有些国家会有许多可使用的核武攻击，这些表示可以向目标地区发射多种战略核武。虽然国家对自己或盟军的领土发动攻击会减轻造成的损伤，但发动核攻击会摧毁地区的经济以及在该区的敌军。发动攻击的阵营会被认为犯下一起或多起暴行，引爆一定数量的核武也会对全球造成剧烈影响。
UI.Codex.codex_nuclearWarfare1=完成核武优先计划可让国家增加更多核武攻击。
UI.Codex.codex_nuclearWarfare2=国家建造核武是为了震慑敌人侵略，若试图征服拥有核武的国家，势必会引发报复性的核武攻击。
UI.Codex.codex_solarSystem.Title=太阳系
UI.Codex.codex_solarSystem0=《地球不屈》模拟地球太阳系中较大的星体，并将距离设在地球到太阳之间距离的 50 倍，其中包括围绕海王星运行的多冰星群“古柏带”。
UI.Codex.codex_solarSystem1=太阳系也包括舰队可前往的“拉格朗日点”，这是由两个星体之间重力汇集而成的稳定固定处，在地图上以几何形状标记。
UI.Codex.codex_orbits.Title=轨道
UI.Codex.codex_orbits0=所有天体和拉格朗日点的周围都有一个或多个环形轨道，阵营可以派遣舰队前往并建立有限的空间站。舰队不需推进剂即可在轨道中保持位置。
UI.Codex.codex_orbits1=靠近天体表面的轨道称为<h>交互</h>轨道。舰队可以前往这些轨道，或是降落，或是轰炸地表上的目标。地球附近交互轨道上的太空殖民地舱体能给地面带来许多好处。
UI.Codex.codex_orbits2=从高度较高的轨道前往其他卫星和行星系统，通常会消耗较少 Delta-v。
UI.Codex.codex_orbits3=有些轨道会以危险符号标记，<color=#FFFFFFFF><sprite name=irradiated_site></color>这些轨道多半会接收到高辐射量，因此建造在该处的空间站不仅需要防护，重量和成本也会比其他地方的空间站高。
UI.Codex.codex_orbits4=有些轨道会产生少量的<color=#FFFFFFFF><sprite name="antimatter"></color>反物质，你可以建造太空殖民地舱体收集这些反物质。
UI.Codex.codex_habSites.Title=太空殖民地据点和矿场
UI.Codex.codex_habSites0=除了环境如地狱般的金星，以及气态巨行星木星、土星、天王星和海王星，所有天体都有至少一个太空殖民地舱体据点，阵营可在这里建立包含矿场和其他舱体的基地。根据规模，体积较大的星体会有多个据点，数量取决于天体的整体规模。
UI.Codex.codex_habSites1=建立矿井后，太空殖民地据点会为控制该矿井的阵营提供某些空间资源，资源类型通常取决于天体的组成成分。
UI.Codex.codex_habSites2=一开始查看太阳系时，阵营只会知道特定太空殖民地据点的矿井可提供的空间资源估计量。若要了解确切的潜力，阵营需要对母天体执行探勘调查。
UI.Codex.codex_habSites3=有些太空殖民地舱体据点会以危险符号标记，<color=#FFFFFFFF><sprite name=irradiated_site></color>这些据点多半会接收到高辐射量，因此建造在该处的基地不仅需要防护，重量和成本也会比其他地方的基地高。
UI.Codex.codex_habSites4=如果我们建立的矿场和电磁弹射器网络足够庞大，将会需要额外的<color=#FFFFFFFF><sprite name="mission_control"></color>进行管理。当某些太空科学全球研究技术完成时，“免费”矿场的价值会提高。
UI.Codex.codex_probes.Title=勘探调查
UI.Codex.codex_probes0=若要建立基地，阵营必须调查天体来判断太空殖民地的精确位置。通过探勘天体，亦会得知精准的矿产量。
UI.Codex.codex_probes1=你可以从地球、太空殖民地的造船厂发射探测器，或者派送具备太空科学实验室舱体的舰船来进行探勘。探勘的资料也可能会被其他阵营偷走。
UI.Codex.codex_research.Title=研究
UI.Codex.codex_research0=在《地球不屈》，研究的过程分为科学与工程。阵营必须决定如何在促进人类了解宇宙的公共计划，以及实现特定目标或提升阵营能力等目标明确的私人计划之间，分配运用研究<color=#FFFFFFFF><sprite name="research"></color>收益。
UI.Codex.codex_research1=人类阵营会共同同时研究三项新科学原理，包括物理、化学或人类如何运作等广泛的知识。这些研究不太会直接改变游戏事件展开的方式，相反的，它们的主要作用在于解锁个别阵营的工程计划。
UI.Codex.codex_research2=对特定原理贡献最多研究的阵营可以选择接下来的研究计划，贡献研究也会提高阵营解锁科技相关计划的机率。
UI.Codex.codex_research3=若拥有足够的基础设施，阵营最多可同时研究三个私人工程计划。计划通常会触发某种影响，或解锁舰船和太空殖民地的新组件。举例来说，可能是“定向能源武器原理”科学原理，而这是“60 公分红外线激光电池”计划的先决条件，这个计划则可以解锁舰船的新武器系统。
UI.Codex.codex_projects.Title=计划
UI.Codex.codex_projects0=并非每个阵营都可以取得所有计划，每个阵营在各计划上有相对应的触发百分比。虽然所有阵营可随时取得某些重要计划，但许多计划只有少部分阵营可以取得，此外，特定战役可能完全不会出现一些非关键科技，此情形是为了模拟人类不清楚某些现实世界的想法是否能实际运作。
UI.Codex.codex_projects1=世界达到先决条件后，不一定会立即提供计划。虽然公共科技在完成前都会处于锁定状态，但阵营可以随时变更正在开发的计划，并储存已完成的研究。有些计划可重复开发，但每一次有阵营完成开发，成本就会随之增加。
UI.Codex.codex_projects2=有些理事会偷走其他阵营完成的计划。
UI.Codex.codex_projects3=许多计划与完成目标有关，这些目标会让阵营更了解外星人入侵的目的，或是胜利的条件。
UI.Codex.codex_techCategories.Title=科技类别
UI.Codex.codex_techCategories0=许多游戏元素通常会基于收益递减为特定研究领域提供加成，这些科技类别包括：
UI.Codex.codex_habitats.Title=太空殖民地
UI.Codex.codex_habitats0=太空殖民地是阵营以太空为基地所运行的设施，阵营可建立两种类型的太空殖民地：可进入轨道的空间站，以及设立于太空殖民地据点的基地。 
UI.Codex.codex_habitats1=这两种类型的太空殖民地舱体皆有三种尺寸，空间站依序有空间平台、轨道站以及环状空间站；基地一开始则是前哨站，接着是大型殖民地舱体，最后是超大型殖民地舱体。
UI.Codex.codex_habitats2=太空殖民地是由舱体组成，所有舱体皆含核心舱体，核心舱体的尺寸会决定太空殖民地的规模。太空殖民地的规模会决定你可以有多少舱体（4、12 或 20 个，加上核心舱体），以及每个舱体的最大尺寸。
UI.Codex.codex_habitats3=大部分太空殖民地舱体会消耗能源，你必须建立足够的发电舱体来容纳其他舱体。你可以关闭舱体来降低能源消耗，但若太空殖民地有可以支持舱体的能源，有些舱体就必须保持开启状态。舱体的维护也会花费空间资源成本，若空间资源不够，你可以用运载力和金钱来支付此成本。有些舱体也会花费任务管控力成本。
UI.Codex.codex_foundingHabs.Title=建立太空殖民地舱体
UI.Codex.codex_foundingHabs0=你可通过三种方式建立太空殖民地舱体，一是使用运载力从地球发射核心舱体，若地点距离我们的家园很远，这种方式会消耗大量时间，如果该任务需要两年以上的时间，可能就不会进入规划阶段。二是开发并建立工具组，以便舰船在抵达轨道或登陆天体时部署；三是在相同行星系统、且有建造舱体的其他太空殖民地舱体建立太空殖民地舱体。
UI.Codex.codex_automatedHabs.Title=自动化太空殖民地
UI.Codex.codex_automatedHabs0=开发足够的科技后，你就可以部署自动化太空殖民地。自动化太空殖民地是小型的机器安装系统，仅能包含你开发的其他自动化舱体。自动化太空殖民地通常会作为舰船的小型矿井或供应站，并需要更多任务管控力，但通常不需要许多空间资源来支持。
UI.Codex.codex_automatedHabs1=请注意，自动化太空殖民地无法使用标准舱体（包含工作人员的舱体），亦无法升级成标准太空殖民地。如果要更换自动化太空殖民地，必须先将其退役。
UI.Codex.codex_buildingHabs.Title=建造太空殖民地
UI.Codex.codex_buildingHabs0=你可以使用运载力从地球运送舱体，或者用太空材料建造，以将太空殖民地舱体加到太空殖民地。随着技术的充分发展，许多舱体都可以开辟出升级到大型版本的路径，通过此方式升级舱体的成本会有减免。
UI.Codex.codex_buildingHabs1=太空殖民地分为不同的“阶层”，阶层数值决定了该太空殖民地可以容纳的舱体规模和数量。升级核心舱体即可提升太空殖民地阶层。
UI.Codex.codex_buildingHabs2=尺寸太小的太空物体无法容纳大于特定规模的太空殖民地。
UI.Codex.codex_assaultingHabs.Title=袭击太空殖民地舱体
UI.Codex.codex_assaultingHabs0=拥有太空陆战队以及具有“突袭敌方太空资产”任务和访问舰队或太空殖民地陆战队的理事的舰队可以突击敌方太空殖民地以试图占领它们。无论哪种情况，突击将利用所在位置的所有可用太空陆战队来发起攻击，包括来自同一位置停靠的其他舰队的太空陆战队。太空殖民地由陆战队舱体进行防御。从轨道攻击基地时，拥有主动式地对轨道防御舱体的太空殖民地也将为防御做出贡献。双方都可能遭受参与突击的太空陆战队舱体的损坏或毁灭。
UI.Codex.codex_assaultingHabs1=使用“突击”任务的理事能够贡献他们的指挥属性和行动力资源，相对于由舰队发起的突击，这将增加他们成功的机会。
UI.Codex.codex_defendingHabs.Title=防御太空殖民地
UI.Codex.codex_defendingHabs0=各个阵营都可以研发能够保护自家太空殖民地的太空殖民地舱体。 
UI.Codex.codex_defendingHabs1=基地防御舱体将会装备重型激光器，能够击落从轨道上进行轰炸的舰船。全球激光技术研究完毕之后，这些激光器都会自动升级。这些舱体还会加装点防御，能够阻拦炮弹。
UI.Codex.codex_defendingHabs2=而且，轨道空间站安装的防御舱体使用的是该阵营通过武器项目研发出来的舰载武器炮塔。每个舱体通常会配备两门炮塔：该阵营最强的激光武器和最强的火炮类武器。较小的太空殖民地舱体可能只会使用已研发完毕的小型炮塔。这些武器在战斗中需要独立控制，无法像舰载武器那样进行指挥。这些舱体虽然能够保护空间站，抵御小型敌方编队的攻击，但如果没有属于自己的支援舰队，就会缺乏足够的火力，无法击败规模更大的舰队。
UI.Codex.codex_defendingHabs3=完成装甲计划也能帮助基地和空间站舱体在受到攻击时支撑得更久。
UI.Codex.codex_defendingHabs4=陆战队舱体可以保护空间站和基地，抵御突袭。
UI.Codex.codex_shipDesign.Title=舰船设计
UI.Codex.codex_shipDesign0=地球上许多秘密计谋及太空的工业化计划，都是阵营建立舰队来保护与提升利益的方式。一旦阵营解锁游戏前期的轨道站造船科技，以及太空殖民地舱体后续的船坞计划，即可建造星际航天器。
UI.Codex.codex_shipDesign1=若拥有足够的舱体，舰船可以探勘及寻找太空殖民地，但大部分舰船的主要目标为战斗。
UI.Codex.codex_shipDesign2=你可以随时运用已开发的舱体来设计舰船。拥有造船厂后，你就能运用空间资源建造舰船，如有必要，也可以使用运载力与金钱造船。
UI.Codex.codes_shipDesign3=建造舰船时，你需要管理质量、加速度和 Delta-v 等重要数值。质量越大，加速度就越低，舰船的操控度也会下降。 Delta-v 衡量你可以改变多少速度，这项数值会控制前往目的地的速度。
UI.Codex.codex_hull.Title=船体
UI.Codex.codex_hull0=若要设计舰船，需要先选择船体。船体的类型会决定舰艏和船体武器挂载点的数量、设施舱体的数量以及船体长度。
UI.Codex.codex_hull1=长度较短的舰船具有比较低的惯性矩，这表示旋转的速度比身形长的舰船更快。
UI.Codex.codex_drive.Title=驱动器
UI.Codex.codex_drive0=<LOC,UI.Fleets.Drive.Description>
UI.Codex.codex_drive1=在战斗中，正在喷射的驱动器有几率摧毁瞄准其尾部的导弹或炮弹。驱动器能量越高，越有可能成功。这就是所谓的“闪耀的火光”。
UI.Codex.codex_powerPlant.Title=动力装置
UI.Codex.codex_powerPlant0=<LOC,UI.Fleets.PowerPlant.Description>
UI.Codex.codex_radiators.Title=散热器
UI.Codex.codex_radiators0=<LOC,UI.Fleets.Radiator.Description>
UI.Codex.codex_batteries.Title=电池
UI.Codex.codex_batteries0=<LOC,UI.Fleets.Battery.Description>
UI.Codex.codex_weapons.Title=武器
UI.Codex.codex_weapons0=武器系统不是装设在舰艏，就是装设在船体上。在武器大小相近的情况下，装设在舰艏的武器威力通常比船体武器更大，但火力范围有限。船体武器可以向舰船周围的任何方向开火。
UI.Codex.codex_weapons1=武器也具有各种大小，大型武器系统会在船体占据多个武器单位。
UI.Codex.codex_weapons2=武器大致分成四种类型：光束武器 （以光速射击并对目标造成瞬时伤害）、发射武器 （向目标发射未导向的弹药，并使用动能或偶尔使用化学能源来击垮目标）、导弹（自我导向的武器系统，可追逐目标直到耗尽推进剂）、粒子武器（其瞄准攻击方式类似于激光，但会在目标的船体内造成辐射损伤）。
UI.Codex.codex_weapons3=某些武器只能用于攻击敌军舰船和太空殖民地舱体，其他则可用于针对来袭的发射武器和导弹进行防御性攻击，也有其他一些武器可攻击这两种目标。
UI.Codex.codex_armor.Title=装甲
UI.Codex.codex_armor0=舰船上的装甲会吸收来袭的武器火力，防止内部零件受到损害。在汽化之前，船体单一位置的每个装甲点会吸收 20 百万焦耳的能量。不同类型的装甲需要不同的厚度及质量来吸收特定量的大量伤害。对轰炸舰队的地对轨攻击总是会击中舰船的舰艏装甲。
UI.Codex.codex_armor1=舰艏和舰艉每个装甲点的质量都比侧面装甲要小，因为侧面装甲必须覆盖更大的表面积。随着舰船的表面积增加，每增加一个侧面装甲点的质量也在增加，同时，舰艏和舰艉装甲也必须覆盖更大的区域。
UI.Codex.codex_armor2=每种船体类型都有其所支持的最大装甲量。
UI.Codex.codex_propellantTanks.Title=推进剂箱
UI.Codex.codex_propellantTanks0=每艘舰船必须有一个或多个 100 吨的推进剂箱。推进剂箱的数量会决定舰船的 Delta-v 数值。
UI.Codex.codex_shipOfficers.Title=舰船军官
UI.Codex.codex_shipOfficers0=当舰船进行长途巡航或参加战斗时，船员能够获得宝贵的经验。有时，船上的一名或多名军官是各自专业领域的熟练专家，并且有一组经验丰富的宇航员在他们的手下服务。这些军官将会获得名字，且他们所服役的舰船也有加成。
UI.Codex.codex_shipOfficers1=军官可以多次晋升，每个级别都有更高的奖励。军官可能会在战斗中阵亡。 //They may also retire if they serve long enough. Higher-ranked officers may transfer between ships in the same fleet or docked at the same hab, but in doing so they will lose one step in rank, representing the loss in familiarity with their environment.
UI.Codex.codex_shipOfficers2=以下列表为军官类型、要求和可能拓展的能力。
UI.Codex.codex_fleets.Title=舰队
UI.Codex.codex_fleets0=舰队由一艘或多艘舰船组成，并由人类阵营或外星人指挥。舰队可采取行动并在太空战斗中作战。
UI.Codex.codex_shipConstruction.Title=建造舰船
UI.Codex.codex_shipConstruction0=个别的舰船可在太空船坞、造船厂或太空工程舱体的太空殖民地中建造。你可以混合使用在太空开采的资源与从地球运送的材料来建造舰船，建造完成后，舰船会在建造的太空殖民地安置停靠。
UI.Codex.codex_shipRefits.Title=改装
UI.Codex.codex_shipRefits0=阵营可在太空殖民地利用建造舱体改装舰船，改装通常限于更换相似类型的零件。<br/><br/>你无法更换船体。<br/>若新的动力装置与旧的等级相同，你可以更换动力装置。<br/>驱动器可以在现有的驱动组中增加或移除推进器，或更换成相同类别、具有所需动力装置和推进剂的驱动器。<br/>若新武器与旧武器的等级与底座相同，你可以更换武器（例如 1 级船体激光就只能换成 1 级船体的激光）。<br/>你可以自由变更装甲。<br/>你可以自由将电池更换成其他电池，但不能换成其他设施舱体。<br/>你可以自由更换储热槽，但不能换成其他设施舱体。<br/>你可以自由变更散热器。<br/>电池或储热槽以外的设施舱体可以更换成其他同等级的舱体。
UI.Codex.codex_propellant.Title=Delta-v
UI.Codex.codex_propellant0=<h>Delta-v</h> 是速度变化的简称，用来衡量舰船在合理时间内达到指定目的地的能力。消耗有限的推进剂资源来产生推力会清空推进剂箱，因此会减少舰船可能达到的 Delta-v。
UI.Codex.codex_propellant1=舰船的 Delta-v 来自舰船总质量、拥有多少推进剂，以及使用推进剂的驱动效率（称为“比冲”或<h>排气速度</h>，《地球不屈》使用排气速度一词）。
UI.Codex.codex_propellant2=根据舰船在太阳系中所处位置的推力和重力，舰船可以通过消耗额外的 Delta-v 来标绘更快到其他目的地的路线。
UI.Codex.codex_propellant3=舰队所有舰船之中最低的 Delta-v 即是舰队的 Delta-v。
UI.Codex.codex_propellant4=舰船必须在具有补给站或造船厂的太空殖民地补给推进剂。
UI.Codex.codex_transfers.Title=调动
UI.Codex.codex_transfers0=调动意指舰队从太空中某处移到另一处的动作。舰队可以调动到轨道、空间站或其他舰队。
UI.Codex.codex_transfers1=启动调动行动后，若舰队完全可以到达目的地，便会获得一个或多个轨道选项。若有多个路径可以选择，玩家可以在抵达时间与 Delta-v 消耗量之间衡量选择。
UI.Codex.codex_transfers2=路径包括<h>微推力螺旋</h>（通常适合低加速度的舰队）、<h>脉冲圆锥</h>（适合高加速度但低 Delta-v 的舰队）、<h>火炬弦</h>（适合高加速度与高 Delta-v 的进阶舰队）。
UI.Codex.codex_fleetOperations.Title=舰队行动
UI.Codex.codex_fleetOperations0=舰队可以采取各种行动，通常只能在轨道中且非调动时进行，这些行动包括：
UI.Codex.codex_orbitalBombardment.Title=轨道轰炸
UI.Codex.codex_orbitalBombardment0=配备磁力、激光或核能武器的舰队可以对天体表面上的目标进行轨道轰炸，舰队必须位于交互轨道，才能发动攻击。 
UI.Codex.codex_orbitalBombardment1=在地球上空，有效目标包括军队、太空设施、地区以及任何我们侦测到的外星资产。在其他天体上，基地和登陆的太空舰队都可能成为目标。
UI.Codex.codex_orbitalBombardment2=特定武器（例如以紫外线波长发射的激光）无法穿越比较厚的大气层进行轰炸，尤其是地球和土卫六的大气层。
UI.Codex.codex_orbitalBombardment3=若被锁定的太空殖民地或地区具有防御力，便会回击发动攻击的舰队并试图击落飞行物和导弹。
UI.Codex.codex_orbitalBombardment4=轰炸舰队可以选择与目标进行交战的高度，以权衡风险与伤害。在较高的高度，双方的激光效果会较弱，而防御系统将有更大的机会击落抛射物和导弹。
UI.Codex.codex_spaceCombat.Title=太空战斗
UI.Codex.codex_spaceCombat0=若有两艘敌对阵营的舰队在轨道、深空或空间站相遇，便会引发太空战斗。玩家可以选择自动解决战斗。
UI.Codex.codex_spaceCombat1=在战斗开始前，各舰队会从以下三种立场中选择一种：参战、接受或回避。至少需有一方舰队选择”参战“，战斗才会开始；若另一方舰队选择”回避“，双方舰队都可以竞标 Delta-v 来进行追击。如果选择”参战“的舰队出价较高，战斗便会开始。如果舰队停泊在太空殖民地，或因先前的战役而无法出战，则只能选择”接受“。
UI.Codex.codex_spaceCombat2=在追逐战中，两支舰队的相对加速度决定了追逐的结果。如果一支舰队的加速度明显高于对手，它可以强制交战，或者耗费少量 Delta-v 而躲避交战。两支具有类似加速度的舰队将进行缓慢的追逐，可能需要耗费大量的 Delta-v 来解决问题，如果双方都决定进行投入的话。追逐战在追逐的舰队与目标之间的距离达到预定距离，或者逃避舰队将两支舰队之间的距离增加同样的距离时结束。
UI.Codex.codex_spaceCombat3=具备防御舱体的空间站会参加战斗，若这些舱体毁损，即视为停用。
UI.Codex.codex_spaceCombat4=规模浩大的太空战斗会需要出动现役舰船的增援舰船。当现役舰船毁损，增援舰船就会取而代之并加入战斗。在战斗期间，你可以随时前往“选项”选单的游戏玩法设定，调整现役舰船的数量上限。举例来说，如果数量上限为 30，则双方于任何时间各可使用最多 15 架舰船。这项机制的用意在于维护大规模战役的运作效能。
UI.Codex.codex_spaceCombat5=当舰队或空间站遭受攻击，在同样轨道中、距离少于 1000 KM 的防御方盟军舰队将会加入防御舰队一同战斗。
UI.Codex.codex_maneuvers.Title=操控
UI.Codex.codex_maneuvers0=作战时，玩家可通过在 3D 空间中设定航点来安排操纵舰船。舰船会转向并向航点前进。玩家也可以旋转舰船的面向而不改变前进方向，以向敌军展示某些武器或装甲表面。
UI.Codex.codex_specialManeuvers.Title=特殊操控
UI.Codex.codex_specialManeuvers0=特殊操控包含持续旋转、匹配速度，以及让舰艏固定朝向主要目标的锁定目标命令。
UI.Codex.codex_fireControl.Title=火力控制
UI.Codex.codex_fireControl0=武器有一种或多种可用的火力模式，可以于作战时设置在舰队、舰船或个别的武器等级中。
UI.Codex.codex_fireControl1=舰船也可以指定敌军的舰船或太空殖民地舱体作为主要目标，相较于其他人，舰船的武器就会更容易锁定该敌军。导弹武器需要有主要目标才可以发射。
UI.Codex.codex_fireControl2=依据武器能力，你也可将武器设定成只攻击敌军舰船、只对来袭的发射武器或导弹进行防御性攻击，或者设定”守卫“模式，首先攻击造成威胁的发射武器，接着再锁定敌军战舰。
UI.Codex.codex_targeting.Title=瞄准和电子反制措施
UI.Codex.codex_targeting0=所有武器都有一个以 KM 为单位的目标射程值，即武器可以瞄准目标舰船并向其开火的最大范围绝对值。如果光束武器不能对目标造成足够的伤害，则其射击距离无法达到此最大射程。
UI.Codex.codex_targeting1=所有舰载武器必须抵抗任何敌方电子反制措施 (ECM) 才能成功瞄准敌人。否则，这些武器将受到反制并强制冷却。导弹武器的冷却时间更长，因为它们的自动制导系统也要抵抗电子反制措施。  
UI.Codex.codex_targeting2=瞄准计算机舱体可以抵抗敌人的电子反制措施。舰船在战斗中成功抵抗某些舰船的电子反制措施后，也能更快地瞄准此舰船。
UI.Codex.codex_targeting3=舰船很容易受到各类武器（核武器、反物质武器、激光武器和粒子武器）的攻击，因此必须在装甲外部安装传感器。传感器损坏后，舰艇抵御电子反制措施的能力将下降，但能够快速修复。
UI.Codex.codex_heatManagement.Title=热能管理
UI.Codex.codex_heatManagement0=开启舰船的动力装置就能充电，或开启驱动器，制造废热（通常会被舰船的散热器排掉）。该系统无法使用装甲。在战斗中，散热器可以收起，但舰船必须将其所有废热累积在储热槽中。储热槽有容量限制。展开散热器时，热度会自动降低。如果储热槽的热度达到上限，舰船会开始承受内部损伤。在战斗中，散热器会在允许情况下自动展开散热。<h>请记住，如果没能进行妥善的热能管理，舰船将会遭受灾难般的故障。</h> 
UI.Codex.codex_batteryManagement.Title=电池管理
UI.Codex.codex_batteryManagement0=当舰船的动力装置用于推进或损坏时，电池将被用作能量源。
UI.Codex.codex_damage.Title=损伤控制
UI.Codex.codex_damage0=任何穿透舰船装甲的伤害都会影响到舰船的内部系统，武器和其他舱体可能会暂时停用或永久损坏，此时便需要在造船厂的太空殖民地进行维修。
UI.Codex.codex_damage1=损伤控制小组也会试着恢复重要作战系统的运作。