UI.Fleets.Title=舰队
UI.Fleets.DryMass=干质量：<rcol>{0} T</rcol>
UI.Fleets.WetMass=湿质量：<rcol>{0} T</rcol>
UI.Fleets.CurrentMass=目前质量：<rcol>{0} T</rcol>
UI.Fleets.ItemMass=质量：<rcol>{0} T</rcol>
UI.Fleets.SingleDV={0} kps										// DV as in ∆V, Delta-v, is a rocket science term that measures how much a ship can change (∆) its velocity ("v")
UI.Fleets.DVValue={0}/{1} kps
UI.Fleets.DV=Delta-V：<rcol>{0}/{1} kps							
UI.Fleets.BaseDV=Delta-V：<rcol>{0} kps
UI.Fleets.ThreeDV=Delta-V：<rcol>{0}/{1}/{2} kps
UI.Fleets.StdDV={0} {1} kps
UI.Fleets.Accelgs={0} G
UI.Fleets.Accelmgs={0} 千分 G
UI.Fleets.AccelmgsAbbr={0} mG
UI.Fleets.TwoValues={0}/{1}
UI.Fleets.CruiseAccel=巡航加速度：<rcol>{0}</rcol>
UI.Fleets.CombatAccel=最大战斗加速度：<rcol>{0}</rcol>
UI.Fleets.CruiseAcceleration=巡航加速度：{0}
UI.Fleets.CombatAcceleration=战斗加速度：{0}
UI.Fleets.TurnRate=转向速率：<rcol>{0} deg/sec^2</rcol>
UI.Fleets.WetMassTab=湿质量：
UI.Fleets.WetMassTab.Description=“湿质量”是指舰船满载燃料时的总质量。质量会影响舰船的机动性。较高的质量会降低 Delta-v 和转向速率。<br/><br/>质量细分：
UI.Fleets.CrewTab=组员：
UI.Fleets.CrewTab.Description=在舰船上服役的人员数目。
UI.Fleets.CruiseAccelerationTab=巡航加速度：
UI.Fleets.CruiseAccelerationTab.Description=这代表舰船在战略层面变换速率的速度。若提高巡航加速度，可让舰船克服天体的引力，以及选择更直接的路径到达目的地。<br/><br/>加速度若能至少达到 100 千分 G，就是较为理想的状态。加速度低于 10 千分 G 的飞船航行时间可能会延长，尤其是在从行星重力井深处发射时。<br/><br/>舰船加速度如果低于 0.5 千分 G，可能会无法完成大多数星际转移，因为这类舰船需要的航行时间太长。
UI.Fleets.CombatAccelerationTab=战斗加速度：
UI.Fleets.CombatAccelerationTab.Description=舰船在战斗层面变换速率的速度。有些驱动系统能够在战斗状态下，进行短时间的高加速。
UI.Fleets.CruiseDeltaVTab=巡航 Delta-v：
UI.Fleets.CruiseDeltaVTab.Description=决定舰船能够抵达的位置，以及抵达的速度。推进剂可以提升 Delta-v，舰船质量则会降低 Delta-v。<br/><br/>若 Delta-v 低于 8 kps，舰船将难以从地球轨道抵达月球。<br/><br/>若 Delta-v 低于 30 kps，舰船将无法稳定地完成从地球出发的星际航行任务。<br/><br/>Delta-v 达到 60 kps 的舰船可执行更为严苛的航行任务，例如从水星航行到土星。<br/><br/>查看<h>游戏法则</h>以获取更多信息。
UI.Fleets.TurnRateTab=转向速率：
UI.Fleets.TurnRateTab.Description=舰船在战斗中可以改变航向的速度。这个值会受到舰船的长度和质量影响。在同等条件下，较短的舰船转弯较快。
UI.Fleets.HeatSinkCapacityTab=储热容量：
UI.Fleets.HeatSinkCapacityTab.Description=当舰船在战斗中收起脆弱的散热器时，储热槽可以暂时负责处理舰船的热能。储热槽数值越高，舰船就能在不展出散热器的情况下作战越久。
UI.Fleets.BatteryCapacityTab=电池容量：
UI.Fleets.BatteryCapacityTab.Description=当发电厂不可用时，舰船的电池会储存来自动力装置的电力，以供大部分的武器系统使用。高阶电池可在作战时充电。
UI.Fleets.ConstructionCostTab=建造成本：
UI.Fleets.ConstructionCostTab.Description=建造该舰船需要的资源。可以用运载力和金钱代替缺少的资源。这样可能会增加建造时间，因为材料必须从地球运来。  
UI.Fleets.ConstructionTimeTab=建造时间：
UI.Fleets.ConstructionTimeTab.Description=造船厂集合所有必要材料后，建造舰船所需的时间。大型造船厂建造舰船的时间比较短。
UI.Fleets.MaintenanceCostTab=支援：
UI.Fleets.MaintenanceCostValue={0}{1} {2}{3}/月
UI.Fleets.MaintenanceCostTab.Description=维护该舰船的月度成本。如果没有支付维护成本，这艘舰船将更容易被其他阵营夺取。
UI.Fleets.ConstructionTime={0} 天												// value, value, boost icon
UI.Fleets.ConstructionTimeLine=/{0}
UI.Fleets.GJ={0} GJ
UI.Fleets.Degs2={0} deg/sec^2
UI.Fleets.Length=船长：<rcol>{0} 公尺</rcol>
UI.Fleets.Beam=船辐：<rcol>{0} 公尺</rcol>
UI.Fleets.DriveLine=驱动器：<rcol>{0}</rcol>
UI.Fleets.PowerPlantLine=动力装置：<rcol>{0}</rcol>
UI.Fleets.BatteryLine=电池：<rcol>{0}</rcol>
UI.Fleets.RadiatorsLine=散热器：<rcol>{0}</rcol>
UI.Fleets.HeatSinkCapacity=储热槽容量：<rcol>{0} GJ</rcol>									// GJ = 千兆焦耳
UI.Fleets.HeatSinkCapacityUnk=储热槽容量：<rcol>未知</rcol>									// GJ = 千兆焦耳
UI.Fleets.NoseWeaponsHeader=舰艏武器
UI.Fleets.HullWeaponsHeader=船体武器
UI.Fleets.UtilityModuleHeader=设施舱体
UI.Fleets.NoseArmorMaterial=舰艏装甲：<rcol>{0} cm {1}</rcol>
UI.Fleets.ArmorRating=装甲评等/伤害减免：<rcol>{0}</rcol>
UI.Fleets.LateralArmorMaterial=横向装甲：<rcol>{0} cm {1}</rcol>
UI.Fleets.TailArmorMaterial=舰艉装甲：<rcol>{0} cm {1}</rcol>
UI.Fleets.NoseArmorMaterialunk=舰艏装甲：<rcol>未知</rcol>
UI.Fleets.LateralArmorMaterialunk=横向装甲：<rcol>未知</rcol>
UI.Fleets.TailArmorMaterialunk=舰艉装甲：<rcol>未知</rcol>
UI.Fleets.Crew=组员：<rcol>{0}</rcol>
UI.Fleets.DamConCrew=损伤控制组员：<rcol>{0}</rcol>
UI.Fleets.DamConCrew.Description=在战斗中，损伤控制组员的规模决定了修复速度。若有足够多的组员，就可以同时修复多个舱体。
UI.Fleets.ShipyardButtonText=舰船等级
UI.Fleets.ShipDesignerButtonText=设计舰船等级
UI.Fleets.FullClassName={0}级{1}										// proper noun, hull type
UI.Fleets.ClassName={0}级												// proper noun
UI.Fleets.DesignerCoreDataHeader=船级和船体
UI.Fleets.DesignerShipDataHeader=舰船效能资料
UI.Fleets.NeedDrive=需要驱动器
UI.Fleets.DesignerHeader=飞船设计工具
UI.Fleets.ClassListHeader={0} 舰船等级
UI.Fleets.DerivedValuesHeader=舰船资料
UI.Fleets.PrimarySystemsHeader=主要系统
UI.Fleets.MissionSystemsHeader=任务系统
UI.Fleets.DamageControl=损伤报告
UI.Fleets.ShowAllShips=查看所有舰船
UI.Fleets.ShowAllFleets=显示所有舰队
UI.Fleets.Utility=设施舱体
UI.Fleets.Utility.Description=设施舱体有不同的效能，能强化航天器的不同能力。储热槽是战斗舰船的重要舱体，能避免脆弱的散热器暴露在敌人的炮火之下。额外的电池也可以放进设施舱体栏位中。
UI.Fleets.PowerPlant=动力装置
UI.Fleets.PowerPlant.Description=舰船的动力装置能为舰船的驱动系统和其他舰船系统提供能量。动力装置的质量与系统驱动或舰船系统的功率中的较大者的电力要求成比例。动力装置也会产生废热，必须使用储热槽储存或通过散热器排出。<br/><br/>备注：许多驱动器需要特定级别的动力装置来运作，有时候，较低科技的动力装置有可能无法产出足够的能量来支援进阶的驱动器，就算等级正确也一样。
UI.Fleets.Battery=电池
UI.Fleets.Battery.Description=舰船的主要电池会储存来自动力装置的能量，当主动力装置由于损坏，或舰船上的主驱动器正在运行，并且没有独立给驱动器供电而无法供能时，电池能量会提供给武器、维生系统和其他关键系统使用。高功率的武器在战斗中会迅速用光电池的电力。改良过的电池会有更大的容量或更快的充电速度。你也可以在同类型设施舱体栏位上安装额外电池，以获得更高的储电量。
UI.Fleets.Radiator=散热器
UI.Fleets.Radiator.Description=散热器能够消除动力装置产生的废热。它们的大小取决于动力装置的输出和效能。因为它们在战斗中非常脆弱，如果舰船有在设施栏位有一个或多个储热槽，可以把散热器收回。然而，一旦舰船的储热槽装满，散热器就必须被再次展开，来保护组员的生命！
UI.Fleets.Drive=驱动器
UI.Fleets.Drive.Description=驱动器会从舰船的舰艉排出推进剂来让舰船前进。驱动器有很多不同形态，不过通过两种常见的数值来评分：推力及排气速度。高推力的驱动器可以在较短的时间内达到较高的速度，而高排气速度的驱动器使用则会较少的推进剂。这两个数值会决定船只的动力装置需要有多少电力。为舰船加上100 T 的推进剂箱能提高舰船的 Delta-v，或是它改变速度的幅度。<br/><br/>注意：许多驱动器需要特定等级的动力装置才能运行，在某些情况下，正确等级的低技术动力装置可能无法产生足够的电力来支持高级驱动器。
UI.Fleets.NoseArmor=舰艏装甲
UI.Fleets.NoseArmor.Description=舰船舰艏上的装甲会吸收来袭的武器火力，防止内部零件受到损害。在汽化之前，船体单一位置的每个装甲点会吸收 20 百万焦耳的能量。不同类型的装甲需要不同的厚度及质量来吸收这么大量的伤害。
UI.Fleets.LateralArmor=横向装甲
UI.Fleets.LateralArmor.Description=舰船船体上的装甲会吸收轰炸左舷及右舷面的武器火力，防止内部零件受到损害。在汽化之前，船体单一位置的每个装甲点会吸收 20 百万焦耳的能量。不同类型的装甲需要不同的厚度及质量来吸收这么大量的伤害。要注意的是，横向装甲点比舰艏及舰艉装甲大上许多，因为它要覆盖的面积更大。
UI.Fleets.TailArmor=舰艉装甲
UI.Fleets.TailArmor.Description=舰船舰艉上的装甲会吸收来袭的武器火力，防止内部零件受到损害。在汽化之前，船体单一位置的每个装甲点会吸收 20 百万焦耳的能量。不同类型的装甲需要不同的厚度及质量来吸收这么大量的伤害。
UI.Fleets.SaveRequirement=要储存这个舰船设计，它必须包含驱动器、动力装置、散热器、电池、装甲材料（零厚度也一样）、至少一个推进剂箱以及一个指派的角色。殖民船等特殊飞船还必须包含一个设施舱体，使其能实现自身舰种功能。
UI.Fleets.NoseHardPoint=舰艏挂载点
UI.Fleets.NoseHardPoint.Description=舰艏挂载点能安装舰载前向武器。此类武器通常比装在船体上的武器威力更强，但舰船要使用此类武器，必须先转向，以舰艏对准目标。有些大型武器会占用多个挂载点。 
UI.Fleets.HullHardPoint=船体挂载点
UI.Fleets.HullHardPoint.Description=船体硬点用来安装可以往任何方向发射的武器。有些较大的武器会占用多个硬点。
UI.Fleets.Propellant=推进剂
UI.Fleets.Propellant.Description=每个推进剂箱能为舰船的驱动器提供 100 T 的推进剂，增加舰船的 Delta-v。
UI.Fleets.None=选取舱体或栏位
UI.Fleets.None.Description=从上方选单选取一个舱体并把它放到合适的栏位，以此开始建造你的舰船。
UI.Fleets.DesignerPropellantTanks=推进剂箱<br/>{0}
UI.Fleets.ArmorOnFacing=最大： {0}
UI.Fleets.DesignerSaveDesign=保存设计
UI.Fleets.ValidRefitDesign=有效改装
UI.Fleets.InvalidRefitDesign=无效改装
UI.Fleets.RefitFailDuplicate=改装不能是现有类型的副本。
UI.Fleets.RefitFailHull=船体必须匹配。
UI.Fleets.RefitFailPowerPlant=动力装置必须是同一等级。
UI.Fleets.RefitFailDrive=驱动器必须有相同的等级、动力装置和推进剂类型。
UI.Fleets.RefitFailHeatSink=散热器不能与其他舱体一起改装。
UI.Fleets.RefitFailBattery=电池不能与其他舱体一起改装。
UI.Fleets.RefitFailUtilityModule=设施舱体只能改装为同一类型的设施舱体。
UI.Fleets.RefitFailWeaponModule=武器不能改装为不同类型或不同装弹量的武器。
UI.Fleets.DesignerDVWarningHeader=警告
UI.Fleets.DesignerDVWarningYes=是
UI.Fleets.DesignerDVWarningNo=否
UI.Fleets.DesignerDVWarningBody1=这艘舰船没有足够的 Delta-v 来进行星际旅行，不过可以在一个行星系统间移动。建议增加更多推进剂、减少质量、或是使用排气速度较高的驱动器，以增加这艘舰船的行进范围。你还是想要储存这个设计吗？
UI.Fleets.DesignerDVWarningBody2=这艘舰船没有足够的 Delta-v 来进行大部分的移动，只能用来防卫一座空间站。建议增加更多推进剂、减少质量、或是使用排气速度较高的驱动器，以增加这艘舰船的行进范围。你还是想要储存这个设计吗？
UI.Fleets.DesignerResetDesign=清除设计工具
UI.Fleets.DeleteModule=移除舱体
UI.Fleets.Designer.Transfer.SetTranser=选择范例转移
UI.Fleets.Designer.Transfer.ToFrom={0} 到 {1}
UI.Fleets.Designer.Transfer.NoAcceleration=无引擎
UI.Fleets.Designer.Transfer.NeedDV=需要 {0} kps
UI.Fleets.ConstructionManagerButtonText=建造舰船
UI.Fleets.ConstructionManagerHeader=建造舰船
UI.Fleets.ConstructionManagerNoShipyards=建造太空船坞或可以用来组装航天器的大型太空殖民地设施。
UI.Fleets.ConstructionManagerNoDesigns=你要不是还没有舰船设计，就是已经把所有设计标为淘汰。
UI.Fleets.ConstructionManagerShowAll=显示全部
UI.Fleets.ConstructionManagerFilter=地点
UI.Fleets.RefitRefuelWarning=舰船在改装期间还会进行补充燃料和修理，而且需要支付所需费用。选择多艘同一级别的舰船进行改装时，如果需要补充燃料或修理，那么每艘舰船的改装费用可能会有所不同，具体取决于每艘舰船自己的补充燃料和修理费用。
UI.Fleets.SelectAShipClass=选取舰船等级
UI.Fleets.AddToConstructionQueueButton=新增到伫列
UI.Fleets.ClearQueueButton=取消预备
UI.Fleets.PayFromEarthTooltip=只要勾选此选项，造船厂就能使用运载力和金钱从地球运输资源，替代我们阵营缺少的任何空间资源。这可能会增加建造时间，因为我们必须等待资源送达。
UI.Fleets.LeadQueueItem={0}（{1} 天）										//class name, days done
UI.Fleets.OtherQueueItem={0}（{1} 天）											//
UI.Fleets.CurrentlyBuilding=目前建造中：<br/>{0}（剩余 {1} 天）
UI.Fleets.CurrentlyWaitingForResources=等待资源送达：<br/>{0}<br/>需要{1}
UI.Fleets.ShipyardIdle=闲置
UI.Fleets.GotoHabs=太空殖民地
UI.Fleets.ShipyardDetails={0}（{1}）{2}											// shipyard module name, sector ID
UI.Fleets.Inactive=未供电
UI.Fleets.Altitude=海拔：{0} KM
UI.Fleets.Mass=质量：<rcol>{0} T</rcol>
UI.Fleets.Tons={0} T
UI.Fleets.RequiredPowerMW=需要电力：<rcol>{0} 百万瓦</rcol>
UI.Fleets.RequiredPowerGW=需要电力：<rcol>{0} 吉瓦</rcol>
UI.Fleets.RequiredPowerTW=需要电力：<rcol>{0} 兆瓦</rcol>
UI.Fleets.NoRequiredPower=这个驱动器不需要外部电源。
UI.Fleets.NoRole=无角色
UI.Fleets.RoleLine=角色：<rcol>{0}
UI.Fleets.SS_Interceptor=截击舰
UI.Fleets.MS_Strike=突击舰
UI.Fleets.LS_Penetrator=突防舰
UI.Fleets.LM_Protector=保护舰
UI.Fleets.SM_Patrol=巡逻舰
UI.Fleets.MM_SpaceSuperiority=空优舰
UI.Fleets.LM_Interdictor=拦截舰
UI.Fleets.LM_Raider=突袭舰
UI.Fleets.SL_Defender=防御舰
UI.Fleets.ML_Standoff=对峙舰
UI.Fleets.LL_Intruder=入侵舰
UI.Fleets.LL_Bomber=轰炸舰
UI.Fleets.TroopCarrier=突击队运载舰
UI.Fleets.ArmyCarrier=远征军运载舰
UI.Fleets.Explorer=探索舰
UI.Fleets.InnerSystemColonyShip=内星系殖民舰船
UI.Fleets.OuterSystemColonyShip=外星系殖民舰船
UI.Fleets.CouncilorTransport=运输
UI.Fleets.EarthSurveillance=监控
UI.Fleets.ClassData.Help=
UI.Fleets.NoRole.description=这艘舰船还没有指派到角色。舰船设计必须有指派的角色才能储存。
UI.Fleets.SS_Interceptor.description=战略范围：短。牺牲推进剂量换取机动性。<br/>最佳战斗交战距离：短。
UI.Fleets.MS_Strike.description=战略范围：中程。<br/>适合交战范围：短程。
UI.Fleets.LS_Penetrator.description=战略范围：长。重视推进剂量，以便开展星际行动。<br/>首选交战距离：近距离。
UI.Fleets.LM_Protector.description=战略范围：长。重视推进剂量，以便开展星际行动。<br/>首选交战距离：近距离。<br/>侧重点防御，范围足以保护附近的舰船。
UI.Fleets.SM_Patrol.description=战略范围：短。牺牲推进剂量换取机动性。<br/>首选交战距离：中距离。
UI.Fleets.MM_SpaceSuperiority.description=战略范围：中程。<br/>适合交战范围：中程。
UI.Fleets.LM_Interdictor.description=战略范围：长。重视推进剂量，以便开展星际行动。<br/>首选交战距离：中距离。
UI.Fleets.LM_Raider.description=战略范围：长。重视推进剂量，以便开展星际行动。<br/>首选交战距离：中距离。<br/>侧重使舰船获得独立于舰队运作的能力。 
UI.Fleets.SL_Defender.description=战略范围：短。牺牲推进剂量换取机动性。<br/>首选交战距离：远距离。
UI.Fleets.ML_Standoff.description=战略范围：中程。<br/>适合交战范围：远程。
UI.Fleets.LL_Intruder.description=战略范围：长。重视推进剂量，以便开展星际行动。<br/>首选交战距离：远距离。
UI.Fleets.LL_Bomber.description=战略范围：长。重视推进剂量，以便开展星际行动。<br/>首选交战距离：远距离。<br/>侧重可实施轰炸的武器。
UI.Fleets.TroopCarrier.description=必须携带陆战队舱体。非战斗舰船将部署于主要阵形之后，且会试着避免战斗。
UI.Fleets.ArmyCarrier.description=非战斗舰船将部署于主要阵形之后，且会试着避免战斗。
UI.Fleets.Explorer.description=必须携带勘探舱体。非战斗舰船将部署于主要阵形之后，且会试着避免战斗。
UI.Fleets.InnerSystemColonyShip.description=必须携带太空殖民地组合舱体。非战斗舰船将部署于主要阵形之后，且会试着避免战斗。
UI.Fleets.OuterSystemColonyShip.description=必须携带太空殖民地核能组合舱体。非战斗舰船将部署于主要阵形之后，且会试着避免战斗。
UI.Fleets.CouncilorTransport.description=非战斗舰船将部署于主要阵形之后，且会试着避免战斗。
UI.Fleets.EarthSurveillance.description=非战斗舰船将部署于主要阵形之后，且会试着避免战斗。
UI.Fleets.AssignRoleTip=点击以根据舰船的特性自动分配职能。<br/>舰船职能会决定自动设计的偏好，以及受 AI 控制的舰船在战斗中的行为模式。
UI.Fleets.Autodesign=自动设计
UI.Fleets.NoseWeaponsTab=舰艏武器
UI.Fleets.HullWeaponsTab=船体武器
UI.Fleets.UtilitiesTab=设施舱体
UI.Fleets.RadiatorsTab=散热器
UI.Fleets.BatteriesTab=电池
UI.Fleets.PowerPlantTab=动力装置
UI.Fleets.DriveTab=驱动系统
UI.Fleets.ArmorTab=装甲
UI.Fleets.AllWeaponsTab=全部
UI.Fleets.GunsTab=枪炮
UI.Fleets.MissilesTab=导弹
UI.Fleets.MagneticWeaponsTab=磁力武器
UI.Fleets.PlasmaWeaponsTab=电浆武器
UI.Fleets.LasersTab=激光
UI.Fleets.ParticleWeaponsTab=粒子束
UI.Fleets.ModuleTable.FireModes=发射模式
UI.Fleets.ModuleTable.Cooldown=冷却时间
UI.Fleets.ModuleTable.ShortRangeDamage=近射程<br/>伤害
UI.Fleets.ModuleTable.MediumRangeDamage=中<br/>射程
UI.Fleets.ModuleTable.LongRangeDamage=远<br/>射程
UI.Fleets.ModuleTable.Damage=伤害
UI.Fleets.ModuleTable.Magazine=弹匣
UI.Fleets.ModuleTable.MagazineMaterials=弹匣材料
UI.Fleets.ModuleTable.Range=射程
UI.Fleets.ModuleTable.Mass=质量
UI.Fleets.ModuleTable.EnergyUsage=能源消耗
UI.Fleets.ModuleTable.ShotPower=发射火力
UI.Fleets.ModuleTable.ShortRangeArmorEffectiveness=短程<br/>装甲有效度
UI.Fleets.ModuleTable.MediumRangeArmorEffectiveness=中<br/>射程
UI.Fleets.ModuleTable.LongRangeArmorEffectiveness=远<br/>射程
UI.Fleets.ModuleTable.ChargingEnergy=充电能量
UI.Fleets.ModuleTable.Salvo=齐射
UI.Fleets.ModuleTable.SalvoCooldown=齐射<br/>冷却时间
UI.Fleets.ModuleTable.MuzzleVelocity=初速
UI.Fleets.ModuleTable.MissileType=类型
UI.Fleets.ModuleTable.MissileAcceleration=加速度
UI.Fleets.ModuleTable.MissileDV=Delta-V
UI.Fleets.ModuleTable.Materials=材料
UI.Fleets.ModuleTable.HeatSinkCapacity=容量
UI.Fleets.ModuleTable.TonsPerGW=T/GW
UI.Fleets.ModuleTable.Vulnerability=脆弱度
UI.Fleets.ModuleTable.MaterialsPerGW=材料/GW
UI.Fleets.ModuleTable.RechargeTime=充电时间
UI.Fleets.ModuleTable.BatteryCapacity=容量
UI.Fleets.ModuleTable.Efficiency=效率
UI.Fleets.ModuleTable.SpecificPower=特定能量
UI.Fleets.ModuleTable.MaximumOutput=最大输出
UI.Fleets.ModuleTable.Thrust=推力
UI.Fleets.ModuleTable.ExhaustVelocity=排气速度
UI.Fleets.ModuleTable.RequiredPower=需要电力
UI.Fleets.ModuleTable.TonsPerSquareMeterPerPoint=T/㎡<br/>/点
UI.Fleets.ModuleTable.Speciality=专长
UI.Fleets.ModuleTable.MaterialsPerTon=材料/T
UI.Fleets.AddModule=添加
UI.Fleets.LandedLocation=降落于{0}
UI.Fleets.DockedLocation=停泊于{0}
UI.Fleets.DestinationLocationOrbit=正在传输至{0}
UI.Fleets.DestinationLocationHab=正在传输至{0}
UI.Fleets.DestinationLocationFriendlyFleet=与{0}集结
UI.Fleets.DestinationLocationFleet=正在拦截{0}
UI.Fleets.OrbitLocation=于{0}
UI.Fleets.ExpandedLocation=，{0}
UI.Fleets.ArrivalDate=（抵达日期{0}）
UI.Fleets.Unavailable=舰队将可以在{0}上执行行动。
UI.Fleets.Cost=建造成本：<rcol>{0}</rcol>
UI.Fleets.MagazineCost=重新填装成本：<rcol>{0}</rcol>
UI.Fleets.RoleTab=角色：
UI.Fleets.ArmorSummaryTab=装甲（艏／体／艉）：
UI.Fleets.ArmorSummaryValue={0}/{1}/{2}
UI.Fleets.WeaponMountDataOne={0}底座，使用 {1} 个硬点						// nose/hull, #
UI.Fleets.WeaponMountDataMult={0}底座，使用 {1} 个硬点					// nose/hull, #
UI.Fleets.Nose=舰艏
UI.Fleets.Hull=船体
UI.Fleets.FireModes=发射模式：<rcol>{0}</rcol>												// list of allowed modes
UI.Fleets.Focus=集中火力
UI.Fleets.Offense=攻击
UI.Fleets.Defense=防御
UI.Fleets.Guardian=守护
UI.Fleets.HullMass=船体：{0}
UI.Fleets.Bombardment=可以轰击：<rcol>{0}</rcol>
UI.Fleets.Bombardment_No=否
UI.Fleets.Bombardment_Yes=是
UI.Fleets.Bombardment_NoAtmo=无法穿透大气
UI.Fleets.PowerPlantMass=动力装置：{0}
UI.Fleets.RadiatorMass=散热器：{0}
UI.Fleets.BatteryMass=电池：{0}
UI.Fleets.NoseArmorMass=舰艏装甲：{0}
UI.Fleets.LateralArmorMass=横向装甲：{0}
UI.Fleets.TailArmorMass=舰艉装甲：{0}
UI.Fleets.PropellantMass=推进剂质量：{0}
UI.Fleets.CrewMass=组员质量：{0}
UI.Fleets.ModuleMass={0}：{1}
UI.Fleets.PropellantType=推进剂：<rcol>{0}</rcol>
UI.Fleets.PropellantMaterials=推进剂材料/箱：<rcol>{0}</rcol>
UI.Fleets.TwoColumn={0}<rcol>{1}</rcol>
UI.Fleets.Build=建造
UI.Fleets.Upgrade=升级
UI.Fleets.Obsolete=淘汰
UI.Fleets.HideObsolete=隐藏淘汰
UI.Fleets.Construct=建造新舰船
UI.Fleets.Refit=改装停泊舰船
UI.Fleets.DockedShips=停泊舰船
UI.Fleets.ValidRefitClasses= 有效改装等级
UI.Fleets.HullDescription=硬点：{0} 舰艏，{1} 船体。设施舱体：{2}。{3}{4}。{5}{6}/月。 
UI.Fleets.RightToToggleLists=右键单击切换列表和图标面板
UI.Fleets.RightToPlace=右键单击将此舱体放置到可用的栏位，或直接将图标拖拽到想要放置的栏位。
UI.Fleets.ShipyardShipMinimums=从这个地面造船厂发射的舰船必须有至少 {0} 的战斗加速度和至少 {1} kps 的 Delta-v 才能进入轨道。
UI.Fleets.Unknown=未知舰队
UI.Fleets.HomeBase=太空殖民地大本营
UI.Fleets.HomeBaseDetail=为这支舰队设定太空殖民地大本营会使其成为航行的默认目的地。
UI.Fleets.BuildDays=建造（{0} 天）	
UI.Fleets.AddToConstructionQueueButtonDays=添加到队列中（{0} 天）					// d for days
UI.Fleets.FleetListButtonText=舰队
UI.Fleets.RefitDays=改装（{0} 天）
UI.Fleets.NumShipsSingle={0}舰船
UI.Fleets.NumShipsPlural={0}舰船
UI.Fleets.RefitIterationSuffix=截击
UI.Fleets.NIS={0}+{1}
UI.Fleets.Explosive=<color=#FFFFFFFF><sprite name=warning></color>此舱体如果受到伤害，就会爆炸。
UI.Fleets.FleetsListTab=舰队列表
UI.Fleets.ShipDetailTab=舰船详细信息
UI.Fleets.AlertLevel=警报等级
UI.Fleets.ArrivalTime=抵达时间