TICondition.Numeric.EqualTo=for igual a {0}
TICondition.Numeric.NotEqualTo=não for igual a {0}
TICondition.Numeric.GreaterThan=> {0}
TICondition.Numeric.GreaterThanOrEqualTo=for pelo menos {0}
TICondition.Numeric.LessThan=< {0}
TICondition.Numeric.LessThanOrEqualTo=for {0} ou menos
TINationCondition_Generic= em nações onde {0} {1}														// symbol, numeric comparison
TINationCondition_fMiltech= em nações onde o nível de tecnologia militar {0}									// numeric comparison
TINationCondition_iControlPoints= em nações onde a quantidade de pontos de controle {0}							// numeric comparison
TINationCondition_iArmies= em nações onde a quantidade de exércitos {0}										// numeric comparison
TINationCondition_efPublicOpinion= em nações onde o apoio público para {0} {1}
TINationCondition_efPriority= em nações onde a porcentagem de pontos de investimento destinada à prioridade de {0} {1}	// priority name, numeric pct comparison
TINationCondition_efMonthlyIPsToPriority= em nações onde o número de pontos de investimento destinada à prioridade de {0} a cada mês {1}
TINationCondition_bFactionControlledTRUE= em nações controladas por qualquer facção
TINationCondition_bFactionControlledFALSE= em nação não controlada por uma facção
TINationCondition_bIsAlienNationTRUE= na nação alienígena
TINationCondition_bIsAlienNationFALSE= em uma nação controlada por humanos
TINationCondition_bAnySpaceAssetsTRUE= em nações com quaisquer propulsão, controle de missão ou defesas espaciais
TINationCondition_bAnySpaceAssetsFALSE= em nações sem um programa espacial
TINationCondition_bAggregateNationTRUE= em uma nação agregada composta por países pequenos do mundo real
TINationCondition_bAggregateNationFALSE= em uma nação não agregada
TINationCondition_bFactionHasControlTRUE= em nações controladas por: {0}
TINationCondition_bFactionHasControlFALSE= em nações não controladas por: {0}
TINationCondition_iNavies= em nações onde a quantidade de marinhas {0}
TINationCondition_bHasAntiSpaceDefensesTRUE= em nações com defesas antiespaciais em funcionamento
TINationCondition_bHasAntiSpaceDefensesFALSE= em nações sem defesas antiespaciais em funcionamento
TIRegionCondition= em regiões onde {0} {1}
TIRegionCondition_bCoastalTRUE= está em uma região que faz fronteira com um oceano
TIRegionCondition_bCoastalFALSE= está em uma região completamente cercada por terra
TIRegionCondition_bOnTheWaterTRUE= está em uma região que atualmente tem acesso a um oceano
TIRegionCondition_bOnTheWaterFALSE= está em uma região que atualmente não tem acesso a um oceano
TIRegionCondition_eEnvironment= em regiões onde o ambiente está classificado como {0}
TIRegionCondition_eRugged= em regiões onde o terreno é {0}
TIRegionCondition_fLatitude= em regiões onde a latitude é {0}
TIRegionCondition_fAbsLatitude= em regiões onde os graus de distância do equador são {0}
TIRegionCondition_fLongitude= em regiões onde a longitude é {0}
TIRegionCondition_fMonthlyBoost= em regiões onde o valor mensal de {0} {1}
TIRegionCondition_bCapitalTRUE= na região capital de uma nação
TIRegionCondition_bCapitalFALSE= nas regiões não-capitais de uma nação
TIRegionCondition_bCoreEconomicTRUE= em regiões econômicas primárias
TIRegionCondition_bCoreEconomicFALSE= em regiões econômicas secundárias
TIRegionCondition_bCoreResourceTRUE= em regiões produtoras de recursos
TIRegionCondition_bCoreResourceFALSE= em regiões não produtoras de recursos
TIRegionCondition_bColonyTRUE= em regiões que sejam colônias
TIRegionCondition_bColonyFALSE= em regiões que não sejam colônias
TIFactionCondition_eIdeologyEqualTo= para {0}
TIFactionCondition_eIdeologyNotEqualTo= se não for {0}
TIFactionCondition_bAlienProxyTRUE= para {0}
TIFactionCondition_bAlienProxyFALSE= para {0}
TIFactionCondition_bAlienAppeaserTRUE= para {0}
TIFactionCondition_bAlienAppeaserFALSE= se não for {0}
TIFactionCondition_efResourceValue= quando nossa reserva de {0} {1}
TIFactionCondition_iAtrocities= quando nossa soma de atrocidades {0}
TIFactionCondition_tbHasEffectTRUE= quando tivermos o efeito {0}
TIFactionCondition_tbHasEffectFALSE= quando não tivermos o efeito {0}
TIFactionCondition_bCouncilorHasTraitTRUE= quando um conselheiro tiver a característica {0}
TIFactionCondition_bCouncilorHasTraitOrPredecessorTRUE= quando um conselheiro tiver a característica {1} ou {0}
TIFactionCondition_iCouncilorStat= quando o atributo de {0} de um conselheiro {1}
TIFactionCondition_bExtremistTRUE= para facções extremistas
TIFactionCondition_bExtremistFALSE= para facções não extremistas
TIFactionCondition_bProAlienTRUE= para facções pró-alienígenas
TIFactionCondition_bProAlienFALSE= para facções que não são pró-alienígenas
TIFactionCondition_bAntiAlienTRUE= para facções antialienígenas
TIFactionCondition_bAntiAlienFALSE= para facções que não são antialienígenas
TIFactionCondition_iAlienInvestigations= quando nossas atividades alienígenas investigadas até o momento {0}
TIFactionCondition_tbCompletedProject= para facções que completaram o projeto {0}
TIFactionCondition_iAggregateStat= quando a média dos atributos de {0} de nossos conselheiros {1}
TIFactionCondition_iTotalStat= quando a soma dos atributos de {0} de nossos conselheiros {1}
TIFactionCondition_iHabs= quando a facção tem {0} habitats
TIFactionCondition_iMines= quando a facção tem {0} minas
TIFactionCondition_iHabSupportFailureLevel= quando o nível de falha de abastecimento aos habitats da facção {0}
TIFactionCondition_efResourceIncomeDaily= quando a receita diária de {0} da nossa facção {1}
TIFactionCondition_bCynicalTRUE= para facções com ideologias cínicas
TIFactionCondition_bBelieversTRUE= para facções com ideologias idealistas
TIFactionCondition_fSpaceCombatValueLEO= quando a força total de combate da frota da nossa facção na órbita terrestre baixa {0}
TIFactionCondition_iSpaceDefenseFacilities= quando nossa facção controlar {0} regiões com defesas espaciais ativas
TIFactionCondition_iAssassinatedHumans= quando a quantidade de conselheiros humanos assassinados por essa facção {0}
TIFactionCondition_iAssassinatedAliens= quando a quantidade de agentes alienígenas assassinados por essa facção {0}
TIFactionCondition_iAssassinations= quando a quantidade de assassinatos bem sucedidos dessa facção {0}
TICouncilorCondition_bInHomeNationTRUE= se na nação de origem
TICouncilorCondition_bInHomeNationFALSE= se fora de nação de origem
TICouncilorCondition_tbHasTraitHas= se este conselheiro tiver a característica {0}
TICouncilorCondition_tbHasTraitDoesNotHave= se este conselheiro não tiver a característica {0}
TICouncilorCondition_tbHasTraitOrPredecessorHas= se este conselheiro tiver as características {0} ou {1}
TICouncilorCondition_tbHasTraitOrPredecessorDoesNotHave= se este conselheiro não tiver as características {0} ou {1}
TICouncilorCondition_bHasTraitGroupingTRUE= se este conselheiro tiver pelo menos uma das seguintes características: {0}
TICouncilorCondition_bHasTraitGroupingFALSE= se este conselheiro não tiver pelo menos uma das seguintes características: {0}
TICouncilorCondition_bHasTraitWithTagTRUE= se este conselheiro tiver pelo menos uma das seguintes características: {0}
TICouncilorCondition_bHasTraitWithTagFALSE= se este conselheiro não tiver pelo menos uma das seguintes características: {0}
TICouncilorCondition_iStat= quando o atributo de {0} deste conselheiro {1}
TICouncilorCondition_iStatWithoutOrgs= quando o atributo de {0} deste conselheiro {1} (sem organizações)
TICouncilorCondition_iNumLoseableOrgs= quando a carteira de organizações não exclusivas do conselheiro {0}
TICouncilorCondition_iAssassinatedHumans= quando a quantidade de conselheiros humanos assassinados por esse conselheiro {0}
TICouncilorCondition_iAssassinatedAliens= quando a quantidade de agentes alienígenas assassinados por esse conselheiro {0}
TICouncilorCondition_iAssassinations= quando a quantidade de assassinatos bem sucedidos por esse conselheiro {0}
TIHabCondition_tbHasModuleFunctioningTRUE= para habitats com um módulo de {0}
TIHabCondition_tbHasModuleFunctioningFALSE= para habitats sem um módulo de {0}
TIHabCondition_tbHasModuleOrUpgradePrereqFunctioningTRUE= para habitats com um módulo de {0} ou {1}
TIHabCondition_tbHasModuleOrUpgradePrereqFunctioningFALSE= para habitats sem um módulo de {0} ou {1}
TIGlobalCondition_bNuclearWeaponsUsed= se nações tiverem usado armas nucleares durante essa campanha
TIGlobalCondition_tbCompletedTech= se a tecnologia de {0} tiver sido pesquisada
TIGlobalCondition_fCampaignDuration_years= se a campanha já durar {0} anos
TIGlobalCondition_bDummyConditionTRUE= sob qualquer circunstância
TIGlobalCondition_bDummyConditionFALSE= sob nenhuma circunstância
TIHabCondition_fSpaceCombatValue= se os pontos de defesa providos por módulos desse habitat {0}
TIHabCondition_fSpaceCombatValueFromDockedFleets= se os pontos de defesa providos por naves atracadas desse habitat {0}
TIHabCondition_fAggregateDefensiveScore= se os pontos de defesa providos por módulos e naves atracadas desse habitat {0}
TIHabCondition_bAllowsShipConstruction= se este habitat tiver um estaleiro
TIHabCondition_fAssaultCombatValue= se o destacamento de fuzileiros deste habitat {0}
TIHabCondition_fAssaultCombatValueFromDockedFleets= se qualquer frota atracada neste habitat tiver destacamentos de fuzileiros {0}
TIHabCondition_fAssaultCombatValueCombined= se este habitat ou qualquer frota atracada tiver destacamentos de fuzileiros {0}
TIHabCondition_fMarineCombatValue= se o destacamento de fuzileiros deste habitat {0}
TIHabCondition_fMarineCombatValueCombined= se este habitat ou qualquer frota atracada tiver destacamentos de fuzileiros {0}
TIHabCondition_fConstructionTimeModifier= se o total do modificador de tempo de construção provido por módulos desse habitat {0}
TIHabCondition_bHasConstructionModule= se este habitat tem um módulo de construção
TIHabCondition_fTechBonus= se o bônus dos módulos deste habitat para pesquisa de {0} {1}
TIHabCondition_efResourceIncomeAnnual= se a receita anual de {0} deste habitat {1}
TIHabCondition_bHasSpecialRule= se um dos módulos deste habitat tem a regra especial {0}
TIHabCondition_fPowerToSectorRatio= quando a distribuição de energia aos setores deste habitat {0}
TIArmyCondition_bFactionControlledTRUE= para exércitos controlados por qualquer facção
TIArmyCondition_fNationMiltechDifferential= se a diferença entre a tecnologia militar deste exército e a da região atual {0}
TISpaceShipCondition_bHasSpecialRuleTRUE= para naves com um módulo de utilidade de {0}
TISpaceShipCondition_iModulesWithSpecialRule= para naves com um módulo de utilidade de {0} {1}
TISpaceShipCondition_bLaserBonusPowerTRUE= para naves com um módulo de utilidade de Propulsor Laser
TISpaceShipCondition_tbHasUtilityModuleTypeTRUE= para naves com um módulo de utilidade de {0}
TISpaceShipCondition_tiNumberOfUtilityModulesType= para naves cuja quantidade de módulos de utilidade de {0} {1}
TISpaceShipCondition_fAssaultCombatValue= se o destacamento de fuzileiros desta nave {0}