TIOfficerTemplate.displayName.Officer_Admiral=Almirante
TIOfficerTemplate.displayName.Officer_Captain=Comandante
TIOfficerTemplate.displayName.Officer_First=Imediato
TIOfficerTemplate.displayName.Officer_FireControl=Oficial de Controle de Disparos
TIOfficerTemplate.displayName.Officer_Gunnery=Oficial de Artilharia
TIOfficerTemplate.displayName.Officer_DirectedEnergy=Oficial de Energia Dirigida
TIOfficerTemplate.displayName.Officer_DamageControl=Oficial de Resposta a Danos
TIOfficerTemplate.displayName.Officer_Engineering=Oficial de Engenharia
TIOfficerTemplate.displayName.Officer_Propulsion=Oficial de Propulsão
TIOfficerTemplate.displayName.Officer_Medical=Oficial Médico
TIOfficerTemplate.displayName.Officer_CIC=Oficial de CIC
TIOfficerTemplate.displayName.Officer_Intel=Oficial de Inteligência
TIOfficerTemplate.displayName.Officer_Marine=Oficial de Fuzileiros
TIOfficerTemplate.displayName.Officer_Supply=Oficial de Suprimentos
TIOfficerTemplate.displayName.Officer_Chief=Chefe de Tripulação

TIOfficerTemplate.description.Officer_Admiral=Um oficial veterano cuja presença concede bonificações para toda a frota. Apenas o almirante que esteja no módulo da ponte do almirantado sendo usado para reduzir o <color=#FFFFFFFF><sprite name=mission_control></color> da frota concederá bonificações.
TIOfficerTemplate.description.Officer_Captain=Comandante da nave.
TIOfficerTemplate.description.Officer_First=O segundo em comando da nave.
TIOfficerTemplate.description.Officer_FireControl=O oficial encarregado pelos sistemas de mísseis da nave.
TIOfficerTemplate.description.Officer_Gunnery=O oficial encarregado pelos sistemas de armas de projéteis da nave.
TIOfficerTemplate.description.Officer_DirectedEnergy=O oficial encarregado pelos sistemas de laser e feixes de partículas da nave.
TIOfficerTemplate.description.Officer_DamageControl=O oficial encarregado pelo reparo dos sistemas da nave em combate.
TIOfficerTemplate.description.Officer_Engineering=O oficial encarregado pelo reator e outros sistemas essenciais da nave.
TIOfficerTemplate.description.Officer_Propulsion=O oficial encarregado pelos sistemas de propulsão da nave.
TIOfficerTemplate.description.Officer_Medical=O oficial encarregado por manter a tripulação viva e com saúde.
TIOfficerTemplate.description.Officer_CIC=O oficial encarregado pelo centro de informações de combate e defesas ativas da nave.
TIOfficerTemplate.description.Officer_Intel=O oficial encarregado pelo conhecimento da tripulação sobre o inimigo.
TIOfficerTemplate.description.Officer_Marine=O oficial encarregado pelo destacamento da fuzileiros desta nave.
TIOfficerTemplate.description.Officer_Supply=O oficial encarregado pelos armazéns da nave.
TIOfficerTemplate.description.Officer_Chief=O astronauta sênior da nave que representa a tripulação.

TIOfficerTemplate.Officer_Admiral_1=Contra-Almirante
TIOfficerTemplate.Officer_Captain_1=Capitão
TIOfficerTemplate.Officer_First_1=Tenente
TIOfficerTemplate.Officer_FireControl_1=Alferes
TIOfficerTemplate.Officer_Gunnery_1=Alferes
TIOfficerTemplate.Officer_DirectedEnergy_1=Alferes
TIOfficerTemplate.Officer_DamageControl_1=Alferes
TIOfficerTemplate.Officer_Engineering_1=Tenente
TIOfficerTemplate.Officer_Propulsion_1=Subtenente
TIOfficerTemplate.Officer_Medical_1=Cirurgião de Voo
TIOfficerTemplate.Officer_CIC_1=Alferes
TIOfficerTemplate.Officer_Intel_1=Alferes
TIOfficerTemplate.Officer_Marine_1=Primeiro-Tenente
TIOfficerTemplate.Officer_Supply_1=Alferes
TIOfficerTemplate.Officer_Chief_1=Chefe Suboficial

TIOfficerTemplate.Officer_Admiral_2=Vice-Almirante
TIOfficerTemplate.Officer_Captain_2=Capitão Sênior
TIOfficerTemplate.Officer_First_2=Capitão-Tenente
TIOfficerTemplate.Officer_FireControl_2=Subtenente
TIOfficerTemplate.Officer_Gunnery_2=Subtenente
TIOfficerTemplate.Officer_DirectedEnergy_2=Subtenente
TIOfficerTemplate.Officer_DamageControl_2=Subtenente
TIOfficerTemplate.Officer_Engineering_2=Capitão-tenente
TIOfficerTemplate.Officer_Propulsion_2=Subtenente
TIOfficerTemplate.Officer_Medical_2=Médico
TIOfficerTemplate.Officer_CIC_2=Subtenente
TIOfficerTemplate.Officer_Intel_2=Subtenente
TIOfficerTemplate.Officer_Marine_2=Capitão
TIOfficerTemplate.Officer_Supply_2=Subtenente
TIOfficerTemplate.Officer_Chief_2=Chefe Suboficial Sênior

TIOfficerTemplate.Officer_Admiral_3=Almirante-de-Frota
TIOfficerTemplate.Officer_Captain_3=Capitão-de-Frota
TIOfficerTemplate.Officer_First_3=Comandante
TIOfficerTemplate.Officer_FireControl_3=Tenente
TIOfficerTemplate.Officer_Gunnery_3=Tenente
TIOfficerTemplate.Officer_DirectedEnergy_3=Tenente
TIOfficerTemplate.Officer_DamageControl_3=Tenente
TIOfficerTemplate.Officer_Engineering_3=Comandante
TIOfficerTemplate.Officer_Propulsion_3=Tenente
TIOfficerTemplate.Officer_Medical_3=Médico Sênior
TIOfficerTemplate.Officer_CIC_3=Tenente
TIOfficerTemplate.Officer_Intel_3=Tenente
TIOfficerTemplate.Officer_Marine_3=Major
TIOfficerTemplate.Officer_Supply_3=Tenente
TIOfficerTemplate.Officer_Chief_3=Chefe Suboficial Mestre

TIOfficerTemplate.MaxPerShip=-Máximo de oficiais desta categoria por nave: {0}
TIOfficerTemplate.MaxTotalOfficersPerShip_Hull=-Máximo total de quaisquer categorias de oficiais, com exceção do almirante e do imediato, em cascos tipo {1}: {0}							// number, hull display name
TIOfficerTemplate.MaxTotalOfficersPerShip=-Máximo total de quaisquer categorias de oficiais na nave, com exceção do almirante e do imediato, limitado pelo tamanho do casco
TIOfficerTemplate.CrewMin=-Tripulação mínima exigida: {0}
TIOfficerTemplate.FlagBridge=-Requere um módulo de {0}																			// name of flag bridge ship utility module
TIOfficerTemplate.MissileWeapons=-Requere armas de míssil na nave
TIOfficerTemplate.EnergyWeapons=-Requere armas de laser ou de feixes de partículas na nave
TIOfficerTemplate.GunWeapons=-Requere armas magnéticas, de plasma ou de projéteis na nave
TIOfficerTemplate.DefenseWeapons=-Requere armas que tenham modo de defesa na nave
TIOfficerTemplate.Marines=-Requere fuzileiros na nave
TIOfficerTemplate.TunableDrive=-Requere um propulsor capaz de realizar propulsão de combate cujo multiplicador seja maior que 1

TIOfficerTemplate.FleetMissionControl=-Reduz o custo de controle de missão da frota em {2}
TIOfficerTemplate.ShipMissionControl=-Reduz o custo de controle de missão da nave em {0}, no mínimo de 1
TIOfficerTemplate.OfficerPromotionChance=-Aumenta a chance de um oficial ser promovido após um evento motivo de promoção em {1}
TIOfficerTemplate.MissileTargeting=-Aumenta a chance de sistemas de mísseis anularem as CME inimigas em {1}
TIOfficerTemplate.MissileDamage=-Aumenta o dano explosivo, por perfuração e de fragmentação de mísseis em {3}
TIOfficerTemplate.BeamTargeting=-Aumenta a chance de sistemas de laser e de feixes de partículas anularem as CME inimigas em {1}
TIOfficerTemplate.BeamDamage=-Aumenta o dano de lasers e feixes de partículas em {3}
TIOfficerTemplate.BeamCooldown=-Reduz o tempo de recarga de armas de feixes em {2}
TIOfficerTemplate.GunTargeting=-Aumenta a chance de sistemas de armas magnéticas, de plasma e de projéteis anularem as CME inimigas em {1}
TIOfficerTemplate.GunDamage=-Aumenta o dano de armas magnéticas, de plasma e de projéteis em {3}
TIOfficerTemplate.MagWeaponCooldown=-Reduz o tempo de recarga de armas magnéticas em {2}
TIOfficerTemplate.PointDefenseCooldown=-Reduz o tempo de recarga de armas de defesa de ponto em {2}
TIOfficerTemplate.GlobalDamage=-Aumenta o dano de todas as armas, exceto de mísseis nucleares e de antimatéria, em {3}
TIOfficerTemplate.DamageControlSpeed=-Aumenta a velocidade na qual a equipe de resposta a danos conserta os sistemas e módulos da nave em {3}
TIOfficerTemplate.InternalDamageTaken=-Reduz o dano interno recebido pela nave em {1}
TIOfficerTemplate.DockRepairSpeed=-Aumenta a velocidade com que a nave é reparada em estaleiros em {3}
TIOfficerTemplate.DockResupplySpeed=-Aumenta a velocidade com que a nave é reabastecida em habitats em {3}
TIOfficerTemplate.Salvage=-Aumenta a quantidade de materiais recuperados pós-combate em {1}
TIOfficerTemplate.MaxTrajectoryDuration_Months=-Aumenta a duração máxima de uma trajetória em {0} meses
TIOfficerTemplate.GlobalTargeting=-Aumenta a capacidade de todas as armas anularem as CME inimigas em {1}
TIOfficerTemplate.GlobalWeaponCooldown=-Reduz o tempo de recarga de todas as armas em {2}
TIOfficerTemplate.ECM=-Aumenta o valor das CME da nave em {1}, o que reduz as chances inimigas de fazê-la de alvo
TIOfficerTemplate.BatteryRechargeRate=-Aumenta a velocidade de recarga da bateria da nave em {3}
TIOfficerTemplate.OfficerDeathChance=-Reduz a chance de mortes de oficiais em combate em {4}
TIOfficerTemplate.AssaultCombatValue=-Aumenta o valor de assalto da nave em {0}
TIOfficerTemplate.ShipDefectionChance=-A nave nunca irá desertar para outra facção
TIOfficerTemplate.DriveCombatThrustMultiplier=-Adiciona {0} ao multiplicador de empuxo de combate do propulsor da nave
TIOfficerTemplate.MaxSurvivableCombatAcceleration=-Aumenta a aceleração de combate máxima permitida na nave em {0} g(s)
TIOfficerTemplate.MaxSurvivableCruiseAcceleration=-Aumenta a aceleração de navegação máxima permitida na nave em {0} g(s)
TIOfficerTemplate.RadiationDamageReduction=-Reduz o dano de radiação provocado por armas de partícula em {2}
TIOfficerTemplate.NoDemotionOnTransfer=-Não perderá um nível com transferência à outra nave

TIOfficerTemplate.OfficerShipNameAndJob={0}: {1}, {2}			// ship name: rank + name, job
TIOfficerTemplate.OfficerNameAndJob={0}, {1}					// rank + name, job
TIOfficerTemplate.OfficerTypeAndRank={0}: {1}
TIOfficerTemplate.RequirementsHeader=Exigências da nave para promover categoria de oficial:
TIOfficerTemplate.PromotionHeader=Motivo de promoção:
TIOfficerTemplate.Bonuses=Bonificações:
TIOfficerTemplate.OfficersKilled=Oficiais mortos:
TIOfficerTemplate.KilledInAction=Morte em ação

TIOfficerTemplate.CompleteLongTrajectory=-A nave completa uma trajetória interplanetária           
TIOfficerTemplate.SurviveCombat=-A nave sobrevive a uma batalha espacial            
TIOfficerTemplate.WinCombat=-A nave faz parte do grupo vencedor em uma batalha espacial
TIOfficerTemplate.CombatKill=-A nave destrói uma nave inimiga ou módulo de combate durante uma batalha
TIOfficerTemplate.CombatKill_Guns=-A nave destrói uma nave inimiga ou módulo de combate durante uma batalha usando armas magnéticas, de plasma ou de projéteis                  
TIOfficerTemplate.CombatKill_Missiles=-A nave destrói uma nave inimiga ou módulo de combate durante uma batalha usando mísseis
TIOfficerTemplate.CombatKill_Beam=-A nave destrói uma nave inimiga ou módulo de combate durante uma batalha usando lasers ou canhões de partícula
TIOfficerTemplate.SuccessfulMarineAssault=-A nave participa em um assalto de fuzileiros exitoso
