UI.Codex.Title=Códex
UI.Codex.ListContainerHeader=Itens do códex
UI.Codex.DetailContainerHeader=Detalhes do códex
UI.Codex.codex_welcome.Title=Introdução 
UI.Codex.codex_welcome0=Este códex contém informações sobre a jogabilidade de Terra Invicta. Escolha um dos tópico à esquerda para ver detalhes sobre as mecânicas de jogo.<br/><br/>Tópicos podem surgir quando as tecnologias pesquisadas desbloquearem novas mecânicas.<br/><br/>Para ver informações mais detalhadas sobre como navegar pela interface do jogo, comece uma campanha jogando com a Resistência e ative a opção de tutorial.
UI.Codex.codex_factions.Title=Facções
UI.Codex.codex_factions0=Como as nações da Terra não foram capazes de entrar em consenso sobre como lidar com a chegada alienígena, facções transnacionais de pessoas que compartilham as mesmas visões de mundo acabaram surgindo nas sombras e se tornaram as principais jogadoras no tabuleiro global. Cada facção segue uma ideologia de abordagem às atividades alienígenas na Terra. Essas facções irão investir e tentar controlar os governos da Terra para avançar em seus objetivos. Você é líder de uma delas.
UI.Codex.codex_factions1=O círculo interno de liderança de cada facção é formado por seus respectivos <h>conselhos</h>. Os conselheiros realizarão missões para lhe ajudar a obter poder sobre as nações da Terra e a descobrir quais são os objetivos dos alienígenas. As facções também podem deter o controle sobre <h>exércitos</h> e, conforme a história avance, podem construir <h>habitats</h> e <h>frotas</h> no espaço.
UI.Codex.codex_factions2=As facções não podem ser completamente eliminadas em Terra Invicta, pois elas surgiram a partir de diferentes crenças da população terrestre. As pessoas podem ser influenciadas e estruturas organizacionais podem ser eliminadas, mas ideias não morrem. O que importa é quão poderosas são as pessoas que defendem essas ideologias.
UI.Codex.codex_objectives.Title=Objetivos
UI.Codex.codex_objectives0=Durante a campanha, cada facção terá um ou mais objetivos para cumprir a todo momento. Completar objetivos permitirá que você descubra informações sobre os alienígenas e seu verdadeiro propósito em nosso sistema solar. Os objetivos também podem desbloquear projetos de pesquisa e organizações especiais para uma facção.
UI.Codex.codex_resources.Title=Recursos
UI.Codex.codex_resources0=As facções precisam administrar vários recursos essenciais na Terra e, conforme a campanha avance, no espaço.
UI.Codex.codex_resources1=Os recursos terrestres são produzidos a partir de uma variedade de fontes, mas os recursos espaciais (água, voláteis, metais, metais nobres e físseis) só ficarão disponíveis com o desenvolvimento da tecnologia necessária para minerar corpos celestes que não sejam a Terra e com o uso de catapultas eletromagnéticas para lançá-los aonde são necessários.
UI.Codex.codex_resources2=Para facilitar a leitura, Terra Invicta utiliza letras junto a números muito grandes ou muito pequenos, como 10 M (10 mil). Letras maiúsculas serão usadas para números acima de 1.000.
UI.Codex.codex_resources3=M: Mil (1.000)
UI.Codex.codex_resources4=MM: Milhões (1.000.000)
UI.Codex.codex_resources5=B: Bilhões (1.000.000.000)
UI.Codex.codex_resources6=T: Trilhões (1.000.000.000.000)
UI.Codex.codex_resources7=Q: Quadrilhões (1.000.000.000.000.000)
UI.Codex.codex_resources8=Letras minúsculas serão usadas para números fracionados abaixo de 1:
UI.Codex.codex_resources9=m: milli- (0,001)
UI.Codex.codex_resources10=u: micro- (0,000 001)
UI.Codex.codex_resources11=n: nano- (0,000 000 001)
UI.Codex.codex_resources12=p: pico- (0,000 000 000 001)									// 1e-12
UI.Codex.codex_resources13=f: femto- (0,000 000 000 000 001)
UI.Codex.codex_resources14=a: atto- (0,000 000 000 000 000 001)
UI.Codex.codex_resources15=z: zepto- (0,000 000 000 000 000 000 001)
UI.Codex.codex_resources16=y: iocto- (0,000 000 000 000 000 000 000 001)
UI.Codex.codex_money.Title=Dinheiro
UI.Codex.codex_money0=<LOC,UI.GeneralControls.MoneyDetail>
UI.Codex.codex_money1=<LOC,UI.GeneralControls.MoneySource>
UI.Codex.codex_influence.Title=Influência
UI.Codex.codex_influence0=<LOC,UI.GeneralControls.InfluenceDetail>
UI.Codex.codex_influence1=<LOC,UI.GeneralControls.InfluenceSource>
UI.Codex.codex_ops.Title=Operações
UI.Codex.codex_ops0=<LOC,UI.GeneralControls.OpsDetail>
UI.Codex.codex_ops1=<LOC,UI.GeneralControls.OpsSource>
UI.Codex.codex_boost.Title=Propulsão
UI.Codex.codex_boost0=<LOC,UI.GeneralControls.BoostDetail>
UI.Codex.codex_boost1=<LOC,UI.GeneralControls.BoostSource>
UI.Codex.codex_missionControl.Title=Controle de missão
UI.Codex.codex_missionControl0=<LOC,UI.GeneralControls.MissionControlDetail>
UI.Codex.codex_missionControl1=O controle de missão é produzido principalmente por instalações na superfície da Terra, mas há algumas organizações e módulos de habitat que também produzem este recurso.
UI.Codex.codex_researchIncome.Title=Pesquisa
UI.Codex.codex_researchIncome0=<LOC,UI.GeneralControls.ResearchDetail>
UI.Codex.codex_researchIncome1=A pesquisa é produzida por nações, conselheiros, organizações e módulos de habitat. Muitos conselheiros, organizações e módulos de habitat oferecem bonificações para <h>categorias</h> específicas de pesquisa.
UI.Codex.codex_researchIncome2=A receita de pesquisa também recebe um bônus de acordo com a quantidade de pesquisas diferentes das quais sua facção esteja participando, então pode ser útil expandir suas iniciativas de pesquisa. Porém, bônus de categorias individuais podem ser reduzidos se você os estiver usando simultaneamente em vários projetos.
UI.Codex.codex_projectsIncome.Title=Projetos
UI.Codex.codex_projectsIncome0=O recurso de projetos representa a capacidade de uma facção em desenvolver objetivos ou resultados específicos.
UI.Codex.codex_projectsIncome1=Ele determina quantos projetos simultâneos ela pode executar e quão rapidamente pode terminá-los. As facções recebem uma janela de projeto de graça. Elas recebem uma segunda janela de projeto (que lhes permitirá trabalhar em dois projetos simultaneamente) se houver um conselheiro no comando de uma organização que receba produção de projeto. Uma terceira janela de projeto será aberta quando a facção construir um módulo de habitat que produza receita de projeto. As características dos conselheiros, assim como diversas organizações ou módulos de habitat que produzam receita de projeto concedem bonificações para todos os projetos sendo realizados pela facção.
UI.Codex.codex_water.Title=Água
UI.Codex.codex_water0=<LOC,UI.GeneralControls.WaterDetail>
UI.Codex.codex_volatiles.Title=Voláteis
UI.Codex.codex_volatiles0=<LOC,UI.GeneralControls.VolatilesDetail>
UI.Codex.codex_metals.Title=Metais
UI.Codex.codex_metals0=<LOC,UI.GeneralControls.BaseMetalsDetail>
UI.Codex.codex_nobleMetals.Title=Metais nobres
UI.Codex.codex_nobleMetals0=<LOC,UI.GeneralControls.NobleMetalsDetail>
UI.Codex.codex_fissiles.Title=Físseis
UI.Codex.codex_fissiles0=<LOC,UI.GeneralControls.FissilesDetail>
UI.Codex.codex_antimatter.Title=Antimatéria
UI.Codex.codex_antimatter0=<LOC,UI.GeneralControls.AntimatterDetail>
UI.Codex.codex_exotics.Title=Exóticos
UI.Codex.codex_exotics0=<LOC,UI.GeneralControls.ExoticsDetail>
UI.Codex.codex_diplomacy.Title=Diplomacia entre facções
UI.Codex.codex_diplomacy0=Ao usar a missão de <h>contato</h> em um conselheiro de outra facção, um conselheiro pode realizar negociações com o líder de outra facção. Negociações bem sucedidas podem servir para diminuir a hostilidade entre facções.
UI.Codex.codex_diplomacy1=Porém, todas as facções humanas acabam por ter ideologias incompatíveis e objetivos opostos. Quaisquer relações cordiais terminarão por ser passageiras, se muito.
UI.Codex.codex_councilors.Title=Conselheiros
UI.Codex.codex_councilors0=Os conselheiros são os principais representantes de uma facção na Terra, e também podem ir ao espaço para ajudar na realização dos objetivos da facção. Inicialmente, as facções podem ter quatro conselheiros, mas certos projetos permitirão que seu conselho tenha seis conselheiros no total. A função primária deles é realizar <h>missões</h> para a sua facção.
UI.Codex.codex_professions.Title=Profissões
UI.Codex.codex_professions0=A profissão de um conselheiro determina os valores iniciais de seus atributos, as missões que ele pode realizar e suas possíveis características. 
UI.Codex.codex_recruiting.Title=Recrutar
UI.Codex.codex_recruiting0=Os conselheiros são recrutados com influência. Você pode garantir que seu conselho tenha todos os tipos de missões disponíveis ao recrutar conselheiros que tenham diferentes profissões.
UI.Codex.codex_recruiting1=A janela de recrutas a conselheiros será atualizada no dia primeiro de cada mês, quando alguns candidatos deixam de fazer parte da lista.
UI.Codex.codex_attributes.Title=Atributos
UI.Codex.codex_attributes0=Um conselheiro tem oito atributos. Eles determinam as chances de sucesso nas missões ou oferecem bonificações às suas receitas.
UI.Codex.codex_attributes1=<color=#FFFFFFFF><sprite name="attribute_persuasion"></color> Persuasão<br/><LOC,UI.Councilor.PersuasionTip>
UI.Codex.codex_attributes2=<color=#FFFFFFFF><sprite name="attribute_investigation"></color> Investigação<br/><LOC,UI.Councilor.InvestigationTip>
UI.Codex.codex_attributes3=<color=#FFFFFFFF><sprite name="attribute_espionage"></color> Espionagem<br/><LOC,UI.Councilor.EspionageTip>
UI.Codex.codex_attributes4=<color=#FFFFFFFF><sprite name="attribute_command"></color> Comando<br/><LOC,UI.Councilor.CommandTip>
UI.Codex.codex_attributes5=<color=#FFFFFFFF><sprite name="attribute_administration"></color> Administração<br/><LOC,UI.Councilor.AdministrationTip>
UI.Codex.codex_attributes6=<color=#FFFFFFFF><sprite name="attribute_science"></color> Ciência<br/><LOC,UI.Councilor.ScienceTip>
UI.Codex.codex_attributes7=<color=#FFFFFFFF><sprite name="attribute_security"></color> Segurança<br/><LOC,UI.Councilor.SecurityTip>
UI.Codex.codex_attributes8=<color=#FFFFFFFF><sprite name="attribute_loyalty"></color> Lealdade<br/><LOC,UI.Councilor.LoyaltyTip>
UI.Codex.codex_traits.Title=Característica
UI.Codex.codex_traits0=As características são os traços natos de um conselheiro. Elas podem conceder bonificações ou penalidades de caráter permanente ou condicional, conceder receitas ou acesso a certas organizações. Algumas características podem ser eliminadas ou promovidas com EXP.
UI.Codex.codex_augmentations.Title=Implantes
UI.Codex.codex_augmentations0=Os implantes cibernéticos são melhoras que um conselheiro pode obter. Eles funcionam de forma similar às características.
UI.Codex.codex_XP.Title=Experiência
UI.Codex.codex_XP0=<LOC,UI.Councilor.XPTooltip>
UI.Codex.codex_orgs.Title=Organizações
UI.Codex.codex_orgs0=As organizações são agências governamentais, empresas privadas e sindicatos criminais que podem ser controlados por um conselheiro. As organizações podem conceder receitas, bonificações aos atributos, novas missões e bonificações às prioridades de investimento que as facções mantêm em nações. As organizações são divididas em níveis de 1 a 3 (representados pelo número de estrelas presentes no ícone da organização). Os conselheiros podem administrar um nível de organização por ponto de seu atributo de administração.
UI.Codex.codex_orgs1=A maioria das organizações fica disponível no mercado exclusivo de uma facção e, após algum tempo, é alternada e ficará disponível no mercado de outra facção. As organizações podem ser compradas usando dinheiro, influência e, às vezes, operações ou propulsão. Elas também podem ser adquiridas com missões de aquisição hostil ou durante negociações com outras facções. As facções podem obter organizações especiais ao completar objetivos ou durante eventos. 
UI.Codex.codex_orgs2=As organizações que tenham um valor em dinheiro podem ser vendidas de volta para o mercado. As facções têm uma janela de organizações não designadas que pode ser usada para transferir as organizações entre os conselheiros.
UI.Codex.codex_orgs3=As organizações na janela de seleção de uma facção não conferem nenhum benefício à facção, mas as que tenham produções negativas continuarão a custar os recursos necessário para mantê-las. Uma facção pode ter no máximo 10 organizações em sua janela de seleção, com exceção às organizações especiais da facção. O restante deverá ser vendido ou transferido para que fique sob controle direto de um conselheiro.
UI.Codex.codex_orgs4=As organizações recém atribuídas a um conselheiro não ativarão suas bonificações até a próxima fase de missões, exceto pelos bônus de administração para que seja possível calcular a capacidade controlar organizações de um conselheiro. Se um conselheiro for detido, todas as organizações administradas por ele ficarão inativas.
UI.Codex.codex_missions.Title=Missões
UI.Codex.codex_missions0=Periodicamente, o jogo entrará na fase de missões, durante a qual todas as facções enviarão seus conselheiros a missões secretamente. As missões serão resolvidas a seguir durante os próximos dias ou semanas. Enquanto que algumas são bem sucedidas automaticamente, a maioria é contestada e será necessário fazer uma rolagem de dados. As missões normalmente têm como alvo nações, regiões, pontos de controle, instalações espaciais e outros conselheiros.
UI.Codex.codex_missions1=Entre as fases de missões, as missões serão resolvidas em uma ordem parcialmente predeterminada, indicada pelo número de relógios visíveis na descrição da missão. As missões defensivas e não contestadas serão acionadas antes de missões contestadas. Quando dois conselheiros estão tentando realizar a mesma missão, aquele que tiver a maior chance de sucesso irá primeiro.
UI.Codex.codex_missions2=Para as missões contestadas, a chance de sucesso é determinada através da soma de todos as bonificações e penalidades relevantes para essa missão em particular, e a facção mandante pode gastar recursos para melhorar as chances de sucesso. Se as bonificações e penalidades somarem zero, a chance de sucesso é de 50%. De outra forma, cada ponto de cada tipo tem um impacto de potência decrescente no resultado. Mudanças nas condições da Terra modem modificar as chances de sucesso entre a fase de designação de missões e a resolução das missões.
UI.Codex.codex_missions3=Quando uma missão contestada é resolvida, um número aleatório entre 0 e 100 é gerado: se ele for menor ou igual à chance de sucesso, a missão será um sucesso, se não, a missão fracassará. Resultados abaixo dos 10% da chance de sucesso serão um sucesso crítico, que normalmente oferece bonificações maiores do que um sucesso comum. Resultados dentro dos 10% dos possíveis fracassos são uma falha crítica e terão consequências piores.
UI.Codex.codex_missionList.Title=Lista de missões
UI.Codex.codex_missionList0=Estas são as missões disponíveis aos conselheiros humanos em Terra Invicta. 
UI.Codex.codex_missionList_alien.Title=Lista de missões alienígenas
UI.Codex.codex_missionList_alien0=Durante a campanha, as facções descobrirão detalhes sobre as atividades alienígenas na Terra. Essa lista crescerá conforme mais conhecimento sobre missões alienígenas ou missões relacionadas a eles seja revelado.
UI.Codex.codex_detection.Title=Vigilância
UI.Codex.codex_detection0=Realizar missões atrai certa atenção, a depender da missão em si e de seu resultado. Conselheiros que tenham o atributo de espionagem alto e estejam em nações onde sua facção tem pontos de controle não serão detectados com facilidade, enquanto que facções nas quais os conselheiros tenham pontuações altas de investigação têm mais chances de detectar conselheiros inimigos. Realizar uma missão de monitorar local faz com que seja mais fácil detectar conselheiros de outras facções em uma região ou um habitat específicos.
UI.Codex.codex_detection1=Alguns conselheiros podem ser detectados, mas não perfeitamente identificados. Realizar uma missão de <h>investigar conselheiro</h> contra um conselheiro específico lhe dará mais informações sobre ele.
UI.Codex.codex_detection2=Se você acha que seus próprios conselheiros foram detectados, a missão de <h>ocultamento</h> fará com que seja muito mais difícil segui-los.
UI.Codex.codex_nations.Title=Nações
UI.Codex.codex_nations0=As nações da Terra servem como campos de batalha para os desígnios alienígenas no planeta, e são locais de conflitos tanto políticos quanto militares. As facções humanas, através de seus conselheiros e exércitos, competirão para controlar as nações e seus recursos para que possam alcançar seus objetivos. 
UI.Codex.codex_nations1=A maioria das nações em Terra Invicta corresponde a países reais da Terra, porém, em vários casos, grupos de pequenas nações adjacentes foram agregados para formar uma única nação e, assim, serem mais relevantes para a escala do jogo. Quaisquer conflitos entre essas nações geralmente estão abaixo da escala desta simulação. As facções trabalham como investidores ocultos e, com determinação suficiente, elas podem assumir o controle da economia e das políticas estrangeiras de uma nação.
UI.Codex.codex_regions.Title=Regiões
UI.Codex.codex_regions0=As nações são compostas de uma ou mais regiões. As regiões recebem seus nomes de acordo com a principal cidade em sua área. A função das regiões é principalmente geográfica, não política; elas existem para marcar os locais de instalações críticas e exércitos. Quando novas nações se formam ou as já existentes mudam, elas serão compostas pelas regiões de outras nações. 
UI.Codex.codex_regions1=As instalações espaciais também serão divididas de acordo com as regiões: são bases de lançamento que conferem propulsão, instalações de controle de missão e, em fases mais avançadas do jogo, defesas superfície-órbita.
UI.Codex.codex_regions2=Os exércitos lutarão e ocuparão as regiões durante as guerras.
UI.Codex.codex_regions3=Quando os conselheiros se movem pela Terra, eles estarão localizados em regiões e podem ser detectados nesses locais, mas grande parte do trabalho de um conselheiro é realizada em nível nacional.
UI.Codex.codex_regions4=As regiões podem ser <h>montanhosas</h>, o que significa que os exércitos levarão mais tempo para atravessá-las e os exércitos de defesa terão uma vantagem considerável durante as batalhas. As regiões costeiras servem como pontos de partida e chegada para os exércitos que tenham a melhora de marinha. As regiões que estejam sobre ou perto da linha do equador ganharão mais propulsão por uma certa quantia de investimento, pois os foguetes lançados podem aproveitar melhor a velocidade de rotação da Terra nessa área.
UI.Codex.codex_claims.Title=Reivin.
UI.Codex.codex_claims0=Algumas nações reivindicam regiões que não lhes pertencem. São regiões que elas podem adquirir através de guerras ou movimentos de secessão.
UI.Codex.codex_claims1=Alguns projetos de ciência social podem desbloquear novas reivindicações durante a campanha.
UI.Codex.codex_controlPoints.Title=Pontos de controle
UI.Codex.codex_controlPoints0=<LOC,UI.Nation.ControlPointDescription>
UI.Codex.codex_controlPoints1=Há variados tipos de ponto de controle. Os tipos dependem do governo nacional e de outras condições, e conferem bonificações relacionadas à facção que os controla. O mais importante é o ponto de controle <h>executivo</h>, que garante a seu dono o comando sobre as políticas estrangeiras da nação.
UI.Codex.codex_controlPoints2=Certas políticas poderosas, como a capacidade de se juntar ou sair de federações, exigem um controle <h>consolidado</h> sobre o executivo, o que significa que a facção executiva ganhou o controle da nação através de uma guerra ou revolução, ou que já domina continuamente o ponto de controle executivo há um certo tempo.
UI.Codex.codex_controlPoints3=<LOC,UI.Nation.ControlPointCost>
UI.Codex.codex_incomes.Title=Receitas
UI.Codex.codex_incomes0=As nações produzem dinheiro, pesquisa, propulsão e controle de missão proporcionalmente para facções que tenham seus pontos de controle. Investir em várias <h>prioridades</h> aumentará a quantidade de recursos conferidos a todas as facções.
UI.Codex.codex_nationStats.Title=Atributos das nações
UI.Codex.codex_nationStats0=A prosperidade e a estabilidade das nações da Terra, já delicadas em vários locais, ficaram ainda mais sobrecarregadas em vista da chegada alienígena. Essas circunstâncias são registradas e mostradas aos jogadores, que podem tomar diversas providências para modificá-las. Os valores essenciais a nível nacional e suas respectivas funções são:
UI.Codex.codex_nationStats1=<color=#FFFFFFFF><sprite name="gov_type"></color> Governo<br/><LOC,UI.Nation.DemocracyHelp1>
UI.Codex.codex_nationStats2=<color=#FFFFFFFF><sprite name="nation_unrest"></color> Agitação<br/><LOC,UI.Nation.UnrestHelp1>
UI.Codex.codex_nationStats3=<color=#FFFFFFFF><sprite name="per_capita_GDP"></color> PIB e PIB per capita<br/><LOC,UI.Nation.GDPHelp1>
UI.Codex.codex_nationStats4=<LOC,UI.Nation.PerCapitaGDPHelp1>
UI.Codex.codex_nationStats5=<color=#FFFFFFFF><sprite name="army_level"></color> Tecnologia militar<br/><LOC,UI.Nation.MiltechHelp1>
UI.Codex.codex_nationStats6=<color=#FFFFFFFF><sprite name="education"></color> Educação<br/><LOC,UI.Nation.EducationHelp1>
UI.Codex.codex_nationStats7=<color=#FFFFFFFF><sprite name="culture"></color> Coesão<br/><LOC,UI.Nation.CohesionHelp1>
UI.Codex.codex_nationStats8=<color=#FFFFFFFF><sprite name="inequality"></color> Desigualdade<br/><LOC,UI.Nation.InequalityHelp1>
UI.Codex.codes_nationStats9=<color=#FFFFFFFF><sprite name="greeneconomy_orange"></color>Sustentabilidade econômica<br/><LOC,UI.Nation.SustainabilityHelp1>
UI.Codex.codex_publicOpinion.Title=Opinião pública
UI.Codex.codex_publicOpinion0=Todos os povos na Terra têm uma opinião em particular sobre a chegada alienígena. Mas as pessoas são maleáveis: eventos e propagandas podem convencê-las sobre um ponto de vista diferente.
UI.Codex.codex_publicOpinion1=Esses pontos de vista se alinham com as ideologias de cada facção, assim como uma opinião "indecisa" entre elas. As ideologias estão posicionadas em relação às demais: quando os eventos apresentam a possibilidade de mudar a opinião de alguém, eles tipicamente a converterão para uma opinião próxima. Por exemplo, é possível que um partidário da Resistência passe a ter visões mais radicais e apoie a Primazia Humana, ou abrande sua opinião e fique indeciso.
UI.Codex.codex_publicOpinion2=Ter apoio público para a sua facção é uma ótima fonte de influência. Você também receberá bonificações durante missões realizadas em nações onde grande parte do público esteja do seu lado.
UI.Codex.codes_publicOpinion3=Algo que pode transformar a opinião pública são as atrocidades cometidas por uma facção. Atrocidades são ações que causam sofrimento ou mortes em massa, e as facções responsáveis perdem partidários como resultado. As atrocidades são cumulativas: conforme uma facção continue a cometê-las, mais drasticamente a penalidade na opinião pública aumentará.
UI.Codex.codex_priorities.Title=Prioridades nacionais
UI.Codex.codex_priorities0=Os pontos de investimento representam um excedente no capital econômico gerado por uma nação. Cada nação gera um certo número de pontos de investimento baseado no tamanho de sua economia menos seu nível de agitação e a quantidade de exércitos que possui. As <h>prioridades</h> de uma nação controlam a distribuição desses pontos de investimento. O proprietário de cada ponto de controle pode direcionar parte dos pontos de investimento a quaisquer prioridades que queira.
UI.Codex.codex_priorities1=Os investimentos são distribuídos em certo peso para cada prioridade (0, 1, 2 ou 3), e a quantidade de investimento direcionada a uma prioridade específica depende do total de pesos determinados para um ponto de controle específico.
UI.Codex.codex_priorities2=Os pontos de investimento gradualmente enchem os contadores de cada prioridade. Quando cheios, a nação recebe os efeitos daquela prioridade e, na maioria dos casos, o contador pode ser preenchido novamente.
UI.Codex.codex_priorities3=Você também pode criar e salvar "modelos de prioridade", que são um detalhamento pré-definido dos pontos de investimento. Eles podem ser aplicados rapidamente a qualquer nação na qual você tenha pontos de controle. Você pode designar qualquer modelo como o padrão a ser aplicado a novos pontos de controle.
UI.Codex.codex_priorities4=As facções também podem investir diretamente com dinheiro, influência e operações nas prioridades das nações de sua escolha. Assim é possível acelerar a criação de exércitos, bases de lançamento e outros ativos. Porém, uma nação só pode receber uma certa quantidade de investimento direto por ano.
UI.Codex.codex_priority_economy.Title=Economia
UI.Codex.codex_priority_economy0=<LOC,UI.Nation.EconomyPriorityGeneric>
UI.Codex.codex_priority_welfare.Title=Bem-Estar
UI.Codex.codex_priority_welfare0=<LOC,UI.Nation.WelfarePriorityGeneric>
UI.Codex.codex_priority_environment.Title=Ambiente
UI.Codex.codex_priority_environment0=<LOC,UI.Nation.EnvironmentPriorityGeneric>
UI.Codex.codex_priority_knowledge.Title=Conhecimento
UI.Codex.codex_priority_knowledge0=<LOC,UI.Nation.KnowledgePriorityGeneric>
UI.Codex.codex_priority_government.Title= Governo
UI.Codex.codex_priority_government0=<LOC,UI.Nation.GovernmentPriorityGeneric>
UI.Codex.codex_priority_unity.Title=Unidade
UI.Codex.codex_priority_unity0=<LOC,UI.Nation.UnityPriorityGeneric>
UI.Codex.codex_priority_foundMilitary.Title=Formar exército
UI.Codex.codex_priority_foundMilitary0=<LOC,UI.Nation.Military_FoundMilitaryPriorityGeneric>
UI.Codex.codex_priority_military.Title=Militar
UI.Codex.codex_priority_military0=<LOC,UI.Nation.MilitaryPriorityGeneric>
UI.Codex.codex_priority_oppression.Title=Opressão
UI.Codex.codex_priority_oppression0=<LOC,UI.Nation.OppressionPriorityGeneric>
UI.Codex.codex_priority_spoils.Title=Espólios
UI.Codex.codex_priority_spoils0=<LOC,UI.Nation.SpoilsPriorityGeneric>
UI.Codex.codex_priority_funding.Title=Financiamento
UI.Codex.codex_priority_funding0=<LOC,UI.Nation.FundingPriorityGeneric>
UI.Codex.codex_priority_spaceflight.Title=Prog. de viagem espacial
UI.Codex.codex_priority_spaceflight0=<LOC,UI.Nation.Civilian_InitiateSpaceflightProgramPriorityGeneric>
UI.Codex.codex_priority_launchFacilities.Title=Propulsão
UI.Codex.codex_priority_launchFacilities0=<LOC,UI.Nation.LaunchFacilitiesPriorityGeneric>
UI.Codex.codex_priority_missionControl.Title=Controle de missão
UI.Codex.codex_priority_missionControl0=<LOC,UI.Nation.MissionControlPriorityGeneric>
UI.Codex.codex_priority_buildArmy.Title=Formar exército
UI.Codex.codex_priority_buildArmy0=<LOC,UI.Nation.Military_BuildArmyPriorityGeneric>
UI.Codex.codex_priority_sealift.Title=Formar marinha
UI.Codex.codex_priority_sealift0=<LOC,UI.Nation.Military_SealiftPriorityGeneric>
UI.Codex.codex_priority_initiateNuclearProgram.Title=Desenvolver arma nuclear
UI.Codex.codex_priority_initiateNuclearProgram0=<LOC,UI.Nation.Military_InitiateNuclearProgramPriorityGeneric>
UI.Codex.codex_priority_nuclearWeapons.Title=Construir armas nucleares
UI.Codex.codex_priority_nuclearWeapons0=<LOC,UI.Nation.Military_BuildNuclearWeaponsPriorityGeneric>
UI.Codex.codex_priority_spaceDefenses.Title=Defesas espaciais
UI.Codex.codex_priority_spaceDefenses0=<LOC,UI.Nation.Military_BuildSpaceDefensesPriorityGeneric>
UI.Codex.codex_priority_buildSTOSquadron.Title=Construir caça orbital
UI.Codex.codex_priority_buildSTOSquadron0=<LOC,UI.Nation.Military_BuildSTOSquadronPriorityGeneric>
UI.Codex.codex_priority_coreEcoUpgrade.Title=<color=#FFFFFFFF><sprite name=build_core_economic_region></color> Nova região econômica primária
UI.Codex.codex_priority_coreEcoUpgrade0=<LOC,UI.Nation.Civilian_CoreEcoUpgradePriorityGeneric>
UI.Codex.codex_priority_coreMineralUpgrade.Title=<color=#FFFFFFFF><sprite name=build_core_mining_region></color> Nova região mineral
UI.Codex.codex_priority_coreMineralUpgrade0=<LOC,UI.Nation.Civilian_CoreMineralUpgradePriorityGeneric>
UI.Codex.codex_priority_coreOilUpgrade.Title=<color=#FFFFFFFF><sprite name=build_core_oil_region></color> Nova região petrolífera
UI.Codex.codex_priority_coreOilUpgrade0=<LOC,UI.Nation.Civilian_CoreOilUpgradePriorityGeneric>
UI.Codex.codex_priority_decolonizeRegion.Title=<color=#FFFFFFFF><sprite name=decolonize_region></color> Descolonizar região
UI.Codex.codex_priority_decolonizeRegion0=<LOC,UI.Nation.Civilian_DecolonizeRegionPriorityGeneric>
UI.Codex.codex_priority_decontaminateRegion.Title=<color=#FFFFFFFF><sprite name=decontaminate></color> Descontaminar região
UI.Codex.codex_priority_decontaminateRegion0=<LOC,UI.Nation.Civilian_DecontaminateRegionPriorityGeneric>
UI.Codex.codex_relations.Title=Relações internacionais
UI.Codex.codex_relations0=As nações que não estejam em guerra podem ser aliadas, ser rivais ou ter relações normais.
UI.Codex.codex_relations1=Os aliados com capacidade de guerrear (aqueles que têm exércitos ou armas nucleares) se juntarão a guerras para defender uns aos outros quando forem atacados. Os aliados também podem mover exércitos entre suas regiões durante tempos de guerra ou de paz. Os aliados de qualquer nação de qualquer dos lados podem se juntar a uma guerra depois que ela seja iniciada, contanto que isso não provoque um conflito de alianças com membros do outro lado da disputa.
UI.Codex.codex_relations2=Nações rivais podem entrar em guerra umas com as outras através da missão de definir diretiva nacional disponível aos conselheiros. As nações humanas normalmente sofrerão com perda de coesão quando declararem guerra a um novo rival.
UI.Codex.codex_relations3=As facções podem gastar influência <color=#FFFFFFFF><sprite name="influence"></color> em nações nas quais tenham o ponto de controle executivo para mudar suas relações bilaterais com outras nações. Qualquer ação que melhore relações, seja passando do estado de rivais a relações normais ou de relações normais para aliados, exige o consentimento da outra nação. Ações que melhorem relações também ativam um período de espera antes que as nações possam melhorar suas relações novamente.
UI.Codex.codex_relations4=Há algumas restrições sobre quem pode se tornar um aliado ou um rival. Duas nações não adjacentes uma a outra com apenas um ponto de controle não podem formar alianças ou rivalidades a menos que uma delas também tenha uma marinha. As nações aliadas a uma nação separatista não podem se aliar à nação de origem dela e aliados da nação de origem não podem se aliar à separatista.
UI.Codex.codex_relations5=As nações também ganham coesão por ter "companheiras" ou rivais mais fortes com no mínimo um ponto de controle a menos do que elas. As nações democráticas com uma pontuação de governo de 6 ou mais só ganham este bônus de nações rivais não democráticas.
UI.Codex.codex_federations.Title=Federações
UI.Codex.codex_federations0=<LOC,UI.Nation.FederationTooltipDetail>
UI.Codex.codex_policies.Title=Diretivas
UI.Codex.codex_policies0=As diretivas são ações que a facção executiva de uma nação pode tomar para alterar dramaticamente o curso da nação. Um conselheiro pode usar a missão de <h>definir diretiva nacional</h> para decretar políticas. As possíveis diretivas incluem:
UI.Codex.codex_terrestrialWarfare.Title=Guerra terrestre
UI.Codex.codex_terrestrialWarfare0=Uma guerra começa quando um conselheiro de uma facção que possua poder executivo sobre certa nação usa a diretiva de guerra nessa nação contra uma nação rival. Todos os aliados com capacidade de guerrear da nação rival (ou seja, aliados que tenham exércitos ou armas nucleares) se juntarão à guerra. Todos os aliados com capacidade de guerrear do atacante têm a opção de se juntar ou não à guerra.
UI.Codex.codex_terrestrialWarfare1=Para vencer uma guerra, um exército deve ocupar a região capital da nação inimiga. Nesse momento, a guerra chegará ao fim e causará um evento de mudança de regime. Regiões reivindicadas serão entregues ao ocupante e a seus aliados. Se parte da nação invadida ainda resistir, os proprietários de seus pontos de controle serão substituídos por representantes da facção vencedora. Alguns dos atributos da nação são alterados quando um novo regime se instala, às vezes de forma imprevisível, mas a nova facção governante poderá fazer investimentos diretos nessa nação sem pagar seu custo de influência durante o período de um ano. Regiões não ocupadas e exércitos inimigos sobreviventes causarão uma maior agitação após uma mudança de regime.
UI.Codex.codex_terrestrialWarfare2=Os exércitos também podem anexar regiões inimigas durante uma guerra se sua nação de origem tiver uma reivindicação sobre a região alvo, mas qualquer combate na região irá interromper e cancelar a tentativa de anexação. As guerras também podem simplesmente terminar em paz, e ambos os lados voltarão ao estado em que estavam antes da guerra.
UI.Codex.codex_armies.Title=Exércitos
UI.Codex.codex_armies0=Os exércitos representam múltiplas divisões modernas capazes de conquistar e assegurar territórios em outras nações. O controle de um exército é obtido depois que os conselheiros obtêm o controle, ao menos parcial, de uma nação. A maioria das nações não possui exércitos no início da campanha, mas as nações que tenham população o bastante podem criar novos exércitos com investimentos. Embora poderosos, os exércitos são um peso para o desenvolvimento econômico da nação e permanecem sujeitos às relações internacionais de seus países de origem. Essas relações também podem ser administradas ao se ter controle suficiente sobre uma nação.
UI.Codex.codex_armies1=O quartel-general de um exército é uma das regiões de sua nação de origem. Quando posicionado em seu quartel-general, o exército terá um impacto menor em custos ao desenvolvimento econômico da nação.
UI.Codex.codex_armies2=Os exércitos dependem de dois valores fundamentais: o nível de tecnologia militar de sua nação de origem e a sua força. A força mede quanto dano o exército já recebeu. 
UI.Codex.codex_armies3=Exércitos que receberam dano se recuperam mais rápido quando estão em qualquer região amiga sem combates, se recuperam mais rápido dentro das fronteiras de sua nação de origem e ainda mais rápido em sua região de origem. Os exércitos se recuperam mais lentamente se a nação estiver trabalhando na recuperação de vários exércitos ao mesmo tempo.
UI.Codex.codex_armies4=Alguns exércitos possuem a melhora de <h>marinha</h> que os permite mover-se pelos oceanos. Durante as guerras, as marinhas de uma nação só podem cruzar os oceanos se sua nação de origem tiver superioridade naval sobre seus inimigos. Apenas as nações maiores ou mais ricas têm a capacidade de formar e exercer sua autoridade com marinhas.
UI.Codex.codex_armies5=Quando um exército é destruído, sua nação de origem recebe pontos de investimento em sua prioridade de formar exército para representar a reconstrução do exército com sobreviventes da unidade anterior. A destruição de um exército com uma marinha também confere pontos de investimento à prioridade de formar marinha de sua nação de origem.
UI.Codex.codex_armyOperations.Title=Operações com exércitos
UI.Codex.codex_armyOperations0=Uma facção no controle de um exército pode utilizá-lo para realizar certas operações, sendo elas:
UI.Codex.codex_armyBattles.Title=Batalhas entre exércitos
UI.Codex.codex_armyBattles0=Se pelo menos dois exércitos inimigos estiverem na mesma região, eles irão lutar. Quanto as mecânicas do combate, cada exército será atacado uma vez por dia. Suas chances de atingir o exército inimigo com sucesso se baseiam em seu nível de tecnologia militar, sua força, se há algum conselheiro emprestando seu atributo de comando à nação de origem do exército através da missão de assessoria, se o exército está defendendo ou atacando a região e se a região é montanhosa.
UI.Codex.codex_armyBattles1=Se um exército estiver em uma região inimiga e não houver exércitos inimigos presentes, ele começará a ocupar a região enfrentando as defesas locais (que usam o nível de tecnologia da nação) e recebendo o dano causado por elas. Os exércitos que tenham recebido danos graves tentarão fugir para um local seguro sem que você interfira, mas eles também podem ser completamente destruídos quando sua força chegar a zero.
UI.Codex.codex_armyBattles2=Se uma região estiver completamente ocupada, as lutas serão interrompidas, mas ela não mudará de lado até que a guerra esteja terminada. As economias regionais e instalações espaciais podem ser gravemente danificas durante as lutas, embora a taxa de dano abaixe proporcionalmente ao aumento do nível de tecnologia militar (para representar o uso de armas mais precisas). Causar dano demasiado contará como uma atrocidade causada pela facção proprietária do exército.
UI.Codex.codex_navalSuperiority.Title=Superioridade naval
UI.Codex.codex_navalSuperiority0=<LOC,UI.Nation.NavalDetail>
UI.Codex.codex_navalSuperiority1=Atenção, pois bloqueios navais não impedirão que exércitos que já estejam no mar alcancem seus respectivos destinos.
UI.Codex.codex_navalSuperiority2=Mesmo com liberdade nos mares ou superioridade naval, os exércitos que estejam sendo transportados pelo mar não poderão passar pelos canais do Panamá ou de Suez se estiverem em guerra com a nação que controla essas regiões e essas regiões não estiverem ocupadas. Qualquer viagem marinha tardará mais enquanto as frotas buscam rotas alternativas.
UI.Codex.codex_nuclearWarfare.Title=Guerra nuclear
UI.Codex.codex_nuclearWarfare0=Algumas nações têm uma certa quantidade de ataques nucleares disponíveis a elas. Esse valor representa a capacidade de lançar múltiplos ataques nucleares contra uma região alvo. Lançar ataques nucleares devastará a economia de uma região e os exércitos inimigos que estejam no local, porém o ataque será parcialmente amenizado se a nação estiver atacando seu próprio território ou território aliado. As facções atacantes serão acusadas por cometer uma ou mais atrocidades. Detonar uma certa quantidade de armas nucleares também pode ter efeitos globais desastrosos.
UI.Codex.codex_nuclearWarfare1=Completar a prioridade de armas nucleares pode conceder mais ataques nucleares a uma nação.
UI.Codex.codex_nuclearWarfare2=As nações criam armas nucleares como uma forma de defesa contra invasões inimigas. Tentar conquistar uma nação que esteja armada com bombas nucleares é quase uma certeza de receber um contra-ataque nuclear em resposta.
UI.Codex.codex_solarSystem.Title=Sistema solar
UI.Codex.codex_solarSystem0=Terra Invicta simula os corpos celestes maiores do sistema solar terrestre, abarcando uma distância de aproximadamente 50x a distância entre a Terra e o Sol. Isso inclui grande parte do cinturão de Kuiper, o grupo de corpos gelados que orbitam além de Netuno.
UI.Codex.codex_solarSystem1=O sistema solar também inclui pontos de Lagrange dentre as áreas para as quais as frotas podem se deslocar. Eles são pontos de ancoragem estáveis criados pela confluência de gravidade entre dois corpos, e estão marcados no mapa com formas geométricas.
UI.Codex.codex_orbits.Title=Órbitas
UI.Codex.codex_orbits0=Todos os corpos celestes e pontos de Lagrange têm uma ou mais órbitas circulares em volta deles nos quais as facções podem mover suas frotas e construir uma quantidade limitada de estações espaciais. As frotas não precisam de qualquer tipo de propelente para permanecer na posição em que estiverem em uma órbita.
UI.Codex.codex_orbits1=As órbitas próximas à superfície de um corpo celeste são chamadas de órbitas <h>adjacentes</h>. Essas são as órbitas para as quais as frotas podem se deslocar para aterrissar ou para bombardear alvos na superfície. Em volta da Terra, alguns dos módulos de habitat conferem bonificações se estiverem em uma órbita adjacente, pois podem conceder benefícios melhores para a superfície.
UI.Codex.codex_orbits2=Normalmente, é necessário usar menos Delta-V nas órbitas de maior altitude para realizar os lançamentos necessários para chegar a outras luas e sistemas planetários.
UI.Codex.codex_orbits3=Algumas órbitas têm a marca de um símbolo de perigo <color=#FFFFFFFF><sprite name=irradiated_site></color>. Essas órbitas recebem altos níveis de radiação e as estações espaciais construídas nesses locais precisarão de escudos, além de serem muito mais pesadas e caras do que as estações construídas em outros locais.
UI.Codex.codex_orbits4=Algumas órbitas também produzem pequenas quantidades de <color=#FFFFFFFF><sprite name="antimatter"></color>antimatéria que pode ser coletada com certos módulos de habitat.
UI.Codex.codex_habSites.Title=Áreas de habitat e mineração
UI.Codex.codex_habSites0=Com exceção do planeta infernal que é Vênus e os gigantes gasosos (Júpiter, Saturno Urano e Netuno), todos os corpos celestes têm pelo menos uma área de habitat na qual as facções podem construir uma base com uma mina e outros módulos. Corpos maiores terão múltiplos locais, cuja quantidade dependerá do tamanho geral do corpo.
UI.Codex.codex_habSites1=Após a construção de uma mina, uma área de habitat proverá certos recursos espaciais à facção no controle das instalações. Os tipos de recursos disponíveis geralmente dependerão da composição do corpo celeste.
UI.Codex.codex_habSites2=Quando estiverem explorando o sistema solar pela primeira vez, as facções só terão estimativas sobre quais recursos espaciais uma mina em uma certa área de habitat pode oferecer. Para descobrir seu potencial com precisão, será necessário prospectar o corpo celeste.
UI.Codex.codex_habSites3=Algumas áreas de habitat têm a marca de um símbolo de perigo <color=#FFFFFFFF><sprite name=irradiated_site></color>. Esses locais recebem altos níveis de radiação e as bases construídas sobre eles precisarão de escudos, além de serem muito mais pesadas e mais caras do que as bases construídas em outros locais.
UI.Codex.codex_habSites4=Se construirmos uma rede de minas e catapultas grande o suficiente, teremos que pagar <color=#FFFFFFFF><sprite name="mission_control"></color> adicional para administrá-la. A quantidade de minas "grátis" aumenta quando certas pesquisas de tecnologias globais relacionadas a ciência espacial são concluídas.
UI.Codex.codex_probes.Title=Prospectando
UI.Codex.codex_probes0=Para construir uma base, uma facção deve primeiramente prospectar o corpo celeste para determinar um local preciso para o habitat. Inspecionar o corpo celeste também revelará qual sua será sua produção exata de mineração.
UI.Codex.codex_probes1=Uma prospecção pode ser realizada por uma sonda que seja lançada da Terra ou de um estaleiro em um habitat, ou por naves equipadas com um módulo de laboratório de ciência espacial. As informações obtidas através de prospecções podem ser roubadas por outras facções.
UI.Codex.codex_research.Title=Pesquisa
UI.Codex.codex_research0=Em Terra Invicta, o processo de pesquisa está dividido entre ciência e engenharia. As facções devem decidir como gerenciar sua receita de pesquisa <color=#FFFFFFFF><sprite name="research"></color> entre iniciativas públicas, que avançarão o entendimento da humanidade sobre o universo, e iniciativas privadas, que servirão para concluir objetivos específicos ou para melhorar as habilidades da facção.
UI.Codex.codex_research1=As facções humanas pesquisam coletivamente três novos princípios científicos de cada vez. Eles dizem respeito a certos entendimentos amplos sobre o funcionamento de elementos da física, da química ou das sociedades, por exemplo. Eles raramente causarão alguma mudança específica direta sobre o progresso de eventos no jogo. Em vez disso, sua função principal é desbloquear projetos de engenharia para as facções individualmente.
UI.Codex.codex_research2=A facção que mais contribuir para a pesquisa de um princípio em particular escolherá o que será pesquisado em seguida. Contribuir para a pesquisa também aumenta a chance de uma facção de desbloquear projetos relacionados àquela tecnologia.
UI.Codex.codex_research3=Com infraestrutura o suficiente, as facções podem pesquisar até três projetos privados de engenharia ao mesmo tempo. Os projetos geralmente irão habilitar um novo efeito ou desbloquear um novo componente para suas naves e habitats. Um exemplo de princípio científico pode ser a "doutrina de armas de energia dirigida", que é um dos pré-requisitos para o projeto de "bateria de laser infravermelho de 60 cm", que por sua vez desbloqueia um novo sistema de armas para as naves.
UI.Codex.codex_projects.Title=Projetos
UI.Codex.codex_projects0=Nem todas as facções têm acesso a todos os projetos. Cada projeto tem uma porcentagem de chance de aparecer para cada facção. Enquanto que certos projetos essenciais estarão sempre disponíveis para todas as facções, muitos deles aparecerão apenas para algumas delas, e é possível que algumas tecnologias não essenciais não apareçam durante uma campanha, simulando que é incerto se algumas ideias do mundo real realmente poderiam funcionar.
UI.Codex.codex_projects1=Os projetos nem sempre ficarão disponíveis imediatamente assim que o mundo cumprir os requisitos necessários para obtê-los. Enquanto que as tecnologias públicas ficam bloqueadas até a conclusão de suas respectivas pesquisas, as facções podem alterar um projeto no qual você esteja investindo a qualquer momento e se aproveitar da pesquisa quando terminada. É possível repetir alguns projetos, mas seu custo aumentará a cada vez que seja concluído por uma facção.
UI.Codex.codex_projects2=Alguns conselheiros podem roubar projetos de outras facções.
UI.Codex.codex_projects3=Alguns projetos estão relacionados à conclusão de objetivos que levam as facções a entender o propósito da invasão alienígena ou as aproximam de suas condições de vitória.
UI.Codex.codex_techCategories.Title=Categorias de tecnologia
UI.Codex.codex_techCategories0=Muitos dos elementos do jogo concedem bonificações a áreas específicas de pesquisa. Normalmente, isso acontecerá de forma que os benefícios sejam decrescentes. As categorias de tecnologia são:
UI.Codex.codex_habitats.Title=Habitats
UI.Codex.codex_habitats0=Os habitats são instalações localizadas no espaço e operadas pelas facções. As facções podem construir dois tipos de habitats: estações, que ficam em órbitas, e bases, que ficam em áreas de habitat na superfície de corpos celestes. 
UI.Codex.codex_habitats1=As duas variedades de habitats possuem três tamanhos. As estações começam como plataformas, se tornam orbitais e em seguida anéis. As bases começam como postos avançados, viram assentamentos e finalmente se tornam colônias.
UI.Codex.codex_habitats2=Os habitats são compostos de módulos. Todos os módulos possuem um módulo de núcleo que determina o tamanho do habitat. O tamanho do habitat determina tanto a quantidade de módulos que ele pode ter (4, 12 ou 20, mais o núcleo), e o tamanho máximo de cada módulo.
UI.Codex.codex_habitats3=A maioria dos módulos de habitat consome energia. É necessário construir módulos de geração de energia para acomodar seus outros módulos. Os módulos podem ser desativados para reduzir o consumo de energia, porém certos módulos devem permanecer ativados se houver energia para alimentá-los. Os módulos também possuem um custo de manutenção pago em recursos espaciais, que podem ser pagos com propulsão e dinheiro se não houver recursos espaciais suficientes. Alguns módulos também possuem um custo de controle de missão.
UI.Codex.codex_foundingHabs.Title=Fundando habitats
UI.Codex.codex_foundingHabs0=Os habitats podem ser fundados de três formas. A primeira é lançando um módulo de núcleo a partir da Terra usando propulsão. Esse método pode levar muito tempo se o local for longe do planeta, e tais missões não podem ser planejadas se elas levarem mais de dois anos. A segunda é desenvolver kits que podem ser construídos pelas naves quando elas chegarem a uma órbita ou um corpo celeste. A terceira é fundar habitats a partir de outros habitats que possuam um módulo de construção localizados no mesmo sistema planetário.
UI.Codex.codex_automatedHabs.Title=Habitats automatizados
UI.Codex.codex_automatedHabs0=Quando você tiver avançado suas capacidades tecnológicas o suficiente, você poderá criar habitats automatizados. São pequenas instalações robóticas nas quais apenas outros módulos automatizados poderão ser adicionados. Elas tipicamente funcionam como uma mina pequena ou uma estação de suprimentos para as suas naves. Elas exigem mais controle de missão, mas não tantos recursos espaciais para mantê-las.
UI.Codex.codex_automatedHabs1=Atenção: os habitats automatizados não podem usar módulos comuns (que possuem tripulação) e não podem ser melhorados para que se transformem em habitats comuns. Para substituir um habitat automatizado, ele deve ser desativado antes.
UI.Codex.codex_buildingHabs.Title=Construindo habitats
UI.Codex.codex_buildingHabs0=Os módulos de habitat são acrescentados aos habitats quando são enviados a partir da Terra usando propulsão ou ao construí-los com materiais espaciais. Com desenvolvimento tecnológico suficiente, muitos módulos possuirão trilhas de melhora para possam ser aumentados; há um desconto para melhorar módulos seguindo esses caminhos.
UI.Codex.codex_buildingHabs1=Os habitats são categorizados em "níveis", um valor que determina quantos módulos de quais tamanhos o habitat pode ter. Melhorar o módulo de núcleo aumenta o nível do habitat.
UI.Codex.codex_buildingHabs2=Objetos espaciais muito pequenos não podem abrigar habitats além de um certo tamanho.
UI.Codex.codex_assaultingHabs.Title=Atacando habitats
UI.Codex.codex_assaultingHabs0=Frotas que tenham fuzileiros, e conselheiros na missão de atacar alvo espacial inimigo que tenham acesso a fuzileiros de frotas ou habitats podem atacar habitats inimigos para tentar tomá-los. Em ambos os casos, o ataque usará todos os fuzileiros disponíveis no local para ser realizado, incluindo fuzileiros de outras frotas que estejam no mesmo local. Os habitats são defendidos por módulos de fuzileiros. Ao atacar uma base a partir da órbita, os habitats que tenham módulos ativos de defesa superfície-órbita também ajudarão na defesa. Os módulos de fuzileiros de ambos os lados podem sofrer danos ou ser destruídos ao participar do ataque.
UI.Codex.codex_assaultingHabs1=Os conselheiros que estejam realizando a missão de ataque são capazes de contribuir com seu atributo de comando e com o recurso de operações à batalha para aumentar suas chances de sucesso quanto a ataques iniciados por frotas.
UI.Codex.codex_defendingHabs.Title=Defendendo habitats
UI.Codex.codex_defendingHabs0=As facções podem criar módulos de habitat capazes de defender seus outros habitats. 
UI.Codex.codex_defendingHabs1=Módulos de defesa de base usarão lasers pesados capazes de abater naves que os bombardeiem da órbita. Esses lasers serão melhorados automaticamente quando as tecnologias globais de laser forem pesquisadas. Os módulos também terão defesa de ponto para protegê-los contra projéteis.
UI.Codex.codex_defendingHabs2=Os módulos defensivos em estações orbitais, por outro lado, usam armas de torres de naves que a facção desenvolver dos projetos de armas. Cada módulo normalmente equipará duas torres: a arma de laser e a arma de projéteis mais fortes da facção. Módulos de habitat menores podem usar apenas as torres menores que forem desenvolvidas. Essas armas operam sob controle independente durante o combate e não podem ser direcionadas como as armas presentes nas naves. Enquanto esses módulos podem proteger uma estação contra pequenos esquadrões de inimigos, é provável que eles não tenham força suficiente para derrotar frotas grandes sem apoio de uma frota própria.
UI.Codex.codex_defendingHabs3=Concluir projetos de escudos também fará com que os módulos de base e de estação sobrevivam por mais tempo ao serem atacados.
UI.Codex.codex_defendingHabs4=Módulos marinhos protegerão tanto as estações quanto as bases de ataques.
UI.Codex.codex_shipDesign.Title=Projetar naves
UI.Codex.codex_shipDesign0=Muitas das conspirações furtivas tramadas na Terra e os esforços para industrializar o espaço marcam o caminho trilhado pelas facções para construir frotas de naves que protejam e avancem seus interesses. Assim que as facções desbloqueiam a tecnologia de construção de orbitais e o projeto de portos espaciais para seus habitats, elas podem construir naves interplanetárias.
UI.Codex.codex_shipDesign1=Com os módulos certos, as naves podem prospectar e fundar habitats, mas a função primária da maioria das naves é o combate.
UI.Codex.codex_shipDesign2=A qualquer momento, você pode projetar naves com os módulos que já desenvolveu. Quando você tiver um estaleiro, poderá construir as naves já com seus recursos espaciais e, se necessário, com propulsão e dinheiro.
UI.Codex.codes_shipDesign3=Os fatores essenciais que devem ser considerados para construir suas naves são: massa, aceleração e Delta-V. Ter mais massa significa ter menos aceleração e que a nave será mais difícil de manobrar. O Delta-V mede o quanto você pode mudar sua velocidade e ele determina a rapidez com que você pode chegar a algum lugar.
UI.Codex.codex_hull.Title=Casco
UI.Codex.codex_hull0=O projeto de uma nave começa pelo casco. O tipo de casco determina a quantidade de pontos que a nave terá para a instalação de armas de nariz e de casco, a quantidade de módulos de utilidade e o comprimento do casco.
UI.Codex.codex_hull1=As naves mais curtas têm menos inércia, o que significa que elas podem girar mais rapidamente do que naves maiores.
UI.Codex.codex_drive.Title=Propulsor
UI.Codex.codex_drive0=<LOC,UI.Fleets.Drive.Description>
UI.Codex.codex_drive1=Durante um combate, um propulsor em funcionamento pode acabar destruindo um míssil ou projétil que esteja mirando na traseira da nave. Propulsores de alta energia têm mais chance de sucesso.
UI.Codex.codex_powerPlant.Title=Gerador de energia
UI.Codex.codex_powerPlant0=<LOC,UI.Fleets.PowerPlant.Description>
UI.Codex.codex_radiators.Title=Radiadores
UI.Codex.codex_radiators0=<LOC,UI.Fleets.Radiator.Description>
UI.Codex.codex_batteries.Title=Baterias
UI.Codex.codex_batteries0=<LOC,UI.Fleets.Battery.Description>
UI.Codex.codex_weapons.Title=Armas
UI.Codex.codex_weapons0=Os sistemas de armas podem ser montados no nariz ou no casco da nave. As armas de nariz normalmente são mais potentes do que armas de casco de tamanhos parecidos, mas têm um campo de alcance limitado. As armas de casco podem disparar em qualquer direção em volta da nave.
UI.Codex.codex_weapons1=As armas também podem ser de vários tamanhos. Os sistemas de armas maiores ocuparão vários dos pontos destinados às armas de casco nas nave.
UI.Codex.codex_weapons2=As armas podem ser classificadas em quatro tipos gerais: armas de laser, cujos tiros na velocidade da luz causam dano imediato ao alvo; armas de projéteis, que disparam projéteis não guiados contra um alvo e usam energia cinética ou química para eliminá-lo; mísseis, um sistema de armas guiadas que perseguirão um alvo até ficarem sem propelente; e armas de partículas, cuja mira é feita de forma similar aos lasers, mas que propagam dano radioativo dentro do casco do alvo.
UI.Codex.codex_weapons3=Certas armas só podem ser usadas ofensivamente contra naves inimigas e módulos de habitats, outras só podem ser usadas defensivamente para abater projéteis e mísseis. Porém, algumas podem ser usadas para ambas as finalidades.
UI.Codex.codex_armor.Title=Escudos
UI.Codex.codex_armor0=Os escudos da nave absorverão o impacto de ataques inimigos de forma a prevenir danos aos componentes internos. Cada ponto de escudo absorverá 20 MJ de energia em um único local do casco antes de ser vaporizado. Diferentes tipos de escudo exigem diferentes espessuras e massas para absorver quantidades específicas de danos. Os ataques de superfície-órbita contra frotas em bombardeio sempre atingirão os escudos do nariz das naves.
UI.Codex.codex_armor1=Os escudos de nariz e de cauda ocupam menos massa por ponto do que escudos laterais, que precisam cobrir áreas maiores. Cada ponto adicional de escudos laterais também aumenta a massa de outros escudos, pois a área de superfície da nave está aumentando com a adição de camadas. Os escudos de nariz e cauda também precisam cobrir áreas maiores com o aumento dos escudos laterais.
UI.Codex.codex_armor2=Cada tipo de casco tem uma quantidade máxima de escudos que pode suportar.
UI.Codex.codex_propellantTanks.Title=Tanques de propelente
UI.Codex.codex_propellantTanks0=Cada nave precisa ter um ou mais tanques de propelente de 100 toneladas. A quantidade de tanques de propelente determinará o valor de Delta-V.
UI.Codex.codex_shipOfficers.Title=Oficiais da nave
UI.Codex.codex_shipOfficers0=Conforme as naves realizam longas viagens ou participam de batalhas, suas tripulações ganham experiência. Em certos momentos, um ou mais dos oficiais da nave podem ser reconhecidos como especialistas habilidosos em seus respectivos postos e por ter uma equipe veterana sob seu comando. Esses oficiais serão nomeados e concederão bonificações para as naves às quais sirvam.
UI.Codex.codex_shipOfficers1=Os oficiais podem receber várias promoções, e assim receber bonificações maiores com cada nível. Eles podem ser mortos em combate. //They may also retire if they serve long enough. Higher-ranked officers may transfer between ships in the same fleet or docked at the same hab, but in doing so they will lose one step in rank, representing the loss in familiarity with their environment.
UI.Codex.codex_shipOfficers2=A lista a seguir inclui as categorias, as exigências e as habilidades dos oficiais que podem ser desenvolvidas.
UI.Codex.codex_fleets.Title=Frotas
UI.Codex.codex_fleets0=As frotas consistem de uma ou mais naves que são lideradas por uma das facções humanas ou pelos alienígenas. As frotas executam operações e lutam em batalhas espaciais.
UI.Codex.codex_shipConstruction.Title=Construção de naves
UI.Codex.codex_shipConstruction0=As naves são construídas em portos espaciais, estaleiros ou módulos de instalações de montagem espacial nos habitats. As naves podem ser construídas com uma combinação de recursos extraídos no espaço e de materiais enviados da Terra. Quando a construção estiver concluída, as naves passam a estar disponíveis atracadas ao habitat no qual foram construídas.
UI.Codex.codex_shipRefits.Title=Modificações
UI.Codex.codex_shipRefits0=As facções podem modificar naves nos habitats que possuam módulos de construção de naves. As modificações são geralmente limitadas à substituição de partes por outras de um tipo similar.<br/><br/>O casco não pode ser trocado.<br/>Os geradores de energia podem ser alterados se o novo gerador pertencer à mesma classe do antigo.<br/>Propulsores podem ser acrescentados ou removidos dos impulsores já em uso, ou um novo propulsor pode ser escolhido se ele tiver o mesmo tipo de uso de energia, propelente e classificação.<br/>As armas podem ser alteradas se a nova peça for da mesma classe e tiver o mesmo tipo de montagem (por exemplo, um laser de casco tipo 1 só pode ser substituído por lasers de casco tipo 1).<br/>Os escudos podem ser alterados livremente.<br/>As baterias podem ser trocadas livremente por outros tipos de bateria, mas não por outros módulos de utilidade.<br/>Os dissipadores de calor podem ser trocados livremente, mas não por outros módulos de utilidade.<br/>Os radiadores podem ser trocados livremente.<br/>Os módulos de utilidade, com exceção das baterias e dos dissipadores de calor, podem ser trocados por outros módulos da mesma classe.
UI.Codex.codex_propellant.Title=Delta-V
UI.Codex.codex_propellant0=O termo <h>Delta-V</h> representa a mudança em velocidade. É a medida da capacidade de uma nave de alcançar um certo destino em um tempo razoável. Gastar propelente para criar impulso reduz a quantidade disponível de Delta-V da nave, pois o processo esvazia os tanques de propelente, um recurso já limitado.
UI.Codex.codex_propellant1=O Delta-V de uma nave é o produto de sua massa total, do propelente que contém e da eficiência de seu propulsor em usar o propelente. Isso é chamado de "impulso específico" ou <h>velocidade de escape</h>. Em Terra Invicta, utilizamos o termo velocidade de escape.
UI.Codex.codex_propellant2=A depender de seu impulso e da gravidade do local em que ela se encontra no sistema solar, uma nave pode estabelecer rotas mais rápidas para outros destinos ao gastar mais Delta-V.
UI.Codex.codex_propellant3=O Delta-V de uma frota será igual ao Delta-V mais baixo dentre todas as naves na frota.
UI.Codex.codex_propellant4=As naves precisam reabastecer suas cargas de propelente nos habitats que possuam depósitos de suprimentos ou estaleiros.
UI.Codex.codex_transfers.Title=Traslados
UI.Codex.codex_transfers0=Traslado é o termo para quando uma frota se move de um local a outro enquanto permanece no espaço. As frotas podem trasladar para órbitas, estações ou outras frotas.
UI.Codex.codex_transfers1=Quando uma operação de traslado é iniciada, a frota receberá uma ou mais opções de trajetória se for possível chegar ao local desejado. Se várias trajetórias estiverem disponíveis, o jogador poderá escolher se dará preferência ao tempo de chegada ou ao gasto de Delta-V.
UI.Codex.codex_transfers2=As trajetórias podem ser: <h>espirais de microimpulso</h>, típicas para frotas de baixa aceleração; <h>cônicas de impulso</h>, para frotas com aceleração alta, mas Delta-V baixo; ou <h>cinemáticas de tocha</h>, para frotas avançadas que tenham aceleração e Delta-V altos.
UI.Codex.codex_fleetOperations.Title=Operações de frota
UI.Codex.codex_fleetOperations0=As frotas podem realizar diversas operações, em geral quando estão em uma órbita e não em traslado. Elas são:
UI.Codex.codex_orbitalBombardment.Title=Bombardeio orbital
UI.Codex.codex_orbitalBombardment0=Uma frota equipada com armas magnéticas, laser ou nucleares podem realizar bombardeios orbitais contra alvos que estejam na superfície de um corpo celeste. A frota deve estar em uma órbita adjacente para lançar os ataques. 
UI.Codex.codex_orbitalBombardment1=Acima da Terra, os alvos possíveis incluem exércitos, instalações espaciais, regiões e quaisquer alvos alienígenas que tenham sido detectados pela facção. Em outros corpos celestes, os alvos podem ser bases e frotas que estejam aterrissadas.
UI.Codex.codex_orbitalBombardment2=Certas armas, como lasers que utilizam frequências ultravioletas, não conseguem realizar ataques através de atmosferas mais espessas, particularmente a da Terra e a de Titã.
UI.Codex.codex_orbitalBombardment3=Se um habitat ou região possuir defesas, elas irão contra-atacar a frota e tentar abater projéteis e mísseis.
UI.Codex.codex_orbitalBombardment4=A frota que estiver fazendo o bombardeio pode escolher a altitude da qual deseja atacar o alvo, avaliando os custos de risco e de dano provocado. Em altitudes mais altas, os lasers de ambas as partes serão menos eficientes, e as defesas terão maior probabilidade de abater projéteis e mísseis.
UI.Codex.codex_spaceCombat.Title=Combate espacial
UI.Codex.codex_spaceCombat0=O encontro de duas frotas de facções inimigas em uma órbita, no espaço profundo ou em uma estação dará início a uma batalha espacial. Os jogadores podem escolher resolver os combates automaticamente.
UI.Codex.codex_spaceCombat1=Antes que a batalha comece, cada frota escolherá um de três posicionamentos: enfrentar, aceitar ou evadir. Pelo menos uma das frotas terá que escolher "enfrentar" para que uma batalha ocorra; se a outra frota escolher "evadir", as frotas podem apostar Delta-V para realizar uma perseguição. Se a frota que escolheu "enfrentar" oferecer mais Delta-V, o combate ocorrerá. As frotas que estão atracadas em habitats ou que não estiverem disponíveis para operações devido a batalhas anteriores só poderão selecionar "aceitar".
UI.Codex.codex_spaceCombat2=Em uma perseguição, a aceleração relativa das duas frotas determinará o resultado. Se uma das frotas for capaz de acelerar consideravelmente mais do que sua oponente, ela poderá forçar o combate ou evadir gastando pouco Delta-V. Frotas que tenham uma capacidade de aceleração similar iniciarão uma perseguição lenta e tensa, na qual podem acabar gastando muito Delta-V se os dois lados estiverem determinados a superar o outro. Uma perseguição termina quando a frota em perseguição chegar a uma certa proximidade de seu alvo, ou quando a frota em fuga se afastar de sua perseguidora nesses mesmos parâmetros.
UI.Codex.codex_spaceCombat3=As estações com módulos de defesa participarão das batalhas, e serão consideradas desativadas se esses módulos forem destruídos.
UI.Codex.codex_spaceCombat4=As batalhas espaciais em grande escala terão naves ativas e de reforço. As naves de reforço se juntarão ao combate em um segundo momento para substituir as naves ativas quando elas forem destruídas. É possível ajustar a quantidade máxima de naves que podem estar ativas a qualquer momento do combate nas configurações de jogo no menu de opções. Um valor máximo de 30, por exemplo, limitará cada lado de combatentes a ter no máximo 15 naves ativas. Esse recurso serve para equilibrar problemas de performance durante as grandes batalhas.
UI.Codex.codex_spaceCombat5=Quando uma frota ou uma estação é atacada, as frotas aliadas da vítima que estejam na mesma órbita e a menos de 1.000 km de distância serão atraídas para a batalha e se juntarão à frota de defesa.
UI.Codex.codex_maneuvers.Title=Manobras
UI.Codex.codex_maneuvers0=Quando estiverem em combate, os jogadores poderão planejar manobras para suas naves determinando pontos de notificação no espaço em três dimensões. As naves irão virar e usar impulso para chegar aos pontos determinados. Os jogadores também podem girar uma nave independentemente da direção de viagem para apresentar suas faces com armas ou escudos ao inimigo.
UI.Codex.codex_specialManeuvers.Title=Manobras especiais
UI.Codex.codex_specialManeuvers0=As manobras especiais incluem giros, igualar velocidade e um comando para travar a nave em um alvo específico que mantém o nariz da nave apontado para seu alvo principal.
UI.Codex.codex_fireControl.Title=Controle de disparos
UI.Codex.codex_fireControl0=As armas têm um ou mais modos de disparo disponíveis. Eles podem ser selecionados na frota, na nave ou individualmente nas próprias armas durante o combate.
UI.Codex.codex_fireControl1=As naves também podem estabelecer uma nave inimiga ou um módulo de habitat para ser seu alvo principal. As armas da nave apontarão para esse inimigo antes dos demais. As armas de mísseis exigem um alvo principal para serem ativadas.
UI.Codex.codex_fireControl2=A depender de suas capacidades, as armas também podem ser configuradas para apenas atacar naves inimigas, apenas disparar defensivamente contra projéteis e mísseis de ataque, ou para ficar em modo de guarda, no qual dispararão primeiro contra ameaças de projéteis e só então passarão a atacar naves inimigas.
UI.Codex.codex_targeting.Title=Sistema de mira e CME
UI.Codex.codex_targeting0=Todas as armas têm um valor de alcance de mira em quilômetros. Esse é o alcance máximo no qual a arma é capaz de identificar naves como alvo e disparar. As armas de partículas podem não disparar contra alvos em alcance máximo se não forem capazes de provocar dano suficiente.
UI.Codex.codex_targeting1=Cada arma da nave deve ser capaz de anular quaisquer contramedidas eletrônicas (CME) inimigas para mirar contra um alvo inimigo com sucesso. Se falhar, a arma entra em um período de recarga forçado enquanto anula as CME. Esta recarga já não afeta armas de mísseis, pois os sistemas de autoorientação delas também precisam superar as CME.  
UI.Codex.codex_targeting2=Módulos de mira computadorizada podem anular CME inimigas. As naves também mirarão em uma nave específica mais rapidamente após derrotar suas CME durante o combate.
UI.Codex.codex_targeting3=As naves também precisam usar sensores localizados no exterior dos escudos. Eles são vulneráveis a quaisquer armas, em especial as nucleares, de antimatéria, de laser e de partículas. O dano sofrido pelos sensores reduz a capacidade da nave em anular CME inimigas, mas é reparado rapidamente.
UI.Codex.codex_heatManagement.Title=Gerenciamento de calor
UI.Codex.codex_heatManagement0=Usar o gerador de energia da nave para recarregar as baterias ou ativar o propulsor irá gerar calor residual. Ele normalmente é eliminado pelos radiadores presentes nos dissipadores de calor da nave, que não podem receber escudos. Durante o combate, os radiadores podem ser retraídos para serem protegidos, mas isso fará com que a nave passe a armazenar o calor nos dissipadores, cuja capacidade é limitada. O nível de calor irá cair automaticamente quando radiadores estiverem estendidos. Se o nível de calor armazenado nos dissipadores chegar ao máximo, a nave começará a sofrer danos internos. Durante os combates, os radiadores serão estendidos automaticamente para eliminar calor, se possível. <h>Atenção, pois se o calor de uma nave não for gerenciado adequadamente, ela sofrerá uma falha catastrófica</h>. 
UI.Codex.codex_batteryManagement.Title=Gerenciamento de bateria
UI.Codex.codex_batteryManagement0=As baterias de uma nave servem como uma fonte de energia para quando seu gerador de energia estiver sendo usado para propulsão ou estiver danificado.
UI.Codex.codex_damage.Title=Resposta a danos
UI.Codex.codex_damage0=Qualquer dano que penetre os escudos da nave atingirão seus sistemas internos. As armas e outros módulos podem ficar temporariamente desabilitados ou ser destruídos, e precisarão ser reparados em um habitat que tenha um estaleiro.
UI.Codex.codex_damage1=As equipes de resposta a danos também tentarão restaurar o funcionamento de sistemas essenciais durante combates.