UI.Fleets.Title=Frotas
UI.Fleets.DryMass=Massa seca:<rcol>{0} toneladas</rcol>
UI.Fleets.WetMass=Massa fresca:<rcol>{0} toneladas</rcol>
UI.Fleets.CurrentMass=Massa atual:<rcol>{0} toneladas</rcol>
UI.Fleets.ItemMass=Massa:<rcol>{0} toneladas</rcol>
UI.Fleets.SingleDV={0} km/s										// DV as in ∆V, Delta-v, is a rocket science term that measures how much a ship can change (∆) its velocity ("v")
UI.Fleets.DVValue={0}/{1} km/s
UI.Fleets.DV=DV:<rcol> {0}/{1} km/s 							
UI.Fleets.BaseDV=DV:<rcol> {0} km/s
UI.Fleets.ThreeDV=DV:<rcol> {0}/{1}/{2} km/s
UI.Fleets.StdDV={0} {1} km/s
UI.Fleets.Accelgs={0} g
UI.Fleets.Accelmgs={0} miligês
UI.Fleets.AccelmgsAbbr={0} mg
UI.Fleets.TwoValues={0}/{1}
UI.Fleets.CruiseAccel=Aceleração de navegação:<rcol>{0}</rcol>
UI.Fleets.CombatAccel=Aceleração máxima de combate:<rcol>{0}</rcol>
UI.Fleets.CruiseAcceleration=Aceleração de navegação: {0}
UI.Fleets.CombatAcceleration=Aceleração de combate: {0}
UI.Fleets.TurnRate=Velocidade de virada:<rcol>{0} graus/s ^2</rcol>
UI.Fleets.WetMassTab=Massa fresca:
UI.Fleets.WetMassTab.Description=A massa fresca é a massa total da nave quando ela está totalmente carregada com combustível. A massa influencia a capacidade de manobra da nave. Ter mais massa diminuiu o Delta-V e a velocidade de virada.<br/><br/>Distribuição de massa:
UI.Fleets.CrewTab=Tripulação:
UI.Fleets.CrewTab.Description=Quantidade de pessoal que servirá abordo da nave.
UI.Fleets.CruiseAccelerationTab=Aceleração de navegação:
UI.Fleets.CruiseAccelerationTab.Description=Rapidez com a qual a nave pode alterar sua velocidade na camada de estratégia. Uma maior aceleração de navegação permite que a nave supere a gravidade de um corpo celeste e siga trajetórias mais diretas aos seus destinos.<br/><br/>O mínimo de 100 miligês é ideal. As naves com menos de 10 miligês podem sofrer com tempos mais longos de viagem a outros corpos, especialmente ao serem lançadas de poços gravitacionais planetários profundo.<br/><br/>Naves com menos de 0,5 miligês podem não ser capazes de fazer transferências interplanetárias, pois as viagens demorariam demais.
UI.Fleets.CombatAccelerationTab=Aceleração de combate:
UI.Fleets.CombatAccelerationTab.Description=Rapidez com a qual a nave pode alterar sua velocidade na camada de combate. Alguns propulsores têm capacidade de oferecer mais aceleração em situações de combate.
UI.Fleets.CruiseDeltaVTab=Delta-V de navegação:
UI.Fleets.CruiseDeltaVTab.Description=Determina aonde a nave pode ir e quão rápido pode chegar lá. Ter mais propelente aumenta o Delta-V, enquanto que ter mais massa na nave o diminui.<br/><br/>Naves com menos de 8 km/s de Delta-V podem ter dificuldades para chegar à lua saindo de uma das órbitas da Terra.<br/><br/>Naves com menos de 30 km/s de Delta-V não serão capazes de realizar traslados interplanetários saindo da Terra.<br/><br/>Naves com cerca de 60 k de Delta-V poderão realizar traslados mais extremos, como por exemplo sair de Mercúrio e chegar em Saturno.<br/><br/>Verifique o <h>códex</h> para mais informações.
UI.Fleets.TurnRateTab=Velocidade de virada:
UI.Fleets.TurnRateTab.Description=Rapidez com a qual a nave pode alterar sua orientação em combate. Este valor depende do comprimento e da massa da nave. Naves menores virarão mais rápido do que naves grande nas mesmas condições.
UI.Fleets.HeatSinkCapacityTab=Capacidade dos dissipadores:
UI.Fleets.HeatSinkCapacityTab.Description=Os dissipadores de calor servem como substitutos temporários para o sistema de gerenciamento de calor de uma nave enquanto seus radiadores, que são vulneráveis, estiverem retraídos durante o combate. Valores mais altos permitem que a nave lute por mais tempo sem estender seus radiadores.
UI.Fleets.BatteryCapacityTab=Capacidade das baterias:
UI.Fleets.BatteryCapacityTab.Description=As baterias da nave armazenam energia de seu gerador de energia para serem usadas, principalmente, pelos sistemas de armas quando o gerador de energia estiver indisponível. Baterias mais avançadas podem ser carregadas durante o combate.
UI.Fleets.ConstructionCostTab=Custo de construção:
UI.Fleets.ConstructionCostTab.Description=São os recursos necessários para construir a nave. Qualquer recurso em falta podem ser substituído por propulsão ou dinheiro. Isso pode aumentar o tempo de construção, pois nesse caso os materiais serão enviados da Terra.  
UI.Fleets.ConstructionTimeTab=Tempo de construção:
UI.Fleets.ConstructionTimeTab.Description=Tempo que levará para construir a nave quando todos os materiais necessários estiverem no estaleiro. Estaleiros maiores reduzem o tempo de construção.
UI.Fleets.MaintenanceCostTab=Manutenção
UI.Fleets.MaintenanceCostValue={0}{1} {2}{3}/mês
UI.Fleets.MaintenanceCostTab.Description=O custo mensal para manter a nave. Se seus custos de manutenção não forem pagos, a nave ficará mais vulnerável às tentativas de captura ou destruição de outras facções.
UI.Fleets.ConstructionTime={0} dias												// value, value, boost icon
UI.Fleets.ConstructionTimeLine=/{0}
UI.Fleets.GJ={0} GJ
UI.Fleets.Degs2={0} graus/s ^2
UI.Fleets.Length=Comprimento:<rcol>{0} metros</rcol>
UI.Fleets.Beam=Feixe:<rcol>{0} metros</rcol>
UI.Fleets.DriveLine=Propulsor:<rcol>{0}</rcol>
UI.Fleets.PowerPlantLine=Gerador de energia:<rcol>{0}</rcol>
UI.Fleets.BatteryLine=Bateria:<rcol>{0}</rcol>
UI.Fleets.RadiatorsLine=Radiadores:<rcol>{0}</rcol>
UI.Fleets.HeatSinkCapacity=Capacidade dos dissipadores:<rcol>{0} GJ</rcol>									// GJ = gigajoules
UI.Fleets.HeatSinkCapacityUnk=Capacidade dos dissipadores:<rcol>desconhecida</rcol>									// GJ = gigajoules
UI.Fleets.NoseWeaponsHeader=Armas de nariz
UI.Fleets.HullWeaponsHeader=Armas de casco
UI.Fleets.UtilityModuleHeader=Módulos de utilidade
UI.Fleets.NoseArmorMaterial=Escudo de nariz:<rcol>{0} cm de {1}</rcol>
UI.Fleets.ArmorRating=Nível dos escudos / Redução de danos:<rcol>{0}</rcol>
UI.Fleets.LateralArmorMaterial=Escudo lateral:<rcol>{0} cm de {1}</rcol>
UI.Fleets.TailArmorMaterial=Escudo da cauda:<rcol>{0} cm de {1}</rcol>
UI.Fleets.NoseArmorMaterialunk=Escudo do nariz:<rcol>desconhecido</rcol>
UI.Fleets.LateralArmorMaterialunk=Escudo lateral:<rcol>desconhecido</rcol>
UI.Fleets.TailArmorMaterialunk=Escudo da cauda:<rcol>desconhecido</rcol>
UI.Fleets.Crew=Tripulação:<rcol>{0}</rcol>
UI.Fleets.DamConCrew=Equipe de resposta a danos:<rcol>{0}</rcol>
UI.Fleets.DamConCrew.Description=Durante um combate, o tamanho da equipe de resposta a danos determina a velocidade dos reparos. Equipes grandes o suficiente podem reparar vários módulos ao mesmo tempo.
UI.Fleets.ShipyardButtonText=Classe de naves
UI.Fleets.ShipDesignerButtonText=Projetar classe
UI.Fleets.FullClassName=Classe {0} - {1}										// proper noun, hull type
UI.Fleets.ClassName=Classe {0}												// proper noun
UI.Fleets.DesignerCoreDataHeader=Classe e casco
UI.Fleets.DesignerShipDataHeader=Informações de performance
UI.Fleets.NeedDrive=Requere propulsor
UI.Fleets.DesignerHeader=Projetor de naves
UI.Fleets.ClassListHeader=Classes de naves {0}
UI.Fleets.DerivedValuesHeader=Informações da nave
UI.Fleets.PrimarySystemsHeader=Sistemas principais
UI.Fleets.MissionSystemsHeader=Sistemas de missão
UI.Fleets.DamageControl=Informe de danos
UI.Fleets.ShowAllShips=Exibir todas as naves
UI.Fleets.ShowAllFleets=Exibir todas as frotas
UI.Fleets.Utility=Módulos de utilidade
UI.Fleets.Utility.Description=Os módulos de utilidade desempenham uma variedade de funções para ampliar as capacidades de uma nave. Os dissipadores de calor são módulos importantes para naves de combate, pois evitam a exposição dos radiadores a ataques inimigos. Também é possível colocar baterias adicionais nos encaixes de módulos de utilidade.
UI.Fleets.PowerPlant=Gerador de energia
UI.Fleets.PowerPlant.Description=O gerador de energia de uma nave produz energia tanto para o propulsor quando para os outros sistemas da nave. A massa do gerador de energia se ajusta ao valor maior de energia que é exigida pelo propulsor ou pelos sistemas da nave. O gerador de energia também produz calor residual que deve ser armazenado nos dissipadores de calor ou eliminado pelos radiadores.<br/><br/>Atenção: muitos propulsores exigem uma certa classe de gerador de energia para funcionar e, em alguns casos, um gerador de energia mais básico da classe correta pode não ser capaz de produzir a energia suficiente para alimentar um propulsor avançado.
UI.Fleets.Battery=Bateria
UI.Fleets.Battery.Description=A bateria principal da nave armazena energia do gerador de energia e a distribui para as armas, para o suporte de vida e para outros sistemas essenciais quando o gerador principal estiver indisponível, seja porque está danificado ou por estar alimentando o propulsor em naves que não possuírem um propulsor independente. Armas de alta performance podem gastar as baterias rapidamente durante um combate. Baterias melhoradas terão uma capacidade maior ou uma velocidade de carga maior. É possível acrescentar baterias adicionais do mesmo tipo nos encaixes de módulos de utilidade para aumentar sua capacidade.
UI.Fleets.Radiator=Radiadores
UI.Fleets.Radiator.Description=Os radiadores eliminam o calor residual produzido pelo gerador de energia da nave. Sua escala é dada em massa, com base na produção e na eficiência do gerador de energia. Como eles são altamente vulneráveis em combate, os radiadores podem ser retraídos se a nave possuir dissipadores de calor em pelo menos um dos encaixes de utilidade. Porém, assim que os dissipadores estivem completamente cheios, os radiadores serão estendidos novamente para proteger a tripulação.
UI.Fleets.Drive=Propulsor
UI.Fleets.Drive.Description=Os propulsores expelem propelente a partir da cauda para mover a nave. Eles têm uma variedade de formas, mas são classificados por dois valores comuns: empuxo e velocidade de escape. Propulsores com alto empuxo podem chegar a velocidades mais altas mais rápido, e propulsores com alta velocidade de escape usam menos propelente. Juntos, esses valores determinam a energia exigida ao gerador de energia da nave. Adicionar tanques de propelente de 100 toneladas à nave aumentará seu Delta-V, ou seja, sua capacidade de alterar sua velocidade.<br/><br/>Atenção: muitos propulsores exigem uma certa classe de gerador de energia para funcionar e, em alguns casos, um gerador de energia mais básico da classe correta pode não ser capaz de produzir a energia suficiente para alimentar um propulsor avançado.
UI.Fleets.NoseArmor=Escudo do nariz
UI.Fleets.NoseArmor.Description=O escudo no nariz da nave absorverá o impacto de ataques inimigos de forma a prevenir danos aos componentes internos. Cada ponto de escudo absorverá 20 MJ de energia em um único local do casco antes de ser vaporizado. Diferentes tipos de escudo exigem diferentes espessuras e massas para absorver quantidades específicas de danos.
UI.Fleets.LateralArmor=Escudo lateral
UI.Fleets.LateralArmor.Description=Os escudos nas laterais da nave absorverão o impacto de ataques inimigos vindos de bordo e estibordo, de forma a prevenir danos aos componentes internos. Cada ponto de escudo absorverá 20 MJ de energia em um único local do casco antes de ser vaporizado. Diferentes tipos de escudo exigem diferentes espessuras e massas para absorver quantidades específicas de danos. Considere que um ponto de escudo lateral é muito maior do que os pontos de escudo do nariz ou da cauda, visto que ele tem mais área para cobrir.
UI.Fleets.TailArmor=Escudo da cauda
UI.Fleets.TailArmor.Description=O escudo na cauda da nave absorverá o impacto de ataques inimigos de forma a prevenir danos aos componentes internos. Cada ponto de escudo absorverá 20 MJ de energia em um único local do casco antes de ser vaporizado. Diferentes tipos de escudo exigem diferentes espessuras e massas para absorver quantidades específicas de danos.
UI.Fleets.SaveRequirement=Para que seja possível salvar o projeto desta nave, ela precisa ter um propulsor, um gerador de energia, radiadores, uma bateria, materiais de escudo (mesmo com 0 de espessura), pelo menos um tanque de propelente e uma função escolhida. Projetos especiais, como naves colonizadoras, também precisam ter módulos de utilidade que as permitam executar sua função.
UI.Fleets.NoseHardPoint=Base de montagem do nariz
UI.Fleets.NoseHardPoint.Description=As bases de montagem no nariz são utilizadas pelas armas frontais da nave. Essas armas geralmente são mais poderosas do que as armas posicionadas no casco, mas a nave terá que ser manobrada para ficar de frente com os inimigos para que possam ser usadas. Algumas armas podem precisar de várias bases de montagem. 
UI.Fleets.HullHardPoint=Base de montagem do casco
UI.Fleets.HullHardPoint.Description=As bases de montagem do casco servem para armas que podem atirar em qualquer direção. Algumas armas podem precisar de várias bases de montagem.
UI.Fleets.Propellant=Propelente
UI.Fleets.Propellant.Description=Cada tanque contém 100 toneladas de propelente que será usado pelo propulsor da nave e aumenta seu Delta-V.
UI.Fleets.None=Selecione um módulo ou encaixe
UI.Fleets.None.Description=Selecione um módulo do menu acima e arraste-o até o encaixe necessário para começar a construir sua nave.
UI.Fleets.DesignerPropellantTanks=Tanques de propelente<br/>{0}
UI.Fleets.ArmorOnFacing=Máx: {0}
UI.Fleets.DesignerSaveDesign=Salvar projeto
UI.Fleets.ValidRefitDesign=Modificação válida
UI.Fleets.InvalidRefitDesign=Modificação inválida
UI.Fleets.RefitFailDuplicate=A modificação não pode ser uma duplicata da classe existente.
UI.Fleets.RefitFailHull=O casco deve combinar.
UI.Fleets.RefitFailPowerPlant=Geradores de energia devem pertencer à mesma classe.
UI.Fleets.RefitFailDrive=Os propulsores devem ter a mesma classe, tipo de gerador de energia e tipo de propelente.
UI.Fleets.RefitFailHeatSink=Radiadores não podem ser trocados por outros módulos.
UI.Fleets.RefitFailBattery=Baterias não podem ser trocadas por outros módulos.
UI.Fleets.RefitFailUtilityModule=Módulos de utilidade só podem ser trocados por outros módulos de utilidade da mesma classe.
UI.Fleets.RefitFailWeaponModule=Armas não podem ser trocadas para classes diferentes ou por outros tamanhos de estação.
UI.Fleets.DesignerDVWarningHeader=ATENÇÃO
UI.Fleets.DesignerDVWarningYes=Sim
UI.Fleets.DesignerDVWarningNo=Não
UI.Fleets.DesignerDVWarningBody1=Este projeto de nave não possui Delta-V suficiente para viagens interplanetárias, mas é capaz de trasladar dentro de um sistema planetário. Tente acrescentar mais propelente, reduzir a massa ou usar um propulsor com uma velocidade de escape maior para aumentar o alcance desta nave. Você ainda deseja salvar este projeto?
UI.Fleets.DesignerDVWarningBody2=Este projeto de nave não possui Delta-V suficiente para realizar quase nenhum tipo de traslado, e pode acabar sendo útil apenas para defender uma estação espacial. Tente acrescentar mais propelente, reduzir a massa ou usar um propulsor com uma velocidade de escape maior para aumentar o alcance desta nave. Você ainda deseja salvar este projeto?
UI.Fleets.DesignerResetDesign=Apagar projeto
UI.Fleets.DeleteModule=Remover módulo
UI.Fleets.Designer.Transfer.SetTranser=Selecionar traslado de exemplo
UI.Fleets.Designer.Transfer.ToFrom=De {0} para {1}
UI.Fleets.Designer.Transfer.NoAcceleration=Sem propulsor
UI.Fleets.Designer.Transfer.NeedDV=Exige {0} km/s
UI.Fleets.ConstructionManagerButtonText=Construção de naves
UI.Fleets.ConstructionManagerHeader=Construção de naves
UI.Fleets.ConstructionManagerNoShipyards=Construa um porto espacial ou uma instalação maior que seja capaz de montar embarcações espaciais.
UI.Fleets.ConstructionManagerNoDesigns=Você ainda não possui projetos de naves ou marcou todos os seus projetos como obsoletos.
UI.Fleets.ConstructionManagerShowAll=Exibir todos
UI.Fleets.ConstructionManagerFilter=Local
UI.Fleets.RefitRefuelWarning=As naves são reabastecidas e reparadas durante modificações e pagam os custos necessários pelo processo. Ao selecionar múltiplas naves da mesma classe para modificar, o custo de modificação de cada nave pode diferir com base em seus respectivos custos de reabastecimento e reparos, se necessários.
UI.Fleets.SelectAShipClass=Selecione uma classe de nave
UI.Fleets.AddToConstructionQueueButton=Adicionar à fila
UI.Fleets.ClearQueueButton=Limpar fila
UI.Fleets.PayFromEarthTooltip=Marque esta opção para permitir que o estaleiro use propulsão e dinheiro para transportar recursos da Terra para substituírem quaisquer recursos espaciais que nossa facção não possua. Isso pode aumentar o tempo de construção enquanto esperamos pela entrega.
UI.Fleets.LeadQueueItem={0} ({1} dias)										//class name, days done
UI.Fleets.OtherQueueItem={0} ({1} dias)											//
UI.Fleets.CurrentlyBuilding=Construção atual:<br/>{0} (restam {1} dias) 
UI.Fleets.CurrentlyWaitingForResources=Aguardando entrega de recursos<br/>{0}<br/>Precisa de {1}
UI.Fleets.ShipyardIdle=Ocioso
UI.Fleets.GotoHabs=Habitats
UI.Fleets.ShipyardDetails={0} ({1}) {2}											// shipyard module name, sector ID
UI.Fleets.Inactive=Sem energia
UI.Fleets.Altitude=Altitude: {0} km
UI.Fleets.Mass=Massa:<rcol>{0} toneladas</rcol>
UI.Fleets.Tons={0} toneladas
UI.Fleets.RequiredPowerMW=Energia necessária:<rcol>{0} megawatts</rcol>
UI.Fleets.RequiredPowerGW=Energia necessária:<rcol>{0} gigawatts</rcol>
UI.Fleets.RequiredPowerTW=Energia necessária:<rcol>{0} terawatts</rcol>
UI.Fleets.NoRequiredPower=Este propulsor não exige uma fonte externa de energia.
UI.Fleets.NoRole=Sem função
UI.Fleets.RoleLine=Função:<rcol>{0}
UI.Fleets.SS_Interceptor=Interceptar
UI.Fleets.MS_Strike=Atacar
UI.Fleets.LS_Penetrator=Perfurante
UI.Fleets.LM_Protector=Protetora
UI.Fleets.SM_Patrol=Patrulhar
UI.Fleets.MM_SpaceSuperiority=Supremacia espacial
UI.Fleets.LM_Interdictor=Conter
UI.Fleets.LM_Raider=Atacante
UI.Fleets.SL_Defender=Defensora
UI.Fleets.ML_Standoff=Retaguarda
UI.Fleets.LL_Intruder=Intrusa
UI.Fleets.LL_Bomber=Bombardeira
UI.Fleets.TroopCarrier=Cargueiro de tropas
UI.Fleets.ArmyCarrier=Cargueiro de exércitos
UI.Fleets.Explorer=Exploradora
UI.Fleets.InnerSystemColonyShip=Colonizadora interna
UI.Fleets.OuterSystemColonyShip=Colonizadora externa
UI.Fleets.CouncilorTransport=Transporte
UI.Fleets.EarthSurveillance=Vigilância
UI.Fleets.ClassData.Help=
UI.Fleets.NoRole.description=Esta nave não possui uma função. Os projetos de naves devem possuir uma função antes que possam ser salvos. As funções dizem ao projetor automático como deve ser o design da nave e indicam qual será o comportamento da nave durante combates quando você entregar o controle à IA.
UI.Fleets.SS_Interceptor.description=Alcance estratégico: curto. Limitará a massa de propelente para favorecer a capacidade de manobra.<br/>Alcance de combate indicado: curto.
UI.Fleets.MS_Strike.description=Alcance estratégico: médio.<br/>Alcance de combate indicado: curto.
UI.Fleets.LS_Penetrator.description=Alcance estratégico: longo. Dará preferência a usar propelente para operações interplanetárias.<br/>Alcance de combate indicado: curto.
UI.Fleets.LM_Protector.description=Alcance estratégico: longo. Dará preferência a usar propelente para operações interplanetárias.<br/>Alcance de combate indicado: curto.<br/>Ênfase em defesa de ponto com alcance suficiente para defender naves próximas.
UI.Fleets.SM_Patrol.description=Alcance estratégico: curto. Limitará a massa de propelente para favorecer a capacidade de manobra.<br/>Alcance de combate indicado: médio.
UI.Fleets.MM_SpaceSuperiority.description=Alcance estratégico: médio.<br/>Alcance de combate indicado: médio.
UI.Fleets.LM_Interdictor.description=Alcance estratégico: longo. Dará preferência a usar propelente para operações interplanetárias.<br/>Alcance de combate indicado: médio.
UI.Fleets.LM_Raider.description=Alcance estratégico: longo. Dará preferência a usar propelente para operações interplanetárias.<br/>Alcance de combate indicado: médio.<br/>Ênfase em capacidades que permitam que a nave opere de maneira independente da frota. 
UI.Fleets.SL_Defender.description=Alcance estratégico: curto. Limitará a massa de propelente para favorecer a capacidade de manobra.<br/>Alcance de combate indicado: longo.
UI.Fleets.ML_Standoff.description=Alcance estratégico: médio.<br/>Alcance de combate indicado: médio.
UI.Fleets.LL_Intruder.description=Alcance estratégico: longo. Dará preferência a usar propelente para operações interplanetárias.<br/>Alcance de combate indicado: longo.
UI.Fleets.LL_Bomber.description=Alcance estratégico: longo. Dará preferência a usar propelente para operações interplanetárias.<br/>Alcance de combate indicado: longo.<br/>Ênfase em armas capazes de realizar bombardeios.
UI.Fleets.TroopCarrier.description=Deve possuir um módulo de fuzileiros. Nave não combatente que permanecerá na traseira de uma formação principal e tentará evitar combates.
UI.Fleets.ArmyCarrier.description=Nave não combatente que permanecerá na traseira de uma formação principal e tentará evitar combates.
UI.Fleets.Explorer.description=Deve possuir um módulo de investigação. Nave não combatente que permanecerá na traseira de uma formação principal e tentará evitar combates.
UI.Fleets.InnerSystemColonyShip.description=Deve possuir um kit de módulo de habitat. Nave não combatente que permanecerá na traseira de uma formação principal e tentará evitar combates.
UI.Fleets.OuterSystemColonyShip.description=Deve possuir um kit de módulo de habitat alimentado por energia nuclear. Nave não combatente que permanecerá na traseira de uma formação principal e tentará evitar combates.
UI.Fleets.CouncilorTransport.description=Nave não combatente que permanecerá na traseira de uma formação principal e tentará evitar combates.
UI.Fleets.EarthSurveillance.description=Nave não combatente que permanecerá na traseira de uma formação principal e tentará evitar combates.
UI.Fleets.AssignRoleTip=Clique para designar funções automaticamente de acordo com as características da nave.<br/>As funções da nave governam as preferências de projeto automático e como a nave se comporta em combate quando o controle é entregue para a IA.
UI.Fleets.Autodesign=Projetor automático
UI.Fleets.NoseWeaponsTab=Armas do nariz
UI.Fleets.HullWeaponsTab=Armas de casco
UI.Fleets.UtilitiesTab=Módulos de utilidade
UI.Fleets.RadiatorsTab=Radiadores
UI.Fleets.BatteriesTab=Bateria
UI.Fleets.PowerPlantTab=Gerador de energia
UI.Fleets.DriveTab=Propulsor
UI.Fleets.ArmorTab=Escudos
UI.Fleets.AllWeaponsTab=Todos
UI.Fleets.GunsTab=Canhões
UI.Fleets.MissilesTab=Mísseis
UI.Fleets.MagneticWeaponsTab=Armas magnéticas
UI.Fleets.PlasmaWeaponsTab=Armas de plasma
UI.Fleets.LasersTab=Lasers
UI.Fleets.ParticleWeaponsTab=Feixes de partículas
UI.Fleets.ModuleTable.FireModes=Modos de disparo
UI.Fleets.ModuleTable.Cooldown=Recarga
UI.Fleets.ModuleTable.ShortRangeDamage=Dano de<br/>curto alcance
UI.Fleets.ModuleTable.MediumRangeDamage=Dano de<br/>médio alcance
UI.Fleets.ModuleTable.LongRangeDamage=Dano de<br/>longo alcance
UI.Fleets.ModuleTable.Damage=Dano
UI.Fleets.ModuleTable.Magazine=Carregador
UI.Fleets.ModuleTable.MagazineMaterials=Materiais do carregador
UI.Fleets.ModuleTable.Range=Alcance
UI.Fleets.ModuleTable.Mass=Massa
UI.Fleets.ModuleTable.EnergyUsage=Uso de energia
UI.Fleets.ModuleTable.ShotPower=Potência de disparo
UI.Fleets.ModuleTable.ShortRangeArmorEffectiveness=Eficiência de escudo<br/>de curto alcance
UI.Fleets.ModuleTable.MediumRangeArmorEffectiveness=Eficiência de escudo<br/>de médio alcance
UI.Fleets.ModuleTable.LongRangeArmorEffectiveness=Eficiência de escudo<br/>de longo alcance
UI.Fleets.ModuleTable.ChargingEnergy=Recarregando energia
UI.Fleets.ModuleTable.Salvo=Barragem
UI.Fleets.ModuleTable.SalvoCooldown=Recarga<br/>de barragem
UI.Fleets.ModuleTable.MuzzleVelocity=Velocidade de saída
UI.Fleets.ModuleTable.MissileType=Tipo
UI.Fleets.ModuleTable.MissileAcceleration=Aceleração
UI.Fleets.ModuleTable.MissileDV=DV
UI.Fleets.ModuleTable.Materials=Materiais
UI.Fleets.ModuleTable.HeatSinkCapacity=Capacidade
UI.Fleets.ModuleTable.TonsPerGW=Ton. por GW
UI.Fleets.ModuleTable.Vulnerability=Vulnerabilidade
UI.Fleets.ModuleTable.MaterialsPerGW=Materiais por GW
UI.Fleets.ModuleTable.RechargeTime=Tempo de recarga
UI.Fleets.ModuleTable.BatteryCapacity=Capacidade
UI.Fleets.ModuleTable.Efficiency=Eficiência
UI.Fleets.ModuleTable.SpecificPower=Potência específica
UI.Fleets.ModuleTable.MaximumOutput=Saída máxima
UI.Fleets.ModuleTable.Thrust=Impulso
UI.Fleets.ModuleTable.ExhaustVelocity=Velocidade de escape
UI.Fleets.ModuleTable.RequiredPower=Energia exigida
UI.Fleets.ModuleTable.TonsPerSquareMeterPerPoint=Toneladas por metro quadrado<br/>por ponto
UI.Fleets.ModuleTable.Speciality=Especialidade
UI.Fleets.ModuleTable.MaterialsPerTon=Materiais por tonelada
UI.Fleets.AddModule=Acrescentar módulo
UI.Fleets.LandedLocation=aterrissou em {0}
UI.Fleets.DockedLocation=atracou em {0}
UI.Fleets.DestinationLocationOrbit=em traslado para {0}
UI.Fleets.DestinationLocationHab=em traslado para {0}
UI.Fleets.DestinationLocationFriendlyFleet=encontro com {0}
UI.Fleets.DestinationLocationFleet=interceptando {0}
UI.Fleets.OrbitLocation=em {0}
UI.Fleets.ExpandedLocation=, {0}
UI.Fleets.ArrivalDate=(Chegada em {0})
UI.Fleets.Unavailable=A frota estará disponível para realizar operações em {0}.
UI.Fleets.Cost=Custo de construção:<rcol>{0}</rcol>
UI.Fleets.MagazineCost=Custo de recarregamento:<rcol>{0}</rcol>
UI.Fleets.RoleTab=Função:
UI.Fleets.ArmorSummaryTab=Escudos (nariz/lateral/cauda):
UI.Fleets.ArmorSummaryValue={0}/{1}/{2}
UI.Fleets.WeaponMountDataOne=Ocupa {1} base de montagem no {0}						// nose/hull, #
UI.Fleets.WeaponMountDataMult=Ocupa {1} bases de montagem no {0}					// nose/hull, #
UI.Fleets.Nose=Nariz
UI.Fleets.Hull=Casco
UI.Fleets.FireModes=Modos de disparo:<rcol>{0}</rcol> 												// list of allowed modes
UI.Fleets.Focus=Ataque concentrado
UI.Fleets.Offense=Ataque
UI.Fleets.Defense=Defesa
UI.Fleets.Guardian=Guarda
UI.Fleets.HullMass=Casco: {0}
UI.Fleets.Bombardment=Capaz de bombardear:<rcol>{0}</rcol>
UI.Fleets.Bombardment_No=Não
UI.Fleets.Bombardment_Yes=Sim
UI.Fleets.Bombardment_NoAtmo=Não atravessa a atmosfera
UI.Fleets.PowerPlantMass=Gerador de energia: {0}
UI.Fleets.RadiatorMass=Radiadores: {0}
UI.Fleets.BatteryMass=Baterias: {0}
UI.Fleets.NoseArmorMass=Escudo do nariz: {0}
UI.Fleets.LateralArmorMass=Escudo lateral: {0}
UI.Fleets.TailArmorMass=Escudo da cauda: {0}
UI.Fleets.PropellantMass=Massa de propelente: {0}
UI.Fleets.CrewMass=Massa da tripulação: {0}
UI.Fleets.ModuleMass={0}: {1}
UI.Fleets.PropellantType=Propelente:<rcol>{0}</rcol>
UI.Fleets.PropellantMaterials=Quantidade de propelente por tanque:<rcol>{0}</rcol>
UI.Fleets.TwoColumn={0}<rcol>{1}</rcol>
UI.Fleets.Build=Construir
UI.Fleets.Upgrade=Melhorar
UI.Fleets.Obsolete=Obsoleto
UI.Fleets.HideObsolete=Ocultar obsoletos
UI.Fleets.Construct=Construir nave nova
UI.Fleets.Refit=Modificar nave atracada
UI.Fleets.DockedShips=Naves atracadas
UI.Fleets.ValidRefitClasses= Classes de modificações válidas
UI.Fleets.HullDescription=Bases de montagem: {0} no nariz, {1} no casco. Módulos de utilidade: {2}. {3}{4}. {5}{6}/mês. 
UI.Fleets.RightToToggleLists=Clique com o botão direito do mouse para alternar entre modo de lista e de ícones para os painéis.
UI.Fleets.RightToPlace=Clique com o botão direito do mouse em um encaixe vazio ou arraste e solte o ícone no encaixe desejado.
UI.Fleets.ShipyardShipMinimums=Naves que sejam lançadas deste estaleiro na superfície devem ter uma aceleração de combate de pelo menos {0} e pelo menos {1} km/s de Delta-V para chegar à órbita.
UI.Fleets.Unknown=Desconhecido
UI.Fleets.HomeBase=Habitat de origem
UI.Fleets.HomeBaseDetail=Estabelecer um habitat para ser o porto de origem desta frota fará com que ele seja o destino padrão para traslados.
UI.Fleets.BuildDays=Construir ({0} dias)	
UI.Fleets.AddToConstructionQueueButtonDays=Adicionar à fila ({0} dias)					// d for days
UI.Fleets.FleetListButtonText=Frotas
UI.Fleets.RefitDays=Modificar ({0} dias)
UI.Fleets.NumShipsSingle={0} nave
UI.Fleets.NumShipsPlural={0} naves
UI.Fleets.RefitIterationSuffix=em Caixa
UI.Fleets.NIS={0}+{1}
UI.Fleets.Explosive=<color=#FFFFFFFF><sprite name=warning></color>Este módulo pode explodir se receber dano.
UI.Fleets.FleetsListTab=Lista de frotas
UI.Fleets.ShipDetailTab=Detalhes da nave
UI.Fleets.AlertLevel=Nível de alerta
UI.Fleets.ArrivalTime=Tempo de chegada